### ISSUE TITLE
Interactions screen - Expand / Contract button for Forces should be on the left of the label

### ISSUE THREAD

**Issue by kmsravindra** [phetsims/states-of-matter#10]
Interactions screen - Expand / Contract button for Forces should be to the left side of the label "Forces". Please see mock-up

**Comment by notsiddhartha** [comment]
Fixed here: https://github.com/phetsims/atomic-interactions/commit/e41e8e4b70abdcc911e1e6988f1edf4c3c51ec80
Assigning to @kmsravindra for verification

**Comment by kmsravindra** [comment]
Looks good. Closing
