### ISSUE TITLE
Illustrator files needed for home screen icons

### ISSUE THREAD

**Issue by jbphet** [phetsims/states-of-matter#103]
I have PNG files for the home screens, but not the .ai files.  @arouinfar - can I get those from you?

For reference, here is what they look like:

![som-home-screen](https://cloud.githubusercontent.com/assets/3082831/9183078/57d75720-3f6a-11e5-8624-6b4a2bed9dc5.png)

**Comment by arouinfar** [comment]
@jbphet there are a few tweaks that need to be made to the home screen icons that have been documented in #69. The Phase Changes and Interaction screen icons will be drawn in code. I have re-sent the asset files for the States screen to you.

**Comment by jbphet** [comment]
The icons for the 2nd two screens are now created completely in code, so no asset needed for those.  The icon for the first screen is created using the three images that represent solid, liquid, and gas throughout the sim, and I now have those assets.  So, we've got everything we need for this.  Closing.
