### ISSUE TITLE
Log of minor UI issues

### ISSUE THREAD

**Issue by kmsravindra** [phetsims/states-of-matter#11]
Interaction screen - 
1. Please check the label punctuation of Large/Small/Weak/Strong. They should read large/small/weak/strong. Please check all label punctuation.
2. The bottom bar label for Interaction sim should just read Interaction.
3. The horizontal adjustable green bar in interaction screen should be much thinner while the vertical green double arrows should be slightly broader. Please see mock-up.
4. The symbols epsilon and sigma can be larger. Please see mock-up.
5. When reset with "Forces" label in expandable state, its not getting reset to contracted state.
6. The violet circle for adjustable attraction is same size as orange circle for Argon. Please see mock-up

Phase changes screen - 
1. The name of the diagram should read "Interaction Potential" and not interaction diagram
2. The label punctuation for Weak/Strong should be weak/strong
3. The handle on the container should be much smaller. Please see mock-up
4. Thermometer is much closer the pressure sensor inlet tube.
5. The size of all 3 wrapper boxes for atoms & molecules, interaction potential and phase diagram should be same. Please see mock-up
6. The label should read Interaction Potential and not interaction diagram
7. The labels pressure and potential energy should be aligned one below the other exactly.
8. The red circle in phase diagram should move along the black line. It looks like it moves slightly above the black line

**Comment by notsiddhartha** [comment]
Fixed with the above commits. Assigning to @kmsravindra for verification.

**Comment by kmsravindra** [comment]
Looks good. Closing
