### ISSUE TITLE
InteractionPotentialCanvasNode catch / paintCanvas

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/states-of-matter#110]
It has a try/catch that is preventing automated testing from finding legitimate errors. I'd highly recommend the try/catch not be used.

Additionally, see https://github.com/phetsims/scenery/issues/480 about not calling setShape() on arrows in paintCanvas(). I'd recommend applying those changes in the view step instead.

Let me know if there are any questions about this, I'm available to help.

**Comment by jonathanolson** [comment]
Also, this will be a very blocking issue, as it will cause the built version of the sim to infinite-loop on Edge.

**Comment by jbphet** [comment]
This issue has been addressed by moving the updates of non-canvas nodes out of the paintCanvas call in InteractionPotentialCanvasNode.  Fuzz testing is now succeeding.  Closing.
