### ISSUE TITLE
Thermometer remains at absolute zero after adding moving atoms

### ISSUE THREAD

**Issue by brroberts1231** [phetsims/states-of-matter#117]
For phetsims/tasks#609
Test device: Bates

Operating System: Windows 7

Browser: Chrome

Problem description: In the phase changes screen, if there are no atoms in the container, the thermometer will read 0 K, which is valid. But then if you pump in new atoms, they will be moving around, but the thermometer will still read 0 K, which would only be correct if the atoms are not moving. The pressure gauge updates correctly as atoms enter the tank, but the thermometer does not. The temperature won't update until you move the lid, and while it's moving, it touches an atom.

Steps to reproduce: Push down the lid of the container until the pressure causes it to explode as many times as necessary so that when you finally replace the lid, there are no more atoms in the container. Then use the pump to add new atoms in. The pressure gauge will change once atoms hit the lid, but the thermometer will not.

Screenshots:
![states of matter 1](https://cloud.githubusercontent.com/assets/11947677/15758857/a57822a4-28c9-11e6-827e-5661e65ff752.JPG)
![states of matter 2](https://cloud.githubusercontent.com/assets/11947677/15758900/ccedd310-28c9-11e6-89c2-57d572c89ee1.JPG)

Troubleshooting information (do not edit):
Name: ‪States of Matter‬
URL: http://www.colorado.edu/physics/phet/dev/html/states-of-matter/1.0.0-dev.6/states-of-matter_en.html
Version: 1.0.0-dev.6 2016-06-02 15:57:50 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.63 Safari/537.36
Language: en-US
Window: 1366x667
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 10 uniform: 253
Texture: size: 8192 imageUnits: 16 (vertex: 4, combined: 20)
Max viewport: 4096x4096
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"7d27130a","branch":"master"},"axon":{"sha":"1f807347","branch":"master"},"babel":{"sha":"b90d3542","branch":"master"},"brand":{"sha":"bb1cfcc6","branch":"master"},"chipper":{"sha":"a01a8e0f","branch":"master"},"dot":{"sha":"04efe0bc","branch":"master"},"joist":{"sha":"76d9aa21","branch":"master"},"kite":{"sha":"dce9765e","branch":"master"},"nitroglycerin":{"sha":"ad3cb990","branch":"master"},"phet-core":{"sha":"c48bf320","branch":"master"},"phetcommon":{"sha":"35ef94ad","branch":"master"},"scenery":{"sha":"4fb54ac9","branch":"master"},"scenery-phet":{"sha":"1bd4aed0","branch":"master"},"sherpa":{"sha":"e1b3c84b","branch":"master"},"states-of-matter":{"sha":"83399aac","branch":"master"},"sun":{"sha":"b708d54f","branch":"master"},"tandem":{"sha":"0e40c775","branch":"master"}}

**Comment by aadish** [comment]
@arouinfar when adding more particles in the container the pressure goes up but the temperature remains constant and this is in sync with Java Version what do you think

**Comment by aadish** [comment]
there was a piece of code which was not ported from the java version which deals with when container was empty, fixed in above commit

**Comment by brroberts1231** [comment]
For phetsims/tasks#611
dev.7: Appears to be fixed for Neon, Argon, and Adjustable Attraction, but not Oxygen or Water. So far only tested on Win 7 Chrome and Firefox. 

Also, on one occasion something interesting happened with Oxygen that I haven't been able to recreate since. After pumping in the particles to the empty container, the molecules slowed down and stopped moving on their own, as if I had cooled them to 0K, but I didn't touch the cooling slider. This only happened once, and the usual behavior is that they keep moving while the thermometer still reads 0K.

**Comment by jbphet** [comment]
Fixed this so that oxygen and water are now properly handled.  Assigning to @brroberts1231 to verify off of master.

**Comment by jbphet** [comment]
Assigning to @phet-steele to verify off master, since I know he's around.

**Comment by phet-steele** [comment]
@jbphet, I talked with @arouinfar and the scenario in this issue needs to match the solution in #129. Any particles added to a container at 0 K should only raise the temperature to 2 K (currently the temperature rises to the critical point of the selected particle).

**Comment by jbphet** [comment]
I don't think 2k is what we want in this case.  The particles are injected with an initial velocity that corresponds to the critical point, and if a number of particles are pumped in, they will appear to be in the gaseous state.  Having the thermometer read 2k in this situation would obviously be wrong.  @phet-steele was arguing for having no reading at all for the empty container.  If that works better, that's fine, but having it fixed at 2k in this case seems incorrect to me.  Back to @arouinfar to decide.

**Comment by arouinfar** [comment]
That sounds like a great idea @phet-steele @jbphet. Since there's no matter to measure the temperature of, it seems reasonable to disable the thermometer (display a dash) when the container is empty. That way, when gas is pumped in at the critical point it doesn't seem discrepant from the case where particles are cooled to 0K.

**Comment by jbphet** [comment]
I've implemented this, here's a screenshot of what it looks like:

![som-no-temp](https://cloud.githubusercontent.com/assets/3082831/17755450/34672a10-6497-11e6-89ff-445b392ef259.PNG)

Assigning to @arouinfar to test on master and close this issue if the behavior looks good.

**Comment by arouinfar** [comment]
👍
