### ISSUE TITLE
No Return Lid button on States screen

### ISSUE THREAD

**Issue by phet-steele** [phetsims/states-of-matter#121]
Blowing the lid off of the container on the States screen has no "Return Lid" button. @aadish @arouinfar I feel it should?

![screen shot 2016-06-03 at 2 45 02 pm](https://cloud.githubusercontent.com/assets/5863899/15792325/cb507050-2999-11e6-8e7e-af172b485c7e.png)

Seen on OSX 10.11.5 Chrome. For phetsims/tasks/issues/609.

Troubleshooting information:
Name: ‪States of Matter‬
URL: http://www.colorado.edu/physics/phet/dev/html/states-of-matter/1.0.0-dev.6/states-of-matter_en.html
Version: 1.0.0-dev.6 2016-06-02 15:57:50 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.79 Safari/537.36
Language: en-US
Window: 2146x1322
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 32 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 16)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"7d27130a","branch":"master"},"axon":{"sha":"1f807347","branch":"master"},"babel":{"sha":"b90d3542","branch":"master"},"brand":{"sha":"bb1cfcc6","branch":"master"},"chipper":{"sha":"a01a8e0f","branch":"master"},"dot":{"sha":"04efe0bc","branch":"master"},"joist":{"sha":"76d9aa21","branch":"master"},"kite":{"sha":"dce9765e","branch":"master"},"nitroglycerin":{"sha":"ad3cb990","branch":"master"},"phet-core":{"sha":"c48bf320","branch":"master"},"phetcommon":{"sha":"35ef94ad","branch":"master"},"scenery":{"sha":"4fb54ac9","branch":"master"},"scenery-phet":{"sha":"1bd4aed0","branch":"master"},"sherpa":{"sha":"e1b3c84b","branch":"master"},"states-of-matter":{"sha":"83399aac","branch":"master"},"sun":{"sha":"b708d54f","branch":"master"},"tandem":{"sha":"0e40c775","branch":"master"}}

**Comment by arouinfar** [comment]
Nice observation @phet-steele! While this matches the Java behavior, I'm not sure what motivated this design decision. Perhaps this case wasn't considered because it takes quite a long time to blow the lid off in the States screen? 

Let's add a Return Lid button to the States screen @aadish.

**Comment by ariel-phet** [comment]
@emily-phet do you remember what there is no such button in the Java version?

**Comment by emily-phet** [comment]
@ariel-phet - I don't recall the exact conversation, but as I think through it now I'm not sure that "return lid" is needed. For this screen, the primary goal is about distinguishing between the different phases, not thinking about pressure so much. Students can use reset to reset the container, and the select the solid/liquid/gas button to get close to there last state/temperature quickly.

**Comment by aadish** [comment]
@ariel-phet what is the final take on this, should we add it or not

**Comment by ariel-phet** [comment]
Considering @emily-phet comments we should not. Closing
