### ISSUE TITLE
Phase Diagram overlaps Reset All button

### ISSUE THREAD

**Issue by brroberts1231** [phetsims/states-of-matter#127]
Test device: Vygotsky 

Operating System: Chrome OS

Browser: Chrome

Problem description: On the phase changes screen, the phase diagram window overlaps the reset all button.

Screenshots:
![screenshot 2016-06-06 at 2 08 01 pm](https://cloud.githubusercontent.com/assets/11947677/15836040/253a0678-2bf0-11e6-91dd-1435665a8f61.png)

Troubleshooting information (do not edit):
Name: ‪States of Matter‬
URL: http://www.colorado.edu/physics/phet/dev/html/states-of-matter/1.0.0-dev.6/states-of-matter_en.html
Version: 1.0.0-dev.6 2016-06-02 15:57:50 UTC
Features missing: touch
User Agent: Mozilla/5.0 (X11; CrOS armv7l 7978.74.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.103 Safari/537.36
Language: en-US
Window: 1366x655
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 15 uniform: 1024
Texture: size: 8192 imageUnits: 16 (vertex: 16, combined: 48)
Max viewport: 8192x8192
OES_texture_float: false
Dependencies JSON: {"assert":{"sha":"7d27130a","branch":"master"},"axon":{"sha":"1f807347","branch":"master"},"babel":{"sha":"b90d3542","branch":"master"},"brand":{"sha":"bb1cfcc6","branch":"master"},"chipper":{"sha":"a01a8e0f","branch":"master"},"dot":{"sha":"04efe0bc","branch":"master"},"joist":{"sha":"76d9aa21","branch":"master"},"kite":{"sha":"dce9765e","branch":"master"},"nitroglycerin":{"sha":"ad3cb990","branch":"master"},"phet-core":{"sha":"c48bf320","branch":"master"},"phetcommon":{"sha":"35ef94ad","branch":"master"},"scenery":{"sha":"4fb54ac9","branch":"master"},"scenery-phet":{"sha":"1bd4aed0","branch":"master"},"sherpa":{"sha":"e1b3c84b","branch":"master"},"states-of-matter":{"sha":"83399aac","branch":"master"},"sun":{"sha":"b708d54f","branch":"master"},"tandem":{"sha":"0e40c775","branch":"master"}}

**Comment by brroberts1231** [comment]
For phetsims/tasks#609

**Comment by brroberts1231** [comment]
Possibly only occurs on Chromebook, because I don't recall seeing this before, and it doesn't appear in #126 either

**Comment by phet-steele** [comment]
Fixed in 1.0.0-dev.7
