### ISSUE TITLE
Pin button moves to different locations when on the adjustable attraction option

### ISSUE THREAD

**Issue by alynne-phet** [phetsims/states-of-matter#130]
For phetsims/tasks/issues/611
Test Device: Personal Laptop
Operating System: Mac OSX 10.11.5
Browser: Chrome

Problem Description: On the Interaction screen with the adjustable attraction option selected, the pin button moves to different locations. Occasionally it is directly on top of the atom, whereas other times it isn't even touching the atom. Also seen on Atomic Interactions sim.

Steps to Reproduce:
1. Select the adjustable attraction option
2. Move the atom diameter to the smallest size
3. Go back to any of the other atom options
4. Select the adjustable attraction option a second time

Screenshots from Atomic Interactions sim:

![image](https://cloud.githubusercontent.com/assets/19288972/16014711/a34345ac-314f-11e6-80bb-5d5172f58e42.png)

![image](https://cloud.githubusercontent.com/assets/19288972/16014714/a8f97a34-314f-11e6-885a-8df15cbc0109.png)

Name: ‪States of Matter‬
URL: http://www.colorado.edu/physics/phet/dev/html/states-of-matter/1.0.0-dev.7/states-of-matter_en.html
Version: 1.0.0-dev.7 2016-06-08 22:25:11 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.84 Safari/537.36
Language: en-US
Window: 1373x725
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 32 uniform: 768
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 16)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"7d27130a","branch":"master"},"axon":{"sha":"1f807347","branch":"master"},"babel":{"sha":"dedd008d","branch":"master"},"brand":{"sha":"f0b1f7da","branch":"master"},"chipper":{"sha":"1586048b","branch":"master"},"dot":{"sha":"9b554e82","branch":"master"},"joist":{"sha":"83de2b95","branch":"master"},"kite":{"sha":"dce9765e","branch":"master"},"nitroglycerin":{"sha":"ad3cb990","branch":"master"},"phet-core":{"sha":"c48bf320","branch":"master"},"phetcommon":{"sha":"35ef94ad","branch":"master"},"scenery":{"sha":"00bd89f4","branch":"master"},"scenery-phet":{"sha":"cc33f674","branch":"master"},"sherpa":{"sha":"e1b3c84b","branch":"master"},"states-of-matter":{"sha":"f8fd765a","branch":"master"},"sun":{"sha":"f2631eea","branch":"master"},"tandem":{"sha":"b3c68afa","branch":"master"}}

**Comment by jbphet** [comment]
This is an issue in the original Java sim too, we just (apparently) never noticed it.  Here is a screenshot:

![som-pin-off](https://cloud.githubusercontent.com/assets/3082831/17073181/95e9fff4-502b-11e6-9db3-8537928e130b.PNG)

**Comment by jbphet** [comment]
I've added code to update the position of the push pin any time a new fixed atom is added.  This should fix the problem, assigning back to @alynne-phet to verify on master.

**Comment by alynne-phet** [comment]
Fixed! Closing
