### ISSUE TITLE
[Chromebook] Parenthesis spacing

### ISSUE THREAD

**Issue by phet-steele** [phetsims/states-of-matter#131]
@jbphet on chromebook, the spacing of the parenthesis here is a little strange (only for van der Waals). This is on the Interaction screen and 1.0.0-dev.7: 
![screenshot 2016-07-05 at 11 33 00 am](https://cloud.githubusercontent.com/assets/5863899/16593797/608bba76-42a4-11e6-9e08-f0f5657523af.png)
For phetsims/tasks/issues/611.
Troubleshooting information:
Name: ‪States of Matter‬
URL: http://www.colorado.edu/physics/phet/dev/html/states-of-matter/1.0.0-dev.7/states-of-matter_en.html
Version: 1.0.0-dev.7 2016-06-08 22:25:11 UTC
Features missing: touch
User Agent: Mozilla/5.0 (X11; CrOS x86_64 7978.66.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.91 Safari/537.36
Language: en-US
Window: 1366x655
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 32 uniform: 4096
Texture: size: 8192 imageUnits: 32 (vertex: 32, combined: 96)
Max viewport: 8192x8192
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"7d27130a","branch":"master"},"axon":{"sha":"1f807347","branch":"master"},"babel":{"sha":"dedd008d","branch":"master"},"brand":{"sha":"f0b1f7da","branch":"master"},"chipper":{"sha":"1586048b","branch":"master"},"dot":{"sha":"9b554e82","branch":"master"},"joist":{"sha":"83de2b95","branch":"master"},"kite":{"sha":"dce9765e","branch":"master"},"nitroglycerin":{"sha":"ad3cb990","branch":"master"},"phet-core":{"sha":"c48bf320","branch":"master"},"phetcommon":{"sha":"35ef94ad","branch":"master"},"scenery":{"sha":"00bd89f4","branch":"master"},"scenery-phet":{"sha":"cc33f674","branch":"master"},"sherpa":{"sha":"e1b3c84b","branch":"master"},"states-of-matter":{"sha":"f8fd765a","branch":"master"},"sun":{"sha":"f2631eea","branch":"master"},"tandem":{"sha":"b3c68afa","branch":"master"}}

**Comment by jbphet** [comment]
Should now be fixed on master, back to @phet-steele to validate on master.

**Comment by phet-steele** [comment]
@brroberts1231 might have a chance to look at this before me, assigning to him.

**Comment by phet-steele** [comment]
👍
