### ISSUE TITLE
Red point on the phase diagram goes off of the graph

### ISSUE THREAD

**Issue by alynne-phet** [phetsims/states-of-matter#132]
For phetsims/tasks#611
Test Device: Personal Laptop
Operating System: Mac OSX 10.11.5
Browser: Chrome

Problem Description: On the Phase Changes screen when the atom is completely cooled, the red point on the phase diagram goes off of the graph past the white arrow lines.

Steps to Reproduce:
1. Choose any of the atoms or molecules
2. Use the bucket of ice to cool the atoms or molecules to 0 K
3. Notice that the red point goes off of the phase diagram

Screenshots:

![image](https://cloud.githubusercontent.com/assets/19288972/16596563/c541ee42-42b1-11e6-8c6f-900f93a008ca.png)

Name: ‪States of Matter‬
URL: http://www.colorado.edu/physics/phet/dev/html/states-of-matter/1.0.0-dev.7/states-of-matter_en.html
Version: 1.0.0-dev.7 2016-06-08 22:25:11 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36
Language: en-US
Window: 1386x718
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 32 uniform: 768
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 16)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"7d27130a","branch":"master"},"axon":{"sha":"1f807347","branch":"master"},"babel":{"sha":"dedd008d","branch":"master"},"brand":{"sha":"f0b1f7da","branch":"master"},"chipper":{"sha":"1586048b","branch":"master"},"dot":{"sha":"9b554e82","branch":"master"},"joist":{"sha":"83de2b95","branch":"master"},"kite":{"sha":"dce9765e","branch":"master"},"nitroglycerin":{"sha":"ad3cb990","branch":"master"},"phet-core":{"sha":"c48bf320","branch":"master"},"phetcommon":{"sha":"35ef94ad","branch":"master"},"scenery":{"sha":"00bd89f4","branch":"master"},"scenery-phet":{"sha":"cc33f674","branch":"master"},"sherpa":{"sha":"e1b3c84b","branch":"master"},"states-of-matter":{"sha":"f8fd765a","branch":"master"},"sun":{"sha":"f2631eea","branch":"master"},"tandem":{"sha":"b3c68afa","branch":"master"}}

**Comment by jbphet** [comment]
I fixed this by added a clip region so that the dot can still get to x=0 and y=0 but doesn't go off the graph.  Back to @alynne-phet for testing on master.

**Comment by phet-steele** [comment]
@jbphet the axis arrows have a certain line thickness, and in 1.0.0-dev.7 it looks like the dot is centered on the left edge of the y-axis arrow and almost the bottom edge of the x-axis arrow (making it look to go off the graph).
<img width="373" alt="screen shot 2016-07-25 at 1 12 07 pm" src="https://cloud.githubusercontent.com/assets/5863899/17113796/6de4e42a-5269-11e6-8f7e-8f368d97f736.png">

An alternative would be to move the (0,0) position to be centered along the intersection of both lines, so the dot is centered between both edges of each line like so:
<img width="423" alt="screen shot 2016-07-25 at 1 11 31 pm" src="https://cloud.githubusercontent.com/assets/5863899/17113774/57b8a2f4-5269-11e6-9349-92a4b02df3bd.png">

**Comment by phet-steele** [comment]
For the record, clip area looks a little strange:
<img width="625" alt="screen shot 2016-07-25 at 1 16 32 pm" src="https://cloud.githubusercontent.com/assets/5863899/17113944/09607a22-526a-11e6-9080-0100b6f800c2.png">

**Comment by jbphet** [comment]
I removed the clipping area and improved the positioning accuracy of the red marker.  Seems like this fix addresses the issue better than the clipping region.  @phet-steele - give this a try and, if it looks good, please close the issue.

**Comment by alynne-phet** [comment]
@jbphet This looks good to me.

**Comment by phet-steele** [comment]
@jbphet this dot is great! Best dot ever! Thanks!
