### ISSUE TITLE
Interaction strength arrow overlaps some of the letters on the x-axis title

### ISSUE THREAD

**Issue by alynne-phet** [phetsims/states-of-matter#133]
For phetsims/tasks#611
Test Device: Personal Laptop
Operating System: Mac OSX 10.11.5
Browser: Chrome

Problem Description: On the Interaction screen on the adjustable attraction option, the interaction strength arrow overlaps some of the letters on the x-axis title. 

Steps to Reproduce:
1. Choose the adjustable attraction option
2. Set the interaction strength to strong
3. Move the atom diameter arrow until the interaction arrow is above the x-axis title

![image](https://cloud.githubusercontent.com/assets/19288972/16597827/2896002c-42b8-11e6-83d5-6513d43cd958.png)

Name: ‪States of Matter‬
URL: http://www.colorado.edu/physics/phet/dev/html/states-of-matter/1.0.0-dev.7/states-of-matter_en.html
Version: 1.0.0-dev.7 2016-06-08 22:25:11 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.106 Safari/537.36
Language: en-US
Window: 1386x718
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 32 uniform: 768
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 16)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"7d27130a","branch":"master"},"axon":{"sha":"1f807347","branch":"master"},"babel":{"sha":"dedd008d","branch":"master"},"brand":{"sha":"f0b1f7da","branch":"master"},"chipper":{"sha":"1586048b","branch":"master"},"dot":{"sha":"9b554e82","branch":"master"},"joist":{"sha":"83de2b95","branch":"master"},"kite":{"sha":"dce9765e","branch":"master"},"nitroglycerin":{"sha":"ad3cb990","branch":"master"},"phet-core":{"sha":"c48bf320","branch":"master"},"phetcommon":{"sha":"35ef94ad","branch":"master"},"scenery":{"sha":"00bd89f4","branch":"master"},"scenery-phet":{"sha":"cc33f674","branch":"master"},"sherpa":{"sha":"e1b3c84b","branch":"master"},"states-of-matter":{"sha":"f8fd765a","branch":"master"},"sun":{"sha":"f2631eea","branch":"master"},"tandem":{"sha":"b3c68afa","branch":"master"}}

**Comment by alynne-phet** [comment]
This is seen in the Atomic Interactions sim as well

**Comment by jbphet** [comment]
Should be fixed, back to @alynne-phet to verify on master.

**Comment by alynne-phet** [comment]
Fixed. Closing
