### ISSUE TITLE
Update Projector Mode Colors

### ISSUE THREAD

**Issue by arouinfar** [phetsims/states-of-matter#135]
The projector mode colors need updating. I will work on these, and then pass them along to @jbphet to implement.

**Comment by arouinfar** [comment]
Global panel colors
* White panel fill
* Black panel stroke
* Black text
* Black selection stroke
* Black slider track
* Black graph axes

Additionally, for the interaction potentials
* Black sigma/epsilon fill (no stroke)
* Black sigma/epsilon arrow fill with white stroke 
* Red interaction potential line (match the red used on the Interaction screen in non-projector mode) -- Please make this change to Atomic Interactions too



The bike pump artwork (left) also needs some tweaking to work on a white background. I've updated the artwork (right), and will send the asset files to @jbphet.
![image](https://cloud.githubusercontent.com/assets/8419308/17340996/daf76cda-58af-11e6-8f07-1332d8282d31.png)   ![image](https://cloud.githubusercontent.com/assets/8419308/17341140/827cac5e-58b0-11e6-9856-969bb03f5e25.png)

**Comment by arouinfar** [comment]
Assigning to @jbphet for implementation.

**Comment by jbphet** [comment]
@amyh-phet - I've worked through a number of the issues for the projector mode.  I'd like to set up a time to look at a few things with you, such as the sigma and epsilon arrows.  Let's set up a time and see if we can finalize this, I'm thinking it will take roughly an hour.

**Comment by amyh-phet** [comment]
@jbphet. Is this for @arouinfar?  Happy to set up a time if you need me to weigh in.

**Comment by arouinfar** [comment]
@amyh-phet pretty sure he meant me :)

@jbphet does tomorrow work for you? My schedule is flexible.

**Comment by jbphet** [comment]
@arouinfar and I reviewed this together, made some final changes, and agree that it is now acceptable.  Closing.
