### ISSUE TITLE
Fix the panel layout

### ISSUE THREAD

**Issue by phet-steele** [phetsims/states-of-matter#136]
A reminder for @jbphet to revert a commit made that moved some panels around. Currently, master of Atomic Interactions looks like the image below. The panels used to be to the left more so as to not cover the reset all button:

<img width="429" alt="screen shot 2016-08-03 at 2 18 05 pm" src="https://cloud.githubusercontent.com/assets/5863899/17381368/c5220e04-5988-11e6-8ce7-4cf055a596ca.png">

**Comment by jbphet** [comment]
Should now be fixed, please test and close if so.

**Comment by phet-steele** [comment]
👍
