### ISSUE TITLE
Move vector icons in Force panels to the right

### ISSUE THREAD

**Issue by arouinfar** [phetsims/states-of-matter#139]
In SOM and Atomic Interactions, the vector icons in the force panels are a bit too close to the text
![image](https://cloud.githubusercontent.com/assets/8419308/17444968/fcf903d2-5aff-11e6-89a2-f847b01053b4.png)

It also looks like the current location of the vector icons restricts the length of the strings during i18n.
![image](https://cloud.githubusercontent.com/assets/8419308/17445169/d47e5564-5b00-11e6-8cca-1d52a8e166f7.png)

It would look a bit better if the vector icons could be moved further to the right like this
![image](https://cloud.githubusercontent.com/assets/8419308/17444928/d7b09bc6-5aff-11e6-94b0-1ed812039a0f.png)

For comparison, here are the old (left) and new (right) locations for the icons.
![image](https://cloud.githubusercontent.com/assets/8419308/17444999/0f58a6ae-5b00-11e6-9cc8-ae65ca0b6b48.png)

Assigning to @jbphet.

**Comment by jbphet** [comment]
I've added some padding, assigning to @arouinfar to verify on the next dev version, which I'm just about to publish.

**Comment by arouinfar** [comment]
Looks great! Closing.
