### ISSUE TITLE
Can we update the pressure gauge less frequently?

### ISSUE THREAD

**Issue by jbphet** [phetsims/states-of-matter#140]
The pressure gauge currently updates every frame.  I'm currently working on improving the performance (see https://github.com/phetsims/states-of-matter/issues/71) and in the process of doing some profiling I can see the the updates to the pressure gauge are taking around 5% of the update time for each frame.  I'm going to try reducing the update frequency to something like every 1/2 second in order to improve performance.  I'd like to make sure that no one objects to this change.  The only objection that I can think of is that the frequent updates make it clear that the pressure is a result of the atoms or molecules hitting the wall, but in my opinion updating every 1/2 second should still get that across reasonably well.

Assigning to @arouinfar for her input.

**Comment by arouinfar** [comment]
That sounds like very reasonable approach, and I would imagine that updates every 1/2 second should be sufficient to observe that pressure is a result of collisions with the container.

Go for it @jbphet!

**Comment by jbphet** [comment]
Done, looks pretty decent to me, closing.
