### ISSUE TITLE
Lid compression rate

### ISSUE THREAD

**Issue by phet-steele** [phetsims/states-of-matter#145]
The maximum rate at which the lid can be lowered should be compared to the Java version.

For phetsims/tasks/issues/687

**Comment by phet-steele** [comment]
Right away, big differences. Videos coming soon.

**Comment by phet-steele** [comment]
@jbphet @ariel-phet @arouinfar here are the results.
Java takes this long, also notice that the expansion rate is much quicker than the compression:
![som02](https://cloud.githubusercontent.com/assets/5863899/17977739/29829566-6ab0-11e6-862f-14064e1ed853.gif)

The 1.0.0-dev.10 version of HTML5 takes this long with similar expression/compression rates:
![som03](https://cloud.githubusercontent.com/assets/5863899/17977956/f8d2e12c-6ab0-11e6-9560-ebe49c51ef58.gif)

**Comment by arouinfar** [comment]
@jbphet I think it's okay if the compression and expansion rates are similar, but we'll want to slow down the compression rate to about half of what @phet-steele showed in dev.10. I think this will more closely match the Java behavior, and address the concerns that @kathy-phet raised during status.

**Comment by ariel-phet** [comment]
Yes, definitely match java behavior

**Comment by jbphet** [comment]
Fix committed, see https://github.com/phetsims/states-of-matter/commit/61092355900e980a010d87a8fbfdec84d300e2a0 (forgot to reference this issue in commit message).

**Comment by jbphet** [comment]
Assigning to @phet-steele to verify on master.

**Comment by phet-steele** [comment]
@jbphet both master and 1.0.0-dev.11 look good.
