### ISSUE TITLE
Phase Diagram point when temp is "-"

### ISSUE THREAD

**Issue by phet-steele** [phetsims/states-of-matter#149]
Phase Changes screen, continuously compress and explode the container until there are no more molecules left in the container. Return the lid. From the changes in #117, the thermometer will display a "-", but there is still a corresponding dot on the phase diagram (that shouldn't be there):

<img width="1284" alt="screen shot 2016-08-29 at 11 00 28 am" src="https://cloud.githubusercontent.com/assets/5863899/18059946/c16135d8-6dd8-11e6-99c1-b718f9a5b282.png">

Seen on Mac OSX 10.11.6. For phetsims/tasks/issues/687.
Troubleshooting information:
Name: ‪States of Matter‬
URL: http://www.colorado.edu/physics/phet/dev/html/states-of-matter/1.0.0-dev.10/states-of-matter_en.html
Version: 1.0.0-dev.10 2016-08-24 21:42:56 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36
Language: en-US
Window: 1388x1000
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 32 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 16)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"7d27130a","branch":"master"},"axon":{"sha":"1fd91832","branch":"master"},"babel":{"sha":"5e625a61","branch":"master"},"brand":{"sha":"f0b1f7da","branch":"master"},"chipper":{"sha":"89c4a103","branch":"master"},"dot":{"sha":"6e8a26f2","branch":"master"},"joist":{"sha":"ab5582ab","branch":"master"},"kite":{"sha":"88f0c3a0","branch":"master"},"nitroglycerin":{"sha":"ad3cb990","branch":"master"},"phet-core":{"sha":"c48bf320","branch":"master"},"phetcommon":{"sha":"83ea84c8","branch":"master"},"scenery":{"sha":"0ab22ac3","branch":"master"},"scenery-phet":{"sha":"1650643c","branch":"master"},"sherpa":{"sha":"5ddfccd4","branch":"master"},"states-of-matter":{"sha":"8ce7fdc3","branch":"master"},"sun":{"sha":"061f2ea9","branch":"master"},"tandem":{"sha":"43ebdfb3","branch":"master"}}

**Comment by jbphet** [comment]
Fixed, assigning to @phet-steele to verify on master.

**Comment by phet-steele** [comment]
@jbphet master looks good.
