### ISSUE TITLE
iPad2 - Changing the tabs in bottom bar is too slow

### ISSUE THREAD

**Issue by kmsravindra** [phetsims/states-of-matter#15]
When clicking on tabs "States" / "Phase changes" / "Interaction" the respective screen takes quite a while to change.

**Comment by jbphet** [comment]
I compared this behavior in the latest dev version ((http://www.colorado.edu/physics/phet/dev/html/states-of-matter/1.0.0-dev.5/states-of-matter_en.html)  to that of the currently published version of Balancing Act, which is also a three-screen sim.  They were pretty comparable.  I think this is about as good as we can expect on an iPad 2.  Will close for now, and reopen if necessary.
