### ISSUE TITLE
Lid is unable to compress with large amounts of molecules

### ISSUE THREAD

**Issue by phet-steele** [phetsims/states-of-matter#150]
@jbphet there is some seriously confusing behaviour with the lid. When there is a large amount of particles in the container (usually max amount), the lid refuses to be dragged below a certain point. The point is different depending on particle type/amount. 

An example procedure with Argon:
1. Compress the container until the lid is right above the pump nozzle.
2. Cool to 0 K.
3. Add argon until there is no more to add. Be sure to keep a close eye on the pressure. Regulate the temperature to not let the container explode.
4. Try to compress the lid further, but instead the lid moves upwards. You can then not drag it any lower.

This video has cut out most of the pumping/cooling, otherwise it would be a long video:

![som04](https://cloud.githubusercontent.com/assets/5863899/18069437/5f1887b0-6e04-11e6-8a3c-8051fd62c02a.gif)

Seen on Mac OSX 10.11.6. For phetsims/tasks/issues/687.
Troubleshooting information:
Name: ‪States of Matter‬
URL: http://www.colorado.edu/physics/phet/dev/html/states-of-matter/1.0.0-dev.10/states-of-matter_en.html
Version: 1.0.0-dev.10 2016-08-24 21:42:56 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36
Language: en-US
Window: 1388x1000
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 32 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 16)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"7d27130a","branch":"master"},"axon":{"sha":"1fd91832","branch":"master"},"babel":{"sha":"5e625a61","branch":"master"},"brand":{"sha":"f0b1f7da","branch":"master"},"chipper":{"sha":"89c4a103","branch":"master"},"dot":{"sha":"6e8a26f2","branch":"master"},"joist":{"sha":"ab5582ab","branch":"master"},"kite":{"sha":"88f0c3a0","branch":"master"},"nitroglycerin":{"sha":"ad3cb990","branch":"master"},"phet-core":{"sha":"c48bf320","branch":"master"},"phetcommon":{"sha":"83ea84c8","branch":"master"},"scenery":{"sha":"0ab22ac3","branch":"master"},"scenery-phet":{"sha":"1650643c","branch":"master"},"sherpa":{"sha":"5ddfccd4","branch":"master"},"states-of-matter":{"sha":"8ce7fdc3","branch":"master"},"sun":{"sha":"061f2ea9","branch":"master"},"tandem":{"sha":"43ebdfb3","branch":"master"}}

**Comment by jbphet** [comment]
I just tested this on the Java version of the sim, and it has the same issue.

**Comment by jbphet** [comment]
There was code that would calculate the minimum allowed container size based on the number of particles, but I don't know why it was there, and there were no comments that explained it.  I've gone ahead and removed it, which gets rid of the problematic behavior described above.  This should be thoroughly tested to see if removing it has some undesirable consequences.

Assigning to @phet-steele to test on master.

**Comment by phet-steele** [comment]
@jbphet, it's been 2 months since this was addressed and we haven't seen any odd behaviour. I think that's more than enough time for unintended consequences to crop up. I went ahead and followed the above procedure and saw no issue. Closing.
