### ISSUE TITLE
[branch] performance

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/states-of-matter#153]
Working on performance enhancements.

**Comment by jonathanolson** [comment]
Also the branch performance-no-gradients, which included stripping parts of the sim away to determine what in the drag causes lower performance.

**Comment by jbphet** [comment]
The performance branch has been merged with master, but I haven't done anything with the performance-no-gradients branch.  @jonathanolson - can we delete these branches and close this issue?

**Comment by jbphet** [comment]
The branch has been deleted, closing.
