### ISSUE TITLE
suspicious default cases in switch statements

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/states-of-matter#155]
Noticed while working on https://github.com/phetsims/chipper/issues/485 ...

There are a bunch of switch statements in `MultipleParticleModel` that look suspect.

(1) Three default cases use an anti-pattern for error handling, e.g.:

```js
422 default:
423   console.log( 'Error: Unrecognized molecule type when getting epsilon value.' );
424   epsilon = 0;
```

It it's truly an "Error", then why does the sim continue, rather than throwing an Error?

(2) This one has an unnecessary `break` in the `default` case:

```js
606  default:
607   // Use the default.
608   particle = new NeonAtom( 0, 0 );
609   break;
610 }
```

(3) In `getTemperatureInKelvin` and `getTwoDegreesKelvinInInternalTemperature` the default case is (e.g.):

```js
262  default:
263     break;
264 }
```

Besides the fact that the default case doesn't need a `break`, this switch leaves me wondering whether this is a bug, or if the intent is to use the default value of `triplePointInKelvin` for `MONATOMIC_OXYGEN` (the only molecule type that doesn't have a case). If it's not a bug, it would be better to have a case for `MONATOMIC_OXYGEN` and a default that throws an Error. I.e., replace the above with:

```js
case StatesOfMatterConstants. MONATOMIC_OXYGEN:
  triplePointInKelvin = ...;
  break;
default:
  throw new Error( 'unsupported molecule type: ' + this.currentMolecule );
}
```

**Comment by jbphet** [comment]
These were left over from the port by the original authors, and I'd noticed them but hadn't taken the time to clean them up.  I have now, putting ```throw new Error``` for most of them.

I don't agree that it's an anipattern to use a ```break``` statement in the ```default``` case.  Sure, it's the last case in the switch statement and it isn't technically required, but if anyone ever stuck another case below it, the default would flow into it, which wouldn't be good.  Here's an link to a post that discusses this: http://programmers.stackexchange.com/questions/201777/break-on-default-case-in-switch.  I've left one case of this in place, but added an assert.

I think this should do it, so I'll go ahead and close it.  @pixelzoom can reopen if he has any concerns.

**Comment by pixelzoom** [comment]
Looks good, with exception of lint error (fixed above).
