### ISSUE TITLE
container explosion occurs much more easily on older ipads

### ISSUE THREAD

**Issue by jbphet** [phetsims/states-of-matter#158]
When running on older iPads, such as an iPad 2, the container on the 2nd screen (Phase Changes) explodes much more easily than on a desktop or a newer iPad.

This issue can be seen on version http://www.colorado.edu/physics/phet/dev/html/states-of-matter/1.0.0-dev.11 and earlier.  

To duplicate:
- Start the sim
- Go to the 2nd screen (phase changes)
- Heat the default substance (Neon) to 60k
- Wait a few seconds until the particles are distributed pretty evenly throughout the container
- As quickly as the sim allows, move the lid down until the container size is reduced to roughly 2/3 of its original size (see screenshot below)

When this procedure is performed on my Win 10 desktop running Chrome or Firefox, or on a newer iPad (I tested on PhET's iPad Air 2 labeled "Dalton"), the pressure in the container will increase to about 60 or 70 atm and stabilize.  When tested on an iPad 2 (the one named "Witten"), this procedure leads to a very rapid increase in pressure and an explosion of the container.

Here is a screenshot that shows where the lid should be moved when performing this test:
![som-pressure](https://cloud.githubusercontent.com/assets/3082831/18684537/d0cb7b54-7f31-11e6-9b99-a765bd98e0a3.PNG)

**Comment by jbphet** [comment]
This behavior is due to the slower maximum frame rate that is achieved on the iPad 2.  The nominal frame rate when running on a good machine is 60 fps, but only 30 fps or less is being achieved on the iPad 2, and this frame rate goes down even further when the lid is being moved.  As a result, particles are ending up much closer to the lid when the lid is moving downwards in a during a time step, which results in greater repulsive force being applied to the particles near the lid, which results in more velocity for these particles, which causes the pressure to increase much more rapidly.

Here are some ideas of things to try, but I'm concerned that these may have undesirable consequences to other aspects of the sim's behavior.
1. lower the limits for max particle velocity resulting from interaction with the lid and wall
2. lower the limit for max particle velocity resulting from interaction with the lid
3. change the entire approach for particle-wall interaction to make them simple bounces (i.e. reversal of velocity vector) and add the velocity of the lid to the particle - this would less susceptible to variations in time step size 
4. add code to recognize long time steps and move all particles interacting with the lid to a safer distance before calculating the force on them

Of these options, I think number 3 would be the most likely to work without having other unanticipated consequences, but it would also be the most time consuming to implement.

**Comment by jbphet** [comment]
Assigning to @ariel-phet for discussion, prioritization, and such.

**Comment by jbphet** [comment]
By the way, I have a subjective comment about the current behavior on iPad 2:  I feel like the container explodes too easily due to this problem, and could potentially be a distraction for people trying to use the Phase Changes screen in labs and activities.

**Comment by ariel-phet** [comment]
Discussed with @jbphet and decided to proceed with (3)

**Comment by jbphet** [comment]
Assigning to @phet-steele to verify that this is fixed.  Version 1.0.0-dev.12 has the improved behavior.

**Comment by phet-steele** [comment]
Looks great in 1.0.0-dev.14
