### ISSUE TITLE
iPad2 - Phase changes screen - Grabbing / Pumping the pump handle is too slow

### ISSUE THREAD

**Issue by kmsravindra** [phetsims/states-of-matter#16]
1. Touch area for the grab handle for the pump might have to be increased
2. The handle is not moving in sync with swipe of the finger. Probably its too slow.

**Comment by jbphet** [comment]
This is still an issue in v1.0.0-dev.5 (http://www.colorado.edu/physics/phet/dev/html/states-of-matter/1.0.0-dev.5/states-of-matter_en.html).

**Comment by notsiddhartha** [comment]
Touch areas fixed by @ChandrashekarBemagoni in the above commit. 
The handle movement on iPad2 seems smooth. Assigning to @kmsravindra for verification

**Comment by kmsravindra** [comment]
This is fixed. Request your confirmation before closing this.

**Comment by jbphet** [comment]
I tested this and found the performance to still be poor on an iPad 2 (Tycho), and did some investigation.  The way the drag handler was implemented caused the pump handle to not go to the full extent of the drag if the user drags past the allowable range, which makes it feel like the motion isn't keeping up.  I fixed this, and the behavior is much better.  Closing.
