### ISSUE TITLE
consider removing "unsafe" particles

### ISSUE THREAD

**Issue by jbphet** [phetsims/states-of-matter#161]
As of this writing, the particle simulation portion of the code tracks whether or not a particle is considered "safe", meaning that it is okay to interact with other particles.  This was done to avoid problems with injecting new particles, since the appearance of new particles could cause instantaneous overlap with other particles, which would lead to super-high particle velocities, which could cause instant explosions of the container.  Particles are marked as unsafe until they are not overlapping any other particles, at which point they become safe and start interacting normally.

However, this approach can have some odd consequences, see https://github.com/phetsims/states-of-matter/issues/23.

In work that I just did for #158 and #71, I ended up putting some pretty severe limits on the amount of energy that a particle can obtain from interaction with other particles.  This may allow us to eliminate the whole "safe" designation and just allow particles to interact right away when injected.  I'd like to try this out as a sort of a fast prototype and test myself, and if it works get some QA test time and, if all looks good, move forward with this.

**Comment by phet-steele** [comment]
@jbphet I like this behaviour!
