### ISSUE TITLE
layout of screens is not using model-view transform

### ISSUE THREAD

**Issue by jbphet** [phetsims/states-of-matter#162]
While working on some layout issues, I noticed that the way that the particle canvas, the particle container, the container lid, and several other view components are being positioned is through the use of a bunch of tweaky constants instead of by using of a model-view transform.  This is true for ```StatesScreenView.js``` and ```PhaseChangesScreenView.js```.  This doesn't affect functionality, but it's a big maintainability issue and should be corrected.

**Comment by phet-steele** [comment]
@jbphet, you were mentioning how the container opening was something to fix. It is missing from the first screen all together.

![missingrim](https://cloud.githubusercontent.com/assets/5863899/19496803/728b357c-9546-11e6-9cf3-add2949c6093.PNG)

**Comment by jbphet** [comment]
This has been addressed, closing.
