### ISSUE TITLE
particles can be suspended above the surface, then resume moving at 0K

### ISSUE THREAD

**Issue by jbphet** [phetsims/states-of-matter#166]
When the temperature is reduced to 0K (absolute zero) very quickly, particles sometimes end up in suspended above the surface.  When the cooling stops (i.e. the slider on the heater-cooler node is released) the particles start moving again but the temperature stays at absolute zero, which is physically incorrect.

There should probably be some code that detects particles that are not on the floor of the container or near other particles and prevent the sim from reaching absolute zero.

**Comment by jbphet** [comment]
I've done a fair amount of work on this, and it seems like it's much improved at this point.  I'll have it checked out in the next round of dev testing.

**Comment by phet-steele** [comment]
@jbphet, particles can still be frozen in midair. If a particle(s) bounces off the bottom and moves upward, there is a chance that it will not make it back to the bottom of the container before reaching 0K. This will occur most often with fewer particles in the container. Maybe a case we don't care about, @jbphet?

Watch towards the left:
![som05](https://cloud.githubusercontent.com/assets/5863899/20412618/1e8976ee-ace5-11e6-924f-7de7797c06b2.gif)

**Comment by jbphet** [comment]
@phet-steele - please retest this on v1.0.0-dev.15.  If you are able to duplicate, please note how many attempts it required.

**Comment by phet-steele** [comment]
From my tests, it looks like this can't happen anymore. Instead, any particle suspended the moment the temperature hits 0K will continue to move towards the bottom. Once they reach the bottom, they stop moving. Closing.
