### ISSUE TITLE
Indicator on pump for amount of remaining particles

### ISSUE THREAD

**Issue by jbphet** [phetsims/states-of-matter#167]
The pump doesn't currently indicate to the user when they can't pump any more particles into the container - it just stops.  @ariel-phet and I discussed this and decided that some sort of visual indication would be good.  Something kind of like this might do the trick (with a single strip of squares of all the same color):

![led-bar-graph-vu-meter-dual-channel-level-indicator-display-](https://cloud.githubusercontent.com/assets/3082831/19534932/0c7585ae-9603-11e6-85db-e55f56e4c5f9.jpg)

**Comment by jbphet** [comment]
Assigning to @ariel-phet for review.

**Comment by ariel-phet** [comment]
I think this indicator is looking great in my opinion - clear feedback, not too eye-catching, and the indicator bars seem abstract enough not to be confused with particles.

@arouinfar please also weigh in (probably need to look at from phettest)

**Comment by arouinfar** [comment]
Looks great @jbphet! I think gray is a good choice here. Not too eye-catching, but clear.

**Comment by ariel-phet** [comment]
Excellent, closing

**Comment by jbphet** [comment]
I reviewed this yesterday with @ariel-phet, and we decided that the indicator should always show the amount that remains to be pumped into the container.  This avoids some potentially odd situations, such as where the user has blown the lid off the container and allowed one or two particles to escape before returning the lid, and the indicator is full be goes empty after pumping one or two particles.

**Comment by jbphet** [comment]
I made the changes described in the immediately preceding comment.  Looks good to me.  Back to @ariel-phet to try it out, make sure it's what we're after, and to close if so.

**Comment by ariel-phet** [comment]
Looks good, closing
