### ISSUE TITLE
the temperature can sometimes drop a bit when container is compressing

### ISSUE THREAD

**Issue by jbphet** [phetsims/states-of-matter#169]
When compressing the container, the model extracts its temperature from the kinetic energy of the particles.  Sometimes the temperature can go down as a result.  I believe that this is because the kinetic energy ends up being sampled at a time when some of the energy is being stored as potential energy between the particles, since their interaction is being modeled using Lennard-Jones potentials.  This is a little bit unphysical - the temperature should never really drop in this case.

**Comment by jbphet** [comment]
The Java sim has this same issue.  It is actually quite a bit more noticeable for that sim.

**Comment by jbphet** [comment]
I discussed this with @ariel-phet and we decided not to try to address this because:
+ it's not very noticeable
+ the Java sim had the same issue
+ the general temperature trend is upwards when the container is being compressed
+ it would be tricky to address, since we'd have to start tracking potential energy

**Comment by jbphet** [comment]
Actually, after a little thought, it might not be too hard to add some code to prevent this from happening that doesn't involve tracking the potential energy.  I could just say that the temperature is not allowed to decrease if the container is currently being compressed.

**Comment by phet-steele** [comment]
I certainly can't notice temperature decreasing, and I can't think why it should. Closing.
