### ISSUE TITLE
Update color of solid/liquid/gas buttons

### ISSUE THREAD

**Issue by arouinfar** [phetsims/states-of-matter#170]
I've worked with @amyh-phet to find some colors for the solid/liquid/gas buttons that look a bit less muddy than the ones currently in the sim (below).

![image](https://cloud.githubusercontent.com/assets/8419308/19535556/65f6372a-9605-11e6-8c31-20417597d0f7.png)

Here's a quick/rough mockup showing the new button colors. Please disregard the flat appearance.
![image](https://cloud.githubusercontent.com/assets/8419308/19535552/60f3873c-9605-11e6-92bc-38828865f9a7.png)

@jbphet please update the colors to
SELECTED_BUTTON_COLOR = #a5a7ff
DESELECTED_BUTTON_COLOR = #ffe098

**Comment by jbphet** [comment]
I made the update.  For the most part, they look pretty good, but the unselected color is pretty light so the highlight doesn't show up very much.  @arouinfar - please test off of the current master version and see what you think.  I tried darkening the color slightly, using F8D980, and thought it worked a little better.

**Comment by arouinfar** [comment]
@jbphet's suggestion of F8D980 does indeed look better. Back to you @jbphet.

**Comment by jbphet** [comment]
I updated the unselected color to the somewhat darker value mentioned above (#F8D980).  I accidentally committed this as part of a fix for another issue after demoing it to @arouinfar.  For reference, the commit is c5ab0bbc6739c67f32887a689d56851c0c35ee25.

**Comment by jbphet** [comment]
Fixed, closing.
