### ISSUE TITLE
consider speeding up particle motion

### ISSUE THREAD

**Issue by jbphet** [phetsims/states-of-matter#178]
@kathy-phet was in my office looking at this sim, and we had the Java version up at the same time.  She noticed that the particle motion is a little faster on the Java version.  I explained that this was a result of trying to get adequate performance on an iPad 2, i.e. I had slowed the motion down a little as part of a tradeoff towards optimizing performance.  She suggested that I investigate speeding the particles back up a bit once other optimizations for iPad 2 were complete.

**Comment by jbphet** [comment]
I tried speeding up the particles by about 25% versus the most recently dev version (http://www.colorado.edu/physics/phet/dev/html/states-of-matter/1.0.0-dev.13/states-of-matter_en.html).  It looks good on my machine, but not great on iPad 2.  @ariel-phet was looking at it with me and agreed to write up his thoughts, so I'm assigning this to him.

**Comment by ariel-phet** [comment]
On the iPad2 with the slightly faster speed there is a noticeable performance drop when the heat/cool bucket is applied. With the slightly slower speed, all visualizations still convey the learning goals, but there is not a noticeable performance change when applying the heat/cool control and all other animations of particle motions remain smooth through the range of temperatures. 

Closing.
