### ISSUE TITLE
Particle Blob freezing 

### ISSUE THREAD

**Issue by EthanWJohnson** [phetsims/states-of-matter#179]
Reproduced on: Chrome, Safari, Edge

Seen on: Windows 10, iPad, Mac

Using the adjustable attraction particle with a low number of total particles set to maximum attraction at about 120 degrees kelvin. At some point the blob will interact in a certain way with the sim that freezes the entire blob--as if , while a sole particle bounces up and down in a perfectly straight line.

After much careful watching (and recording), I managed to capture the incident occurring;
![particle slowdown](https://cloud.githubusercontent.com/assets/22551096/20199313/dc075134-a766-11e6-8a6e-a436d785b944.gif)

Sequence of events;
1.) Particle blob hits the wall and ejects a sole particle nearly straight up and down
2.) Particle blob bounces to the other wall
3.) Particle blob hits other wall and the velocity of each particle in it increases. AT THE SAME TIME, the velocity of the sole particle also increases
4.) Particle blob slows down. Sole particle stops moving side to side but continues to speed up slightly.
5.) Particle blob freezes as if at absolute zero. Sole particle bouncing perfectly up and down.

It seems like the sole particle is inheriting all the velocity/energy of the entire chamber, though how or why I have no idea.

Related to https://github.com/phetsims/tasks/issues/725

Debug Info;
Name: ‪States of Matter‬
URL: http://www.colorado.edu/physics/phet/dev/html/states-of-matter/1.0.0-dev.14/states-of-matter_en.html
Version: 1.0.0-dev.14 2016-11-09 20:12:59 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.71 Safari/537.36
Language: en-US
Window: 1366x648
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"845be6b5","branch":"master"},"axon":{"sha":"8353fe86","branch":"master"},"babel":{"sha":"1294f048","branch":"master"},"brand":{"sha":"880a18de","branch":"master"},"chipper":{"sha":"957db829","branch":"master"},"dot":{"sha":"2765eb4d","branch":"master"},"joist":{"sha":"3bb749cf","branch":"master"},"kite":{"sha":"48cb255e","branch":"master"},"nitroglycerin":{"sha":"b19c167e","branch":"master"},"phet-core":{"sha":"4222a05a","branch":"master"},"phetcommon":{"sha":"8df1bf7d","branch":"master"},"query-string-machine":{"sha":"13ba45df","branch":"master"},"scenery":{"sha":"fb9d77c5","branch":"master"},"scenery-phet":{"sha":"89cce959","branch":"master"},"sherpa":{"sha":"7a7b88b0","branch":"master"},"states-of-matter":{"sha":"d9863972","branch":"master"},"sun":{"sha":"2f551060","branch":"master"},"tandem":{"sha":"005c5582","branch":"master"}}

**Comment by EthanWJohnson** [comment]
Just a note regarding previous versions; the bug ALMOST seems to occur in prior versions. I have noted the blob's velocity to nearly reduce to zero after the sequence of events above plays out; however, the particle and the blob's horizontal movement never fully stopped, and so at some point they collided again. In three hours of letting the sim run, it never quite froze, but it got very close.

**Comment by jbphet** [comment]
This is due to a subtle interaction between the thermostat and falling particles.  The thermostat doesn't scale down Y velocities of falling particles so that they don't end up stuck in mid air when cooling down the system, but that can create a situation like this where all of the kinetic energy is essentially in one particle, and the others have virtually none.

I've added code that prevents the scaling of the X velocity in falling particles below a certain minimum value.  I think that will prevent the sim from getting into this situation for long periods of time.  It will still come up briefly, but because the particle with the energy will be moving in the x direction, it will eventually collide with the blob.

This change is available in http://www.colorado.edu/physics/phet/dev/html/states-of-matter/1.0.0-dev.15/states-of-matter_en.html.

**Comment by EthanWJohnson** [comment]
Fix above looks to be working;

![frozen single still occuring](https://cloud.githubusercontent.com/assets/22551096/20812065/74d86846-b7cd-11e6-8b65-e8161fef7b25.gif)

While the situation came up (very rapidly, in fact) the particle maintained a minimal X velocity and self corrected after about a minute. It can look a bit strange, but it will certainly self-correct and we could consider this fixed.
