### ISSUE TITLE
iPad2 - Interaction screen - Adjusting the graphical plot in Adjustable attraction mode

### ISSUE THREAD

**Issue by kmsravindra** [phetsims/states-of-matter#18]
on IPad2, its difficult to grab and adjust the graphical curve plot in Adjustable attraction mode.

**Comment by jbphet** [comment]
I've just tested this on the latest dev version (http://www.colorado.edu/physics/phet/dev/html/states-of-matter/1.0.0-dev.5/states-of-matter_en.html).  It's definitely a challenge to adjust the attraction curve from interacting with the arrow on the curve, but the issue doesn't seem to be the ability to grab the arrow, as the description above kind of implies.  It seems to me to be a performance issue - there is a huge lag from the time the curve or the sliders are adjusted until the change becomes visible.

**Comment by notsiddhartha** [comment]
There seem to be lots of Vector2 allocations per frame (in thousands) from the drawPotentialEnergyCurve call in InteractionPotentialDiagram. Particularly from Path.setShape call for potentialEnergyLine.

Re-writing InteractionPotentialDiagram using canvas should fix this on iPad2

**Comment by ChandrashekarBemagoni** [comment]
Fixed in above . Assigning to @kmsravindra for verification

**Comment by kmsravindra** [comment]
The performance is now decent on iPad2.
