### ISSUE TITLE
Particle blobs increase velocity at low temperatures

### ISSUE THREAD

**Issue by EthanWJohnson** [phetsims/states-of-matter#180]
At very low temperatures blobs of neon/water molecules (what I've seen thus far) will start out moving/vibrating slowly but, over several minutes, will move/vibrate much more quickly.

![low temperature water 1](https://cloud.githubusercontent.com/assets/22551096/20409415/b55477a4-acd6-11e6-8991-645036f13ab5.gif)

After mere moments the water blob will begin vibrating and moving faster and faster. After a few minutes, it will be moving like this;

![low temperature water 2](https://cloud.githubusercontent.com/assets/22551096/20410019/62a14152-acd8-11e6-9b25-92a598236ca7.gif)

They shouldn't be moving any faster if no net energy is being put into the system, I.E no user interaction. This behavior doesn't occur with oxygen or argon as far as I can tell; I've only gotten it to work with neon and water. 

For water at least, it isn't limited to near absolute zero; I've also gotten it to occur at up to 10 degrees kelvin. 

Note that changing the temperature at all will reset the molecules to their proper speed, often dramatically slowing them down in the process.

Related to: https://github.com/phetsims/tasks/issues/725

Debug Information:

Name: ‪States of Matter‬
URL: http://www.colorado.edu/physics/phet/dev/html/states-of-matter/1.0.0-dev.14/states-of-matter_en.html
Version: 1.0.0-dev.14 2016-11-09 20:12:59 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.71 Safari/537.36
Language: en-US
Window: 1366x648
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"845be6b5","branch":"master"},"axon":{"sha":"8353fe86","branch":"master"},"babel":{"sha":"1294f048","branch":"master"},"brand":{"sha":"880a18de","branch":"master"},"chipper":{"sha":"957db829","branch":"master"},"dot":{"sha":"2765eb4d","branch":"master"},"joist":{"sha":"3bb749cf","branch":"master"},"kite":{"sha":"48cb255e","branch":"master"},"nitroglycerin":{"sha":"b19c167e","branch":"master"},"phet-core":{"sha":"4222a05a","branch":"master"},"phetcommon":{"sha":"8df1bf7d","branch":"master"},"query-string-machine":{"sha":"13ba45df","branch":"master"},"scenery":{"sha":"fb9d77c5","branch":"master"},"scenery-phet":{"sha":"89cce959","branch":"master"},"sherpa":{"sha":"7a7b88b0","branch":"master"},"states-of-matter":{"sha":"d9863972","branch":"master"},"sun":{"sha":"2f551060","branch":"master"},"tandem":{"sha":"005c5582","branch":"master"}}

**Comment by kathy-phet** [comment]
This is also in the Java sim.

**Comment by jbphet** [comment]
I fixed this by switching to the isokinetic thermostat at low temperatures.  The change is available in http://www.colorado.edu/physics/phet/dev/html/states-of-matter/1.0.0-dev.15/states-of-matter_en.html.

**Comment by EthanWJohnson** [comment]
This looks fine now--I've left the sim running at very low temperatures and movement is very consistent. Closing.
