### ISSUE TITLE
With multiple particle blobs at absolute zero, only one gets heated

### ISSUE THREAD

**Issue by EthanWJohnson** [phetsims/states-of-matter#181]
While this was caught a while ago, evidently it was never formerly recorded here in the issues.

When there are multiple blobs of particles in _relatively_ close proximity to each other frozen at absolute zero, applying heat will only apply the heat to one of the blobs, never both.
![temperature increase with multiple blobs](https://cloud.githubusercontent.com/assets/22551096/20449402/57c595b6-ada6-11e6-94fa-7270d0067592.gif)

Can't determine when it will choose one blob over another; seems to be random. In any case, one will heat up and start moving appropriately while the other stays still as if at absolute zero. 

Related to: https://github.com/phetsims/tasks/issues/725

Debug Information:
Name: ‪States of Matter‬
URL: http://www.colorado.edu/physics/phet/dev/html/states-of-matter/1.0.0-dev.14/states-of-matter_en.html?
Version: 1.0.0-dev.14 2016-11-09 20:12:59 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.71 Safari/537.36
Language: en-US
Window: 1366x648
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"845be6b5","branch":"master"},"axon":{"sha":"8353fe86","branch":"master"},"babel":{"sha":"1294f048","branch":"master"},"brand":{"sha":"880a18de","branch":"master"},"chipper":{"sha":"957db829","branch":"master"},"dot":{"sha":"2765eb4d","branch":"master"},"joist":{"sha":"3bb749cf","branch":"master"},"kite":{"sha":"48cb255e","branch":"master"},"nitroglycerin":{"sha":"b19c167e","branch":"master"},"phet-core":{"sha":"4222a05a","branch":"master"},"phetcommon":{"sha":"8df1bf7d","branch":"master"},"query-string-machine":{"sha":"13ba45df","branch":"master"},"scenery":{"sha":"fb9d77c5","branch":"master"},"scenery-phet":{"sha":"89cce959","branch":"master"},"sherpa":{"sha":"7a7b88b0","branch":"master"},"states-of-matter":{"sha":"d9863972","branch":"master"},"sun":{"sha":"2f551060","branch":"master"},"tandem":{"sha":"005c5582","branch":"master"}}

**Comment by jbphet** [comment]
I've done some investigation, and I think I know what's happening here.  The isokinetic thermostat calculates a scaling factor when changing the temperature and applies it to the kinetic energy values of all particles.  If there is a group where all of the particles have essentially zero kinetic energy, the scaling factor won't change anything.

A potential solution would be to have a small random amount of kinetic energy that is added to particles below a certain threshold when heating up past the min temperature.  I'll experiment with that.

**Comment by jbphet** [comment]
I've added code that gives each particle a minimum amount of kinetic energy when the particles transition from absolute zero to above absolute zero.  This is available in http://www.colorado.edu/physics/phet/dev/html/states-of-matter/1.0.0-dev.15/states-of-matter_en.html.

**Comment by EthanWJohnson** [comment]
This looks good--when moving out of absolute zero, all blobs and particles are heating up and moving across the board.
