### ISSUE TITLE
Oxygen Oxygen not escaping when one atom pushed above binding energy

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/states-of-matter#184]
From Carl (back in 2012 on unfuddle)

> I have been playing with the chem sims.  I noticed that on the atomic interactions one, with O on O, if you drag the one O in so it is on the steeply rising potentional energy edge, above the binding energy, when released it stays bound in the well, rather than escaping.  All the other sets of molecules go flying out like they should.  I will probably offer some other comments on sims, but just wanted to flag this bug.
> 
> cheers,
> Carl

@jbphet this bug has apparently been around for 4 years....however if it is something reasonably easy to address might be nice to fix with our publication of SOM

**Comment by jbphet** [comment]
I've changed this to detect when the atom is released in the area of the potential that is greater than zero.  @ariel-phet - please test on the master branch and close if this looks like what we're after.

**Comment by ariel-phet** [comment]
I think so....looks good to me! Closing
