### ISSUE TITLE
Color Blind testing good except for Phase Diagram

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/states-of-matter#185]
I looked over the sim using the new Chrome extension I found, all look pretty good, except for the phase diagram assuming Protanopia. It looks like the solid and liquid color could have a bit more contrast.

![som protanopia](https://cloud.githubusercontent.com/assets/4051174/20779737/ad533812-b733-11e6-9afb-c11aa5a656d2.PNG)

**Comment by jbphet** [comment]
I tried a darker shade of purple for the background of the "solid" region in the graph, and it looks more distinct.  Here's a screen shot.

![som-color-blind](https://cloud.githubusercontent.com/assets/3082831/20984627/56e47edc-bc7e-11e6-886d-34c2c715f632.PNG)

@ariel-phet - please test off of master and close if this looks good to you.

**Comment by ariel-phet** [comment]
Looks good, thanks!
