### ISSUE TITLE
Ice-10 (Frozen, high density water at high temperatures)

### ISSUE THREAD

**Issue by EthanWJohnson** [phetsims/states-of-matter#187]
Under a certain set of conditions, water will condense into a very dense, orderly, high temperature yet completely stationary "ice" phase, by exploding and then cooling water. Upon reaching this phase, Ice-10 will kill sim performance (frames and input times measured in seconds), render heating and cooling completely nonfunctional, and will continuously increase sim memory usage.

Steps to Reproduce;
1.) Add the maximum number of water molecules possible to the container

2.) Compress the water until it BARELY explodes

3.) Once it explodes, quickly return the lid after a few--but not too many--water molecules have escaped the container. Less than 10 escapees is preferable, though Ice-10 will still form if more are lost, it just takes longer. There is a definitive threshold for when it will or won't form, but we can't find it.

4.) Cool the container to between 300 and 400 degrees kelvin.

If done correctly, Ice-10 will precipitate on the bottom of the container and rapidly freeze into its highly ordered form. 
![second ice-10](https://cloud.githubusercontent.com/assets/22551096/20854128/7dc5246c-b8ae-11e6-8634-f9d621ef2f70.gif)
~Formation Process of Ice-10

Through rigorous scientific testing, the properties of Ice-10 have been determined;

-Ice-10, once fully crystallized (stationary), is completely resistant to all temperature changes. No amount of heating or cooling will affect Ice-10

-Ice-10 will rapidly convert water molecules into more Ice-10, assimilating it into its form very quickly. Adding more water molecules to the container will not affect it for long.

-Once Ice-10 has begun to form, its formation process cannot be stopped; the water molecules will progress towards Ice-10's highly dense, organized structure. No amount of heating or cooling can disrupt the formation process.

-Once it has fully crystallized and frozen, simulation performance will bottom out; frames and inputs occur over seconds rather than milliseconds, and the sim becomes incredibly choppy and unresponsive. In addition, memory usage will continue to climb, beginning at around 30 MB and progressing to over 150 MB over the course of 15 minutes.

I have no idea what causes this; weird interactions between weird things. It is easiest to reproduce by exploding the container but @phet-steele managed to get it to form without exploding the container--once. It's a new state of water, hidden in the atomic interactions!

Related to https://github.com/phetsims/tasks/issues/746

Debug Info;
Name: ‪States of Matter‬
URL: http://www.colorado.edu/physics/phet/dev/html/states-of-matter/1.0.0-dev.15/states-of-matter_en.html
Version: 1.0.0-dev.15 2016-11-30 21:11:25 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.99 Safari/537.36
Language: en-US
Window: 1366x648
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"47c12d19","branch":"master"},"axon":{"sha":"835a8b04","branch":"master"},"babel":{"sha":"538e7084","branch":"master"},"brand":{"sha":"6d85e08a","branch":"master"},"chipper":{"sha":"f57edeb4","branch":"master"},"dot":{"sha":"2765eb4d","branch":"master"},"joist":{"sha":"6430512a","branch":"master"},"kite":{"sha":"48cb255e","branch":"master"},"nitroglycerin":{"sha":"b19c167e","branch":"master"},"phet-core":{"sha":"9e9fe9de","branch":"master"},"phetcommon":{"sha":"16feff3e","branch":"master"},"query-string-machine":{"sha":"24ad72ef","branch":"master"},"scenery":{"sha":"1bf0a92e","branch":"master"},"scenery-phet":{"sha":"a3ccf91d","branch":"master"},"sherpa":{"sha":"c2e033b0","branch":"master"},"states-of-matter":{"sha":"87fba600","branch":"master"},"sun":{"sha":"0810acad","branch":"master"},"tandem":{"sha":"f37e6d7c","branch":"master"}}

**Comment by jbphet** [comment]
This was due to a bug in the algorithm that places particles back in the container after an explosion followed by a return of the lid.  This algorithm was setting the X value of the position vector to a vector rather than a value, which was then causing the value to be converted to a string when a `+=` operation was done on it, and then subsequent `+=` operations were causing the strings to grow continuously.  That's why them memory usage was climbing.  For some reason, the string values caused the temperature calculation to be quite high, so the thermostat was always scaling the velocity and rotation down on the particles down, which is what caused the ice-like state.  This should now be fixed.  Assigning to @phet-steele so that he or @EthanWJohnson can verify that this is fixed on master.

**Comment by EthanWJohnson** [comment]
I'm not able to form Ice-10 on the master version--above commit appears to have fixed it.

**Comment by phet-steele** [comment]
Fixed in the rc 👍
