### ISSUE TITLE
?stringTest=%20 causes alignment failures and errors

### ISSUE THREAD

**Issue by phet-steele** [phetsims/states-of-matter#199]
`?stringTest=%20` is not a supported test, so this probably does not need to be addressed for 1.0. That being said, I've never seen a sim break from this test until now. I guess I'll leave it up to @jbphet to look into this if he wants to. Maybe this is indicative of a deeper problem?

3rd screen, alignment is way off:
<img width="1918" alt="screen shot 2016-12-14 at 2 31 19 pm" src="https://cloud.githubusercontent.com/assets/5863899/21201945/1ac266c6-c20a-11e6-84bb-d7baacb12992.png">

2nd screen, alignment is even worse. Sim errors out and locks up:
<img width="1340" alt="screen shot 2016-12-14 at 2 32 29 pm" src="https://cloud.githubusercontent.com/assets/5863899/21201980/3231f434-c20a-11e6-9b1c-ebb6711adb2a.png">

18 similar errors on the 2nd screen, here is just one
```
Error: <rect> attribute width: Expected length, "NaN".
updateSVGSelf @ states-of-matter_en.html?stringTest= :880
updateSVG @ states-of-matter_en.html?stringTest= :879
update @ states-of-matter_en.html?stringTest= :879
update @ states-of-matter_en.html?stringTest= :882
update @ states-of-matter_en.html?stringTest= :883
update @ states-of-matter_en.html?stringTest= :882
update @ states-of-matter_en.html?stringTest= :883
updateDisplay @ states-of-matter_en.html?stringTest= :885
stepSimulation @ states-of-matter_en.html?stringTest= :902
runAnimationLoop @ states-of-matter_en.html?stringTest= :902
```

Seen on all macOS 10.12.2 browsers, for phetsims/tasks#753.
URL: http://www.colorado.edu/physics/phet/dev/html/states-of-matter/1.0.0-rc.1/states-of-matter_en.html?stringTest=%20
Version: 1.0.0-rc.1 2016-12-13 17:17:22 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.95 Safari/537.36
Language: en-US
Window: 1920x1001
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 32 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 80)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"1ea1df65","branch":"HEAD"},"axon":{"sha":"1fba32ce","branch":"HEAD"},"babel":{"sha":"893c10ee","branch":"master"},"brand":{"sha":"41d9b92a","branch":"HEAD"},"chipper":{"sha":"ce490c62","branch":"HEAD"},"dot":{"sha":"a014950f","branch":"HEAD"},"joist":{"sha":"173fdd07","branch":"HEAD"},"kite":{"sha":"e5affc4c","branch":"HEAD"},"nitroglycerin":{"sha":"bb4cf015","branch":"HEAD"},"phet-core":{"sha":"87b5cab3","branch":"HEAD"},"phetcommon":{"sha":"afb66c63","branch":"HEAD"},"query-string-machine":{"sha":"b38c3c25","branch":"HEAD"},"scenery":{"sha":"5d0c2b1e","branch":"HEAD"},"scenery-phet":{"sha":"fdf8f08e","branch":"HEAD"},"sherpa":{"sha":"727a3136","branch":"HEAD"},"states-of-matter":{"sha":"f69fb7c1","branch":"HEAD"},"sun":{"sha":"e86f9f50","branch":"HEAD"},"tandem":{"sha":"b83eb2e2","branch":"HEAD"}}

**Comment by phet-steele** [comment]
Pretty sure this is the EXACT same issue as https://github.com/phetsims/atomic-interactions/issues/58. (the above screenshots and errors happen the same with `?stringTest=xss`). I could be proactive and give this issue the same treatment as the linked issue, but I'll still let @jbphet decide.

**Comment by jbphet** [comment]
I have investigated this and it looks like the bulk of the issues result from code that lays out graphs and panels based in part on the bounds of text nodes.  When there are no visible characters in the text node, it is considered to have no bounds, so failures result.  If the developer tools are open, errors and assertions are encountered.

I recommended closing this as "will not fix".  Assigning to @ariel-phet to make sure that he agrees, if so, he can label and close.

**Comment by ariel-phet** [comment]
@jbphet agreed, closing

**Comment by jbphet** [comment]
While working on some other portions of the sim, I discovered that the main culprit that was causing the layout issues was a small text label with its bounds set to 'accurate'.  I ended up logging an issue about this - see https://github.com/phetsims/scenery/issues/595 - and adding a workaround.  This radically improved the results of this test.
