### ISSUE TITLE
Atom diameter slider doesn't reach minimum

### ISSUE THREAD

**Issue by phet-steele** [phetsims/states-of-matter#20]
In the interaction screen with adjustable attraction selected, the slider to change atom diameter does not reach the minimum allowable diameter in the sim. In other words, after dragging the slider all the way to the left to make the atom smaller, the user can then use the arrows on the graph that go left and right to make the atom even smaller (by moving the graph left).

Video:
https://drive.google.com/file/d/0B3HJopSo_QqLRXdjSTZrTHpmX1U/view?usp=sharing

Tested on Win 8.1 browsers in 1.0.0-dev.2
Troubleshooting information:
Name: States of Matter
URL: http://www.colorado.edu/physics/phet/dev/html/states-of-matter/1.0.0-dev.2/states-of-matter_en.html
Version: 1.0.0-dev.2
Features missing: touch
User Agent: Mozilla/5.0 (Windows NT 6.3; WOW64; rv:35.0) Gecko/20100101 Firefox/35.0
Language: en-US
Window: 1366x633
Pixel Ratio: 1/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0
Vendor: Mozilla (Mozilla)
Vertex: attribs: 16 varying: 10 uniform: 254
Texture: size: 16384 imageUnits: 16 (vertex: 4, combined: 20)
Max viewport: 16384x16384
OES_texture_float: true

**Comment by jbphet** [comment]
Something's a bit odd with this.  I can duplicate it on the 1.0.0-dev.2 version that is posted to the development server, but I can't duplicate it on master.  None of the commits that have been made since this version was posted would appear to address the issue, some I'm not sure what is up.  I'll assign this to myself to follow up once the next dev version is out.

**Comment by ChandrashekarBemagoni** [comment]
https://github.com/phetsims/atomic-interactions/commit/0234c7f2ba472fe2e6d89c7b1fb73c20e486ac38
Fixed in the above commit.

**Comment by ChandrashekarBemagoni** [comment]
Assigning to @jbphet  for verification.

**Comment by jbphet** [comment]
Tested on http://www.colorado.edu/physics/phet/dev/html/states-of-matter/1.0.0-dev.4/states-of-matter_en.html and the issue appears to be fixed.  Closing.
