### ISSUE TITLE
Chromebook overlap on Phase Changes screen

### ISSUE THREAD

**Issue by phet-steele** [phetsims/states-of-matter#201]
The Phase Changes screen on Chromebook gets a little crowded towards the bottom. @ariel-phet @jbphet is there a way to free up the overlap slightly? (The Reset All button and Phase Diagram panel are overlapping by a few pizels)

![states of matter screenshot 1](https://cloud.githubusercontent.com/assets/5863899/21202649/777f87b6-c20c-11e6-9f2c-7b5d5c374ecc.png)

Seen on Peppy.4389.93.0, for phetsims/tasks#753

**Comment by ariel-phet** [comment]
@jbphet feel free to remove a pixel or so between the control panels and move the reset all button down a pixel or two to remove the overlap. If needed, the reset all button could be reduced slightly in size (5%) with a dilated touch area.

Feel free to use any combination of space/size adjustment that you feel works best.

**Comment by jbphet** [comment]
I moved it down two pixels, it now looks like this:

![som-moved-reset-button](https://cloud.githubusercontent.com/assets/3082831/21242309/ef7f916a-c2d0-11e6-8b95-d9939606957f.png)

**Comment by phet-steele** [comment]
👍 1.0.0-rc.2 is great.
