### ISSUE TITLE
Performance on Edge is fairly abysmal 

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/states-of-matter#204]
Testing on Win 10 and Edge, I saw 5 fps with water in the gaseous phase.

The performance is definitely below our normal standards, but fortunately edge is an extremely low percentage of our user base.

At some point, we should investigate what is bogging down so badly, but we will not let this issue delay publication of the sim (compromises must be made at times).

**Comment by EthanWJohnson** [comment]
I'm not seeing quite the same performance hit on either of my windows 10 systems, but the sim is using a ridiculous amount of CPU compared to Firefox and Chrome. It sits around 50% CPU usage with spikes up to 60%, whereas Firefox and Chrome generally hover around 20-25% usage.

**Comment by pixelzoom** [comment]
In Graphing Quadratics, I was able to increase Edge performance significantly by avoiding `removeChild` and mutating Nodes where possible.  Apparently Edge is more sensitive to scenegraph changes.

**Comment by jbphet** [comment]
@KatieWoe - This issue is several years old, and I believe Edge has been significantly updated since then.  Can you have the QA team re-test and, if performance is decent, close?

**Comment by KatieWoe** [comment]
Looks good in published sim. We also don't really support Edge, so I think this can be closed.
