### ISSUE TITLE
fails stringTest in Options dialog

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/states-of-matter#206]
Noted in published and master versions of SOM and SOM:Basics.

With `?stringTest=xss`, it's apparent that the Options dialog's content has no `maxWidth`.

If doing a maintenance release, you need to pickup the fix for the "Options" title in phetsims/joist#416.

**Comment by jbphet** [comment]
I've added a `maxWidth` option for the dialog.  I looked at a number of the translations that are currently live on the site, and none seem to have any issues with the width of this dialog, so I don't think a maintenance release is warranted.  I think this is addressed, so I'll close it, @pixelzoom please reopen if there is more that needs to be done.

**Comment by pixelzoom** [comment]
@jbphet It looks like you added a maxWidth for the entire dialog contents.  That will cause the entire contents to shrink if only one text label is long.   In all sims that I've worked on, it has been requested to set maxWidth on the individual labels, not on the entire contents.

**Comment by pixelzoom** [comment]
For example, see how @jonathanolson addressed this same issue in https://github.com/phetsims/molecule-shapes/issues/148, commit https://github.com/phetsims/molecule-shapes/commit/3116679d13f7dd36206dd0111a2f609d4514a394.  This is the correct way to apply `maxWidth`.

**Comment by jbphet** [comment]
How does that look?
