### ISSUE TITLE
User question: system temperature, pump position

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/states-of-matter#207]
> As a long-time fan of the “States of Matter” sim, I was happy to see an HTML5 version.  However, after using it, some things about the HTML5 version don’t make sense to me.
>  
> In the Java version, the gas entering the canister had the same temperature as the system.  So if I had water molecules sitting in ice formation at 75K, I could add more water molecules through the ‘pump’ and show how they almost immediately freeze, thus limiting the vapor pressure.  Increase the temperature, repeat the experiment, and it is obvious that the vapor pressure increases along with it.  At higher temperatures with liquid present, the students can add water vapor at different temperatures to see the effect that temperature has on the vapor pressure.
>  
> In the HTML5 version though, for reasons I can’t figure out, adding additional water molecules dramatically increases the temperature of the system.  So now if I repeat the same experiment as above – have some water molecules at 75K for example, and add some more vapor, immediately everything melts.  There might be a physical basis for this as I am sure that adding more molecules to the system does increase the temperature slightly, but the changes seem unrealistic to me.  For example, start out with the default water ice at 157K.  Now lift the handle and add one single ‘pump’ - which looks like it spits out only three molecules - and immediately the system jumps to 360K!  Is this physically realistic??  I don’t know enough about microphysics to speak about this with certainty, but I wish there was a way to turn this effect OFF (in other words – make it behave like the java version does).
>  
> My other gripe is that when doing said demonstration, it is helpful to have the inlet of the pump be near the top of the can (again like the Java version).  This way, when the students add a ‘pump’ of water vapor, it enters the top of the canister, and then they can see how the vapor molecules interact with the ice or liquid.  With the HTML5 version, the new gas enters from near the bottom, which is at the same level of the ice or liquid.  In my opinion that muddles the interaction that I want them to see.  Could the entry point for the pump be movable by the user?

**Comment by jbphet** [comment]
Assigned to @ariel-phet to decide whether to figure out whether to take this on.  Tagging @arouinfar since I know these changes were discussed at design meetings and she might have some input.

**Comment by ariel-phet** [comment]
@oliver-phet can you forward me the original email so I can respond directly to the user?

**Comment by oliver-phet** [comment]
Original email forwarded.

**Comment by ariel-phet** [comment]
Responded to user with the following:

> 
> Thanks for your feedback on our HTML5 States of Matter sim. A few responses to your concerns:
> 
> 1. When you pump water molecules in and the temperature rises significantly does appear to be buggy behavior. We will be investigating and hopefully identifying a fix. Due to priorities, it will be a several weeks before we investigate, but thanks for pointing out this behavior, as it does not seem to match the other substances, and appears to be incorrect.
> 
> 2. We see where having the inlet for the pump higher on the container would have certain benefits, however, since you can compress the lid, we placed the pump inlet low on the container to maximize the range the lid could be compressed while still allowing additional atoms/molecules. We feel this position allows more flexibility with the interaction, but we understand the trade-off of not having atoms/molecules float in from the top.
> 
> 3. The Java version had some issues we were trying to rectify. For instance, if at "absolute zero" you pumped atoms/molecules into the container (which had obvious kinetic energy) the temperature indicated would not rise, which was strictly incorrect. The model for this sim is quite "tweaky" so it looks like we got things generally fixed, but there are still some issues with water. As mentioned in (1) we will be looking into that, and we very much appreciate you pointing it out!

**Comment by ariel-phet** [comment]
Closing this issue, and will be opening a separate issue for the behavior of water when molecules are pumped in.
