### ISSUE TITLE
Icons look bad on FF and IE

### ISSUE THREAD

**Issue by phet-steele** [phetsims/states-of-matter#21]
Image scaling, especially on the screen images, is bad in FF and IE. FF/Chrome comparison:

FF
![ffstates](https://cloud.githubusercontent.com/assets/5863899/5982299/e4cb14ce-a87e-11e4-9b16-648e21f9d605.png)

Chrome
![chromestates](https://cloud.githubusercontent.com/assets/5863899/5982308/f6b04876-a87e-11e4-862e-f3ea27ca6c09.png)

Troubleshooting information:
Name: States of Matter
URL: http://www.colorado.edu/physics/phet/dev/html/states-of-matter/1.0.0-dev.2/states-of-matter_en.html
Version: 1.0.0-dev.2
Features missing: touch
User Agent: Mozilla/5.0 (Windows NT 6.3; WOW64; rv:35.0) Gecko/20100101 Firefox/35.0
Language: en-US
Window: 1366x633
Pixel Ratio: 1/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0
Vendor: Mozilla (Mozilla)
Vertex: attribs: 16 varying: 10 uniform: 254
Texture: size: 16384 imageUnits: 16 (vertex: 4, combined: 20)
Max viewport: 16384x16384
OES_texture_float: true

**Comment by pixelzoom** [comment]
The screen images are currently huge, 4267x2792.  They should be scaled down for the home screen. And if you want the navbar icons to look better in Firefox, create navbar-specific images at 147x100.

**Comment by jbphet** [comment]
These icons are basically just screen shots, and no icons are currently depicted in the design doc.  Assigning to @ariel-phet to get manage the design and creation of icons that will work better.

**Comment by ariel-phet** [comment]
@arouinfar you and I should work on some icons for SOM

**Comment by jbphet** [comment]
I've integrated a new set of icons provided by @arouinfar.  For the most part, I think they look pretty good.  The only issue is that the phase changes icon is hard to interpret on the nav bar (in my opinion).  Assigning to @arouinfar to take a look and decide whether to modify this icon or to supply a different version for the nav bar.  @arouinfar - if you feel it is acceptable as is, please go ahead and close this issue.

**Comment by arouinfar** [comment]
Closing this issue and moving future discussion of icons to #69.
