### ISSUE TITLE
incorporate support for Legends of Learning

### ISSUE THREAD

**Issue by jbphet** [phetsims/states-of-matter#210]
I reported in a recent status meeting that I'm spending some time working on https://github.com/phetsims/states-of-matter/issues/208.  @kathy-phet has requested that as I work on this I should also add support for LoL.  Here is the email dialog:

> (@kathy-phet): As you work to fix States of Matter, please also add legends of learning capabilities to this sim. The various versions will fit nicely into their categories and help us start to earn revenue from them, and if we are republishing/testing we should go ahead and add this capability.

> (@jbphet): Sounds good, will do.  Is @samreid the person to talk to in order to make sure I'm clear as to what exactly this entails?

> (@ariel-phet): Yes, @samreid would be good to talk to, but I believe as long as the sim is built off master these days, it comes with LoL features (@phet-steele might also know). So it might be as simple as bringing the sim up to current SHAs, but don't quote me on that. LoL testing comes standard as part of QA for new sims.

> (@jbphet): I'm okay with building off of master, but it would mean a more intensive round of QA is required.  Are we cool with that?

> (@ariel-phet): Yes, I am cool with that. Although that might mean that actually deploying the sim happens after we have chipper worked out.

**Comment by jbphet** [comment]
@samreid - can you confirm that building off of master will incorporate LoL support?

**Comment by samreid** [comment]
Joist/master of LegendsOfLearningSupport.js and its usages are intended to support Legends of Learning and hopefully sufficient.  However, the simulation developer also needs to make sure that nothing in the simulation happens outside of the step(dt) function.  For example, some of our older sims use window.setTimeout or window.setInterval--those will not be able to pause correctly.  Also there is a caveat that our Legends of Learning support is in its infancy, so we require a testing phase for it during QA time and we need to be prepared for new problems that come up.

**Comment by jbphet** [comment]
Thanks @samreid.  Is there a good way for me as a developer to check that the functionality works once I've taken the steps you outlined, or is it best to build a dev version and have QA check it?

**Comment by samreid** [comment]
From @jessegreenberg note on slack:

> It does, to see features you can add query param ?legendsOfLearning, and put sim url in "Game URL" field in http://harness.legendsoflearning.com/

Basically test that pause works, pause in 5 seconds works, try dragging things when you pause in 5 seconds, etc.  Try dragging things outside the iframe, etc.

**Comment by jbphet** [comment]
I tested today using the test harness URL provided above and used localhost links from master for the sims.  I tested all 3 sim variations, and all loaded, and the "Pause" function worked.  I didn't see any control that said "Pause in 5 Seconds", so I don't know if this has gone away or if it's a bit of a hidden option and I don't know how to find it.  At any rate, since the pause functionality worked, I'm going to mark this as fixed and will get QA to test it as part of the deployment process.

For the record, I tested this using the following URLs for the "Enter Game Source URL" field in the Legends of Learning test harness:
+ http://localhost:8080/states-of-matter/states-of-matte_en.html?brand=phet&ea&legendsOfLearning
+ http://localhost:8080/states-of-matter-basics/states-of-matter-basics_en.html?brand=phet&ea&legendsOfLearning
+ http://localhost:8080/atomic-interactions/atomic-interactions_en.html?brand=phet&ea&legendsOfLearning

**Comment by KatieWoe** [comment]
@jbphet do you want this issue closed?

**Comment by jbphet** [comment]
@KatieWoe - please note if it's been verified to work and, if so, on what release, and then clear the "fixed-pending-testing" label but leave it open.  I'll make a pass through after deployment and close everything that we leave in the "fixed-pending-deployment" state.

**Comment by jbphet** [comment]
Published in v1.1.0.  @samreid - does anyone need to be notified of this?  If not, feel free to close.

**Comment by samreid** [comment]
@arouinfar may be a good contact for LOL, reassigning.

**Comment by arouinfar** [comment]
@jbphet just wanted to check in on this issue. SOM added LoL support in the 1.1 branch, but the latest SOMB is still on 1.0, so it doesn't have LoL support yet, correct?

**Comment by jbphet** [comment]
Yes, that's correct.  A while back it was decided that redeploying SOMB wasn't a priority at the time, and we haven't revisited it since then.  If it's important to get out it, please let @kathy-phet and @ariel-phet know, and we'll get 'er done.

**Comment by arouinfar** [comment]
Thanks @jbphet. I was just doing a bit of GitHub hygiene and noticed the latest version of SOMB was dated a week or so after my last comment, so I wanted to be sure that that wasn't the version that was supposed to be delivered.

**Comment by jbphet** [comment]
@arouinfar - no, the version that is currently live, which is v1.0.7, built on Nov 6 2018, does not include LoL support.  The date reflects a maintenance release that was done to fix issues with full screen behavior on iOS devices.

**Comment by jbphet** [comment]
A separate issue has now been created for publishing States of Matter Basics with LoL support, please see https://github.com/phetsims/states-of-matter-basics/issues/19.  Closing this one.
