### ISSUE TITLE
Create LoL Icons and Descriptions

### ISSUE THREAD

**Issue by arouinfar** [phetsims/states-of-matter#211]
Support for LoL is being added in #210 so we will also need icons and descriptions.

**Comment by arouinfar** [comment]
@ariel-phet @kathy-phet or @jbphet can you confirm that we are delivering only SOM -- not SOMB? 

I think SOMB would be redundant here, since the first screen is exactly identical to SOM and the 2nd screen is very similar. The primary difference on the 2nd screen is that SOMB does not include the  adjustable interaction option and thus does not have the interaction potential (which could always be minimized).

**Comment by ariel-phet** [comment]
I am bit out of the LoL loop, but I would think only SOM is logical given your points above.

**Comment by jbphet** [comment]
I have no idea.  I'm adding @samreid to the list of assignees, since he is more likely to know than I.

**Comment by jbphet** [comment]
As I think about it, I will be working to add changes to the temperature behavior for SOM in #208, and that change may go out with the release that supports LoL.  If this is done, then SOMB will also need to be republished, otherwise the two sims will have slightly different behaviors.  I think we should just plan on doing SOMB too.

**Comment by kathy-phet** [comment]
@arouinfar - They are focused on 8th grade and lower right now, so I think SOMB might be the more appropriate of the two sims. I do agree that there is a lot of overlap, however, so its a bit complicated of a choice.

**Comment by arouinfar** [comment]
Sounds good @kathy-phet I will prepare icons and descriptions for SOMB. QA testing generally focuses on SOM (because SOMB is mostly redundant) so if for some reason we change our minds in the future, the live version of SOM would also be LoL-ready.

**Comment by arouinfar** [comment]
The icons and descriptions for SOMB are now on Drive.
