### ISSUE TITLE
User suggestion: toggle pressure units

### ISSUE THREAD

**Issue by arouinfar** [phetsims/states-of-matter#215]
In #214, a user requested support for pressure units of bar or mbar.

The thermometer readout is a combobox to toggle C/K.
![image](https://user-images.githubusercontent.com/8419308/38323853-b5794aaa-37fb-11e8-8368-e3b191d97c35.png)

We are planning to do something similar in Gas Properties, allowing users to toggle between atm and kPa.
![image](https://user-images.githubusercontent.com/8419308/38323922-ed70e2f6-37fb-11e8-9adf-7103c41dc6e4.png)

This seems like a reasonable request to me, but I would suggest that we would allow units of atm, kPa, and bar.

**Comment by jbphet** [comment]
This was discussed in the 8/2/2018 design meeting with @ariel-phet, @arouinfar, and @kathy-phet and it was decided to not add alternative pressure units since this is not truly meant to be a quantitative sim.  Closing.
