### ISSUE TITLE
Query parameter to start sim using Celsius

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/states-of-matter#216]
A collaborator requested that the sim start using Celsius rather than Kelvin. @jbphet thought this should be done using a query parameter. 

Waiting to confirm with collaborator before we start instrumenting this.

**Comment by oliver-phet** [comment]
> It would be ideal for him, if he know where he could define the code of standart (Celsius) for the correspondent Dropdown. As the sims will run for 10 to 15 years, he could change the standard every time he would have to update the version without contacting you again. 

@jbphet It sounds like it would be great if we could add a query parameter to allow the sim to start using Celsius.

**Comment by jbphet** [comment]
Added in https://github.com/phetsims/states-of-matter/commit/6c2a42cdd1af7528f44cc6caedc96c63d362e27b (forgot to reference this issue in the commit).

**Comment by jbphet** [comment]
I added the query parameter `defaultCelsius` for this feature, seems to work well.  The sim will return to Celsius is changed to Kelvin and then reset.

Leaving open and unassigned until tested and published.

**Do not close this issue** until the feature has been published and we have informed the user who requested the feature that it is now available.

**Comment by oliver-phet** [comment]
@jbphet Was there a issue created in QA to test this?

**Comment by jbphet** [comment]
There will be for the next RC.

**Comment by phet-steele** [comment]
Looks good in 1.1.0-rc.1 Win 10 Chrome. From the commit, I can't imagine this needing more testing on other platforms.

> **DO NOT CLOSE THIS ISSUE** until the feature has been published and we have informed the user who requested the feature that it is now available.

@jbphet let @oliver-phet know when this is out!

**Comment by jbphet** [comment]
Unassigning but leaving open so that we remember to tell the person who requested it when it's available.

**Comment by jbphet** [comment]
@oliver-phet - please tell the individual who requested this that it is now live.

**Comment by oliver-phet** [comment]
Email sent. Closing.

**Comment by KatieWoe** [comment]
This is also looking ok in SOMB 1.1.0-rc.2
