### ISSUE TITLE
migrate HandleNode to scenery-phet

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/states-of-matter#218]
Gas Properties design document identifies a handle that is used in multiple places. It looks like this:

![screenshot_705](https://user-images.githubusercontent.com/3046552/42838635-8fedaa78-89be-11e8-8d90-f9aa0dac878d.png)

I'm sort of surprised that this isn't already in common code, since I seem to recall other sims having this type of handle. 

`STATES_OF_MATTER/HandleNode` looks close, but would need to be refined (it's sort of crude looking) and generalized.  It looks like this:

![screenshot_707](https://user-images.githubusercontent.com/3046552/42900769-e906e48a-8a86-11e8-995d-048da67ef570.png)

Assigning to me, @jbphet and @ariel-phet to discuss.

**Comment by ariel-phet** [comment]
@pixelzoom is this something @andrealin could do, as she has done a fair bit of common code work now?

**Comment by pixelzoom** [comment]
yep.

**Comment by pixelzoom** [comment]
Yes. Although I suspect that she'll have her hands full with Graphing Quadratics.

**Comment by samreid** [comment]
I helped @chrisklus review HandleNode.js and everything is looking great.  The only outstanding question I had was whether to use flat options or nested options.  I asked on slack:

Did we decide we prefer flat options like this?
_.extend({
 componentAProperty1: ‘x’,
 componentAProperty2: ‘y’
})

or nested options like this:

_.extend({
 componentAOptions:{…}
});

and haven't heard back yet.  Still, the flat strategy seems clear and simple and matches our existing patterns, so I think we should start with that.  Back to you @chrisklus if there's anything else.  Close if we're all set.

**Comment by chrisklus** [comment]
@samreid thanks for reviewing with me, I think we're all set. Closing.

**Comment by pixelzoom** [comment]
I did reply on Slack, but looks like my reply didn't get sent (perhaps my internet connection went down). I said:

> See nested options on code review checklist. But imo, it depends on context - how many options, whether it's desirable to hide the identity of sub components, etc. If you want to be able to customize all options of a subcomponent, then definitely nested options.

Looking at HandleNode, I think that flat options are fine in that context.
