### ISSUE TITLE
Slight upward jump for neon and argon when cooled from solid state

### ISSUE THREAD

**Issue by jbphet** [phetsims/states-of-matter#219]
While working on the drift issues reported in https://github.com/phetsims/states-of-matter/issues/214 and https://github.com/phetsims/states-of-matter-basics/issues/15, I noticed that there is a noticeable initial jump exhibited by neon and argon when they are cooled from a solid state.  This is present in the currently published version too, which is v1.0.3, but seems to be a little more apparent in the master version after the changes that I made to prevent drift.

I dug into this a little bit, and it seems like the initial temperature is being set in such a way that the particles behave the way we want them too, but isn't quite correct, and so when the cooling starts, the particles end up essentially being warmed a little first, then cooled.  I wasn't able to come up with a quick fix after an hour or so of investigation and experimentation, so fixing it may be a bit involved.

@ariel-phet and @arouinfar - please check out the dev version linked below and let me know if you think this has to be addressed before the next release.  You should probably compare it to the currently live version to see if you think there is a noticeable and problematic difference.

https://phet-dev.colorado.edu/html/states-of-matter/1.1.0-dev.3/phet/states-of-matter_en_phet.html

**Comment by ariel-phet** [comment]
@jbphet yes, I can see what you are talking about. It does look a tad odd, but I am not overly concerned at this point. Things settle quickly enough that you have to be watching pretty carefully to decide it is odd. 

Since we know this behavior is in a sense incorrect, I am going to mark the issue as deferred. We can see if we get any complaints from the world over the next school year. 

Unassigning, marking deferred.

**Comment by jbphet** [comment]
I had a bit of a brainstorm about this while working on other aspects of the sim, and I have implemented some code that only runs the isokinetic thermostat if the calculated temperature of the substance needs to be changed in a specific direction (e.g. the particles need to be slowed down because the user is cooling them) instead of always running it when the temperature is changing.  This seems to solve the problem, and thus far I haven't seen any odd side effects.  I'll keep this open and will have QA take a look when we have a release candidate.

**Comment by KatieWoe** [comment]
Seems good.  Closing
