### ISSUE TITLE
FF heating/cooling bucket text is blurry when its slider is manipulated

### ISSUE THREAD

**Issue by phet-steele** [phetsims/states-of-matter#22]
Seen in Win 8.1, FF 35.0.1 with 1.0.0-dev.2

Video:
https://drive.google.com/file/d/0B3HJopSo_QqLSkVLbWxxRTZqNFU/view?usp=sharing

Troubleshooting information:
Name: States of Matter
URL: http://www.colorado.edu/physics/phet/dev/html/states-of-matter/1.0.0-dev.2/states-of-matter_en.html
Version: 1.0.0-dev.2
Features missing: touch
User Agent: Mozilla/5.0 (Windows NT 6.3; WOW64; rv:35.0) Gecko/20100101 Firefox/35.0
Language: en-US
Window: 1366x633
Pixel Ratio: 1/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0
Vendor: Mozilla (Mozilla)
Vertex: attribs: 16 varying: 10 uniform: 254
Texture: size: 16384 imageUnits: 16 (vertex: 4, combined: 20)
Max viewport: 16384x16384
OES_texture_float: true

**Comment by jbphet** [comment]
This is a Firefox only issue, and similar issues have been seen on other simulations.  This isn't a bug in the sim code, so I'll assign it to myself and talk with other developers to find out if there is any fix for this.  All in all, it seems pretty minor.

**Comment by jbphet** [comment]
Assigning to @jonathanolson to take a look.  As I recall, this is just something that Firefox does, and there isn't that much that can be done about it.  If that's the case, @jonathanolson should just close the issue.  If something *can* be done (with reasonable effort), please let us know.

**Comment by jonathanolson** [comment]
It's on my list of things Firefox does that I don't know how to work around so far. As requested above, closing.
