### ISSUE TITLE
Cooled solids drift to the side of the container

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/states-of-matter#220]
**Test device:**
Dell Laptop
**Operating System:**
Win 10
**Browser:**
Chrome
**Problem description:**
For phetsims/QA/issues/164 and related to phetsims/states-of-matter-basics/issues/15
Drifting of solids to one side of the container can still occur if the solid has been cooled down.
**Steps to reproduce:**
1. Go to the States screen
2. Choose an solid.  Water tends to occur the fastest
3. Use the bucket to lower the temperature to -257 C (the actual temperature is not very important, as long as it is cooled)
4. Wait from 1 to  minutes, depending on the solid chosen and the temperature.

**Screenshots:**
![drift](https://user-images.githubusercontent.com/41024075/43974421-c05e69fe-9c97-11e8-9edc-f2eed7a93194.PNG)
![drift2](https://user-images.githubusercontent.com/41024075/43974427-c479fac6-9c97-11e8-96a2-62c40294a520.PNG)

Troubleshooting information (do not edit):

<details>

Name: ‪States of Matter‬
URL: https://phet-dev.colorado.edu/html/states-of-matter/1.1.0-dev.3/phet/states-of-matter_en_phet.html
Version: 1.1.0-dev.3 2018-08-06 20:52:14 UTC
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.84 Safari/537.36
Language: en-US
Window: 1536x737
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"928741cf","branch":"master"},"axon":{"sha":"3feda95c","branch":"master"},"brand":{"sha":"89d28f63","branch":"master"},"chipper":{"sha":"cba50451","branch":"master"},"dot":{"sha":"49561319","branch":"master"},"joist":{"sha":"2ff274d4","branch":"master"},"kite":{"sha":"a43e7dd9","branch":"master"},"nitroglycerin":{"sha":"ccaab9cd","branch":"master"},"phet-core":{"sha":"9c242cdc","branch":"master"},"phet-io":{"sha":"a03fa3de","branch":"master"},"phet-io-wrapper-classroom-activity":{"sha":"f666b06e","branch":"master"},"phet-io-wrapper-hookes-law-energy":{"sha":"b3ca28bf","branch":"master"},"phet-io-wrapper-lab-book":{"sha":"4144509a","branch":"master"},"phet-io-wrappers":{"sha":"a5a4edc5","branch":"master"},"phetcommon":{"sha":"04bc12ce","branch":"master"},"query-string-machine":{"sha":"4178d27a","branch":"master"},"scenery":{"sha":"687654c7","branch":"master"},"scenery-phet":{"sha":"fd193b3a","branch":"master"},"sherpa":{"sha":"79fb5b8c","branch":"master"},"states-of-matter":{"sha":"8222bec7","branch":"master"},"sun":{"sha":"cd84de33","branch":"master"},"tambo":{"sha":"2aac9c19","branch":"master"},"tandem":{"sha":"66d0f519","branch":"master"}}

</details>

**Comment by jbphet** [comment]
I've added zeroing out of collective velocity for all solids when the phase is set.  This improves the behavior, but there is still some drift over long time periods.  In my opinion, the level is now acceptable, since people are unlike to have the sim just sit there for ten minutes.

@KatieWoe - please test this on master and, if it strikes you as acceptable, mark as "fixed pending deployment".  If you think this deserves more discussion, assign to @ariel-phet and @arouinfar for their input.

**Comment by KatieWoe** [comment]
@jbphet it does seem better.  I did notice that when on water as a solid some of the particle movement looked less smooth than usual, so that might be something to keep an eye on.

**Comment by KatieWoe** [comment]
Looks Good.  Closing

**Comment by jbphet** [comment]
Deployed in v1.1.0, closing.
