### ISSUE TITLE
Solid will begin to deform if left to sit

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/states-of-matter#221]
**Test device:**
Dell Laptop
**Operating System:**
Win 10
**Browser:**
Chrome
**Problem description:**
For phetsims/QA/issues/164
Solid will begin to deform if left to sit for some amount of time.  That amount of time depends on the solid chosen.  @jbphet is aware of this and finds it an acceptable compromise, but wanted an issue made to confirm this.
**Steps to reproduce:**
1. Go to the States screen
2. Leave the sim running with one of the solids, such as Neon.  One minute is usually enough, but it becomes more noticeable the more time passes.
3. To compare to the published sim: This deformation does not occur until the solid has fully drifted to one side or the other.  Once it reaches a wall it will start to deform.

**Screenshots:**
Dev Version:

![deformdev](https://user-images.githubusercontent.com/41024075/43975935-72536cb4-9c9c-11e8-860a-349044fbdeed.gif)

Published Version:

![deformpub](https://user-images.githubusercontent.com/41024075/43975960-7ffe309c-9c9c-11e8-8d8d-fa75b96a75aa.gif)

**Troubleshooting information (do not edit):**

<details>

Name: ‪States of Matter‬
URL: https://phet-dev.colorado.edu/html/states-of-matter/1.1.0-dev.3/phet/states-of-matter_en_phet.html
Version: 1.1.0-dev.3 2018-08-06 20:52:14 UTC
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.84 Safari/537.36
Language: en-US
Window: 1536x737
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"928741cf","branch":"master"},"axon":{"sha":"3feda95c","branch":"master"},"brand":{"sha":"89d28f63","branch":"master"},"chipper":{"sha":"cba50451","branch":"master"},"dot":{"sha":"49561319","branch":"master"},"joist":{"sha":"2ff274d4","branch":"master"},"kite":{"sha":"a43e7dd9","branch":"master"},"nitroglycerin":{"sha":"ccaab9cd","branch":"master"},"phet-core":{"sha":"9c242cdc","branch":"master"},"phet-io":{"sha":"a03fa3de","branch":"master"},"phet-io-wrapper-classroom-activity":{"sha":"f666b06e","branch":"master"},"phet-io-wrapper-hookes-law-energy":{"sha":"b3ca28bf","branch":"master"},"phet-io-wrapper-lab-book":{"sha":"4144509a","branch":"master"},"phet-io-wrappers":{"sha":"a5a4edc5","branch":"master"},"phetcommon":{"sha":"04bc12ce","branch":"master"},"query-string-machine":{"sha":"4178d27a","branch":"master"},"scenery":{"sha":"687654c7","branch":"master"},"scenery-phet":{"sha":"fd193b3a","branch":"master"},"sherpa":{"sha":"79fb5b8c","branch":"master"},"states-of-matter":{"sha":"8222bec7","branch":"master"},"sun":{"sha":"cd84de33","branch":"master"},"tambo":{"sha":"2aac9c19","branch":"master"},"tandem":{"sha":"66d0f519","branch":"master"}}

</details>

**Comment by arouinfar** [comment]
Nice find @KatieWoe. @jbphet I left solid neon unattended and noticed considerable shifting after ~10 minutes. 

On startup:
<img width="439" alt="screen shot 2018-08-13 at 2 18 45 pm" src="https://user-images.githubusercontent.com/8419308/44056576-ea3b8570-9f05-11e8-9457-3153134b653e.png">

After ~10 minutes:
<img width="436" alt="screen shot 2018-08-13 at 2 33 19 pm" src="https://user-images.githubusercontent.com/8419308/44056577-ea508114-9f05-11e8-9031-755802360ff7.png">

@KatieWoe said: 
>  @jbphet is aware of this and finds it an acceptable compromise, but wanted an issue made to confirm this.

I don't think this is a particularly realistic use case, so I would agree that this is an acceptable trade-off. @jbphet please feel free to close this issue.

**Comment by jbphet** [comment]
Also, I think it's fairly "real" in that a blob of neon atoms would tend toward this state due to entropy.  Closing.
