### ISSUE TITLE
Neon and Argon Particles begin flashing and falling to the bottom

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/states-of-matter#222]
**Test device:**
Dell Laptop
**Operating System:**
Win 10
**Browser:**
Chrome
**Problem description:**
For phetsims/QA/issues/164
It is possible to continuously add neon or argon particles.  When too many are added they will start to flash, teleport, sink to the bottom, and overlap.  In addition, the needle showing pressure will be swinging wildly back and forth.  The flashing and teleportation seems a bit hard to see in the gifs.  I was not able to do this with oxygen or water.  This is not occurring in the published sim.
**Steps to reproduce:**
1. Select the Phase Changes screen
2. Select Neon or Argon (Neon is a bit easier)
3. Add particles using the bike pump continuously.
4. This should start to happen around when pressure is 90 atm for Neon

**Screenshots:**
![glitchamount](https://user-images.githubusercontent.com/41024075/43981242-504c5b96-9cae-11e8-9193-2a3a7e4fb227.gif)
https://drive.google.com/file/d/1MYfRLKGJsRRgkgwaX5J-2l_SRkxrBuOq/view?usp=sharing
https://drive.google.com/file/d/1jsIDrCJ5wjf340Df3AVOD3zF_NnldCPY/view?usp=sharing

Troubleshooting information (do not edit):

<details>

Name: ‪States of Matter‬
URL: https://phet-dev.colorado.edu/html/states-of-matter/1.1.0-dev.3/phet/states-of-matter_en_phet.html
Version: 1.1.0-dev.3 2018-08-06 20:52:14 UTC
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36
Language: en-US
Window: 1536x737
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"928741cf","branch":"master"},"axon":{"sha":"3feda95c","branch":"master"},"brand":{"sha":"89d28f63","branch":"master"},"chipper":{"sha":"cba50451","branch":"master"},"dot":{"sha":"49561319","branch":"master"},"joist":{"sha":"2ff274d4","branch":"master"},"kite":{"sha":"a43e7dd9","branch":"master"},"nitroglycerin":{"sha":"ccaab9cd","branch":"master"},"phet-core":{"sha":"9c242cdc","branch":"master"},"phet-io":{"sha":"a03fa3de","branch":"master"},"phet-io-wrapper-classroom-activity":{"sha":"f666b06e","branch":"master"},"phet-io-wrapper-hookes-law-energy":{"sha":"b3ca28bf","branch":"master"},"phet-io-wrapper-lab-book":{"sha":"4144509a","branch":"master"},"phet-io-wrappers":{"sha":"a5a4edc5","branch":"master"},"phetcommon":{"sha":"04bc12ce","branch":"master"},"query-string-machine":{"sha":"4178d27a","branch":"master"},"scenery":{"sha":"687654c7","branch":"master"},"scenery-phet":{"sha":"fd193b3a","branch":"master"},"sherpa":{"sha":"79fb5b8c","branch":"master"},"states-of-matter":{"sha":"8222bec7","branch":"master"},"sun":{"sha":"cd84de33","branch":"master"},"tambo":{"sha":"2aac9c19","branch":"master"},"tandem":{"sha":"66d0f519","branch":"master"}}

</details>

**Comment by KatieWoe** [comment]
I was able to get this bug with oxygen, but in a slightly different way.  I doesn't occur simply by adding more particles (though I did think I may have seen some jumpiness, I couldn't tell).  To do this with oxygen, fill the container then freeze the particles solid.  When attempting to heat them up again, the bug will occur.

https://drive.google.com/file/d/1NTy_SycgKBJrgoEawN0rsiyS6nQVY18d/view?usp=sharing

(Having a bit of trouble with google drive and the video.  Let me know if you have trouble seeing it)

**Comment by kellywurtz** [comment]
Test device:
Chromebook
Operating System:
Chrome OS - Version 67.0.3396.99
Browser:
Chrome

This bug also occurs with the Adjustable Attraction particles. Pump the container full of particles to around 150 atm, at which point they all fall to the bottom and then blow the lid off.

**Comment by kellywurtz** [comment]
Test device:
Macbook
Operating System:
OS X 10.10.5
Browser:
Safari

Also with the adjustable interaction particles, if you first cool the system to a solid state, and then begin pumping particles in, the bug will occur sooner (lower temperature & pressure/fewer particles) than if you had not initially cooled the system. On the other hand, if you initially warm the system a bit, and then begin pumping particles in, the bug will take longer to occur (higher temperature & pressure, more particles) than if you had not initially warmed the system.

**Comment by jbphet** [comment]
@KatieWoe - I believe this problem was due to the newly added code that compensates for drift.  This code (which was added by me) was using a total value for accumulating the drift, and that total was getting too high when lots of particles were in the container.  I have changed the code to instead use an average value for the accumulated drift (total/numParticles), and that seems to have fixed the problem.  I only tested the case of pumping in a lot of neon, and only on my Win 10 machine using Chrome.  It should be fixed on master - can QA please test the other cases that you and @kellywurtz described above?

**Comment by KatieWoe** [comment]
@jbphet Win 10 chrome using Argon and cooling it occasionally, I still saw the problem.
https://drive.google.com/file/d/1lOtWUZMw35APqJImzJeKMlyTkK6lZzte/view?usp=sharing
Long video.  Bug at the end.

**Comment by KatieWoe** [comment]
I also was able to reproduce it with neon on the same system, though it did not occur as quickly.  I filled it mostly full, then started to cool it down, similar to the method for argon.

I also noticed an issue that may be connected to this one, or it might be a general performance issue.  I noticed little "jumps" or skips in the animation of the particles as I was pumping.  I tried to capture them here, though it's a bit hard to see.
https://drive.google.com/file/d/1VduPlQMJzzBr9FP4j0aYT3_PB_WH3Kak/view?usp=sharing

**Comment by jbphet** [comment]
Another good test.  There was another place in the code that I'd missed that could also benefit from averaging.  Please test master again and see how things are looking now.

**Comment by KatieWoe** [comment]
Looks great.  Haven't seen the bug yet and everything generally looks smoother.  I'll keep looking through the day as I have time, but I think we can say this is fixed.

**Comment by jbphet** [comment]
Excellent!  Unassigning, and will add this to the list of issues to be double checked on the RC.

**Comment by KatieWoe** [comment]
Looks good.  Closing
