### ISSUE TITLE
Lost atom behind toolbox

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/states-of-matter#225]
**Test device:**
Dell Laptops
**Operating System:**
Win 10
**Browser:**
Chrome
**Problem description:**
For https://github.com/phetsims/QA/issues/185
This is present in the published version.  When on the interaction screen the moveable tom can be hid behind a toolbox.
**Steps to reproduce:**
1. Go to interactions screen
2. Open the forces toolbox
3. Select adjustable attraction
4. Drag the atom behind the toolboxes and let go

**Screenshots:**
![lost](https://user-images.githubusercontent.com/41024075/45459523-ec06bb00-b6b5-11e8-8311-019ac486136c.gif)

Troubleshooting information (do not edit):

<details>

Name: ‪States of Matter‬
URL: https://phet-dev.colorado.edu/html/states-of-matter/1.1.0-rc.1/phet/states-of-matter_en_phet.html
Version: 1.1.0-rc.1 2018-09-12 18:56:30 UTC
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.92 Safari/537.36
Language: en-US
Window: 1536x732
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"928741cf","branch":"HEAD"},"axon":{"sha":"d7ba44e2","branch":"HEAD"},"brand":{"sha":"89d28f63","branch":"HEAD"},"chipper":{"sha":"bbbb514a","branch":"HEAD"},"dot":{"sha":"820111c8","branch":"HEAD"},"joist":{"sha":"fb860843","branch":"HEAD"},"kite":{"sha":"59755f7e","branch":"HEAD"},"nitroglycerin":{"sha":"ccaab9cd","branch":"HEAD"},"phet-core":{"sha":"68a89cc4","branch":"HEAD"},"phet-io":{"sha":"364077cf","branch":"HEAD"},"phet-io-wrapper-classroom-activity":{"sha":"abc4ae3e","branch":"HEAD"},"phet-io-wrapper-hookes-law-energy":{"sha":"429886e7","branch":"HEAD"},"phet-io-wrapper-lab-book":{"sha":"ef0b0b0c","branch":"HEAD"},"phet-io-wrappers":{"sha":"7ec1a04a","branch":"HEAD"},"phetcommon":{"sha":"22b158d0","branch":"HEAD"},"query-string-machine":{"sha":"c2e502fb","branch":"HEAD"},"scenery":{"sha":"415371c3","branch":"HEAD"},"scenery-phet":{"sha":"94b92879","branch":"HEAD"},"sherpa":{"sha":"a9fd066b","branch":"HEAD"},"states-of-matter":{"sha":"de26f688","branch":"HEAD"},"sun":{"sha":"3086e97a","branch":"HEAD"},"tambo":{"sha":"0e5b9133","branch":"HEAD"},"tandem":{"sha":"a2348c0c","branch":"HEAD"}}

</details>

**Comment by phet-steele** [comment]
![Wow](https://media.giphy.com/media/26ufdipQqU2lhNA4g/giphy.gif)

At least you can just collapse the Forces panel to get it back.

**Comment by phet-steele** [comment]
I'm going to pass this off to @arouinfar first to see how much she cares about this, before a dev spends time on it.

**Comment by KatieWoe** [comment]
@phet-steele yeah I realized that after I had locked up and gone home for the day.

**Comment by jbphet** [comment]
> One option would be to trigger the "Return Atom" button when the atom completely disappears behind the panel.

This isn't easy.  The atom, and the model in general, has no knowledge of the position of the control panel, which is in the view.  The "Return Atom" button is made visible solely based on a distance from the original position, and incorporating the position and open/closed state of the control panel would be possible but not easy.

>  Otherwise, feel free to veto and close the issue.

Due to the non-trivial nature of what it would take to address this issue, I'm going to close it without fixing it.  It has existed in the sim as long as the sim has been around, and hasn't been a problem.
