### ISSUE TITLE
Heated solids float and rotate

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/states-of-matter#227]
**Test device:**
Dell Laptop and iPad Air 2
**Operating System:**
Win 10 and iOS 11.4.1
**Browser:**
Chrome and Safari
**Problem description:**
For https://github.com/phetsims/QA/issues/185 and elaboration on https://github.com/phetsims/states-of-matter/issues/214#issuecomment-410294041
When heating up a very cold solid it will both rise off the bottom of the container noticeably before even becoming a liquid, and start to rotate.  This behavior can be intermittent and is more noticeable in neon and argon from what I've seen.  Assigning @ariel-phet and @arouinfar to determine severity.
**Steps to reproduce:**
1. Go to Phase Changes screen
2. Cool the neon cube to 0K
3. Heat with heat bucket slider all the way up and observe behavior.  May take a few tries.

**Screenshots:**
![imflying](https://user-images.githubusercontent.com/41024075/45574160-50e42180-b82c-11e8-9822-cf1865484313.gif)

**Troubleshooting information (do not edit):**

<details>

Name: ‪States of Matter‬
URL: https://phet-dev.colorado.edu/html/states-of-matter/1.1.0-rc.1/phet/states-of-matter_en_phet.html
Version: 1.1.0-rc.1 2018-09-12 18:56:30 UTC
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.92 Safari/537.36
Language: en-US
Window: 1536x732
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"928741cf","branch":"HEAD"},"axon":{"sha":"d7ba44e2","branch":"HEAD"},"brand":{"sha":"89d28f63","branch":"HEAD"},"chipper":{"sha":"bbbb514a","branch":"HEAD"},"dot":{"sha":"820111c8","branch":"HEAD"},"joist":{"sha":"fb860843","branch":"HEAD"},"kite":{"sha":"59755f7e","branch":"HEAD"},"nitroglycerin":{"sha":"ccaab9cd","branch":"HEAD"},"phet-core":{"sha":"68a89cc4","branch":"HEAD"},"phet-io":{"sha":"364077cf","branch":"HEAD"},"phet-io-wrapper-classroom-activity":{"sha":"abc4ae3e","branch":"HEAD"},"phet-io-wrapper-hookes-law-energy":{"sha":"429886e7","branch":"HEAD"},"phet-io-wrapper-lab-book":{"sha":"ef0b0b0c","branch":"HEAD"},"phet-io-wrappers":{"sha":"7ec1a04a","branch":"HEAD"},"phetcommon":{"sha":"22b158d0","branch":"HEAD"},"query-string-machine":{"sha":"c2e502fb","branch":"HEAD"},"scenery":{"sha":"415371c3","branch":"HEAD"},"scenery-phet":{"sha":"94b92879","branch":"HEAD"},"sherpa":{"sha":"a9fd066b","branch":"HEAD"},"states-of-matter":{"sha":"de26f688","branch":"HEAD"},"sun":{"sha":"3086e97a","branch":"HEAD"},"tambo":{"sha":"0e5b9133","branch":"HEAD"},"tandem":{"sha":"a2348c0c","branch":"HEAD"}}

</details>

**Comment by arouinfar** [comment]
Interesting find @KatieWoe.

This behavior is present in the published version, though is somewhat mitigated by the solid drifting off to the side (#220). 

In general, the cooler the solid neon, the more it will behave like the screen capture in @KatieWoe's https://github.com/phetsims/states-of-matter/issues/227#issue-360448541. While there may be some strangeness coming from 0 K behavior, I was able to create similar situations in the 1-3 K range. That said, applying heat right after startup also results in a somewhat floaty neon. 

@jbphet did you weaken the gravity some? I can't remember. I'd also be interested to hear your thoughts about what's going on here.

**Comment by jbphet** [comment]
Gravity has not been weakened.  This is the same cause as the left-right drift, just in the Y direction, which is that the number of particles isn't high enough to guarantee that the net velocity is always zero.  The case that @KatieWoe captured about is about as bad as it gets, and it often isn't as noticeable.  In a design meeting, we discussed whether we wanted to try to moderate the Y direction too, and decided against, see https://github.com/phetsims/states-of-matter/issues/214#issuecomment-410294041.  We could always change this decision if necessary.

**Comment by ariel-phet** [comment]
@KatieWoe thanks for pointing out. I would not say this is so much a "bug" as potentially emergent behavior. It may look a tad funky in the worst case scenario, but...

1. this behavior exists in the published version (and no complaints)

2. heating is still doing the thing we expect...increase the motion of the particles, so I don't think this is pedagogically damaging or incorrect at all.

This model is extremely "tweaky", so I think we should not do anything in this case unless we start to see some complaints from users. 

Closing.
