### ISSUE TITLE
Neon and Argon on Interaction short when stringTest=long

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/states-of-matter#228]
**Test device:**
Dell Laptop
**Operating System:**
Win 10
**Browser:**
Chrome
**Problem description:**
For https://github.com/phetsims/QA/issues/185
When stringTest=long on the interaction screen, the Neon and Argon strings are much shorter than adjustable attraction and have a lot of room to expand.
**Steps to reproduce:**
1. Set stringTest=long
2. Go to Interaction screen
3. Compare three strings in toolbox to each other and available room.

**Screenshots:**
![long](https://user-images.githubusercontent.com/41024075/45576806-049ddf00-b836-11e8-97de-278a23989e67.PNG)

<details>
<summary>Troubleshooting Info</summary>

Name: 12345678901234567890123456789012345678901234567890
URL: https://phet-dev.colorado.edu/html/states-of-matter/1.1.0-rc.1/phet/states-of-matter_en_phet.html?stringTest=long
Version: 1.1.0-rc.1 2018-09-12 18:56:30 UTC
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.92 Safari/537.36
Language: en-US
Window: 1536x732
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"928741cf","branch":"HEAD"},"axon":{"sha":"d7ba44e2","branch":"HEAD"},"brand":{"sha":"89d28f63","branch":"HEAD"},"chipper":{"sha":"bbbb514a","branch":"HEAD"},"dot":{"sha":"820111c8","branch":"HEAD"},"joist":{"sha":"fb860843","branch":"HEAD"},"kite":{"sha":"59755f7e","branch":"HEAD"},"nitroglycerin":{"sha":"ccaab9cd","branch":"HEAD"},"phet-core":{"sha":"68a89cc4","branch":"HEAD"},"phet-io":{"sha":"364077cf","branch":"HEAD"},"phet-io-wrapper-classroom-activity":{"sha":"abc4ae3e","branch":"HEAD"},"phet-io-wrapper-hookes-law-energy":{"sha":"429886e7","branch":"HEAD"},"phet-io-wrapper-lab-book":{"sha":"ef0b0b0c","branch":"HEAD"},"phet-io-wrappers":{"sha":"7ec1a04a","branch":"HEAD"},"phetcommon":{"sha":"22b158d0","branch":"HEAD"},"query-string-machine":{"sha":"c2e502fb","branch":"HEAD"},"scenery":{"sha":"415371c3","branch":"HEAD"},"scenery-phet":{"sha":"94b92879","branch":"HEAD"},"sherpa":{"sha":"a9fd066b","branch":"HEAD"},"states-of-matter":{"sha":"de26f688","branch":"HEAD"},"sun":{"sha":"3086e97a","branch":"HEAD"},"tambo":{"sha":"0e5b9133","branch":"HEAD"},"tandem":{"sha":"a2348c0c","branch":"HEAD"}}

</details>

**Comment by arouinfar** [comment]
Good catch @KatieWoe. The maxWidths for Neon and Argon do look like they could be a bit bigger @jbphet.

**Comment by KatieWoe** [comment]
Confirm 1.1.0-rc.2

**Comment by jbphet** [comment]
Deployed in v1.1.0, closing.
