### ISSUE TITLE
Kelvin label appears thin

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/states-of-matter#229]
**Device**
Dell Laptop
**OS**
Win 8.1
**Browser**
Internet explorer
**Problem Description**
For https://github.com/phetsims/QA/issues/185
The K that is used for the Kelvin label in the temperature drop down looks much thinner on this platform than on others.  I have not seen this on other platforms yet, but will update the issue if I do.  It does seem to be the same way in the published version.
**Steps to Reproduce**
1. Go to the states screen on Win 8.1 IE
2. Examine the K in the temperature label
3. Compare to the K in another platform

**Screenshots**
Thin K
![k](https://user-images.githubusercontent.com/41024075/45700680-6d34d680-bb2a-11e8-9b91-9fb8343eba11.PNG)
Normal K
![normalk](https://user-images.githubusercontent.com/41024075/45700746-92294980-bb2a-11e8-8074-5fdfbbd1c5cf.PNG)

**Comment by arouinfar** [comment]
@KatieWoe my guess is that the thin K font was chosen by the browser (likely a fallback of sorts). Not particularly sure what devs do to specify font face, but perhaps the 'K' is somehow handled differently from other text in the sim. If that's the case, @jbphet can you update the 'K' so it has the same font face as other text in the sim? If this is just a weird browser thing that we can't control, feel free to close.

**Comment by KatieWoe** [comment]
Appears this way on Win 7 IE as well

**Comment by jbphet** [comment]
I think we should leave this as is.  The character isn't actually just the letter K, it's a unicode symbol that is specifically for degrees kelvin, see http://www.fileformat.info/info/unicode/char/212a/index.htm.  We could change it to be a simple K, but then it would be inconsistent with the symbol used for degrees Celsius.  Also, it looks reasonable on my machine in IE, as shown below.  It's actually being rendered in the same font as the numerical temperature value, though it may not look like it - it's just that it's a different symbol.  Also, from the sound of it, this is an IE-specific problem.  Given all of this, I think it would be far more trouble than it's worth to fix it.

![image](https://user-images.githubusercontent.com/3082831/46179484-b4347180-c278-11e8-9fa7-855a9e45e201.png)

Assigning to @ariel-phet to make sure he concurs, if so, please close.

**Comment by ariel-phet** [comment]
Both the degrees C and degrees K look crappy on my Windows 7 IE.

That being said, if you are using IE on Win 7 or 8.1 this is probably the least of your problems. 

Agree with @jbphet not worth effort to fix, but appreciate the attention to detail @KatieWoe!
