### ISSUE TITLE
Layered molecules behavioral inconsistency

### ISSUE THREAD

**Issue by phet-steele** [phetsims/states-of-matter#23]
This is a known occurrence in Java as well, and would be difficult to fix. When molecules are in front of the nozzle that leads from the pump, the newly added pumped molecules move as if the original molecules weren't there, instead of interacting with any other molecules . This makes sense because the new incoming molecules need a place to go so moving behind the "blockage" is acceptable. The problem comes when the container begins to be heated. The video below occurs after 0K has be reached and multiple molecules have been pumped behind the larger neon block. In this video, the molecules in the back react very differently and quite quickly to the addition of heat than the large neon block. When reproducing, it may be important to NOT do something in the video that I did which is to try to cool the new molecules before adding heat.

The Video:
https://drive.google.com/file/d/0B3HJopSo_QqLcEp0TVdNbUV0Tkk/view?usp=sharing

This occurred in Win 8.1 browsers with 1.0.0-dev.2 and Java 1.8.0_25

Troubleshooting information:
Name: States of Matter
URL: http://www.colorado.edu/physics/phet/dev/html/states-of-matter/1.0.0-dev.2/states-of-matter_en.html
Version: 1.0.0-dev.2
Features missing: touch
User Agent: Mozilla/5.0 (Windows NT 6.3; WOW64; rv:35.0) Gecko/20100101 Firefox/35.0
Language: en-US
Window: 1366x633
Pixel Ratio: 1/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0
Vendor: Mozilla (Mozilla)
Vertex: attribs: 16 varying: 10 uniform: 254
Texture: size: 16384 imageUnits: 16 (vertex: 4, combined: 20)
Max viewport: 16384x16384
OES_texture_float: true

**Comment by jbphet** [comment]
Assigning to @ariel-phet to have him decide if this is something that we should try to address.  It behaves this way because when incoming particles are added to the container, they can't start by overlapping any other particles or it will cause excessive repulsion in the model, and the particles become way too energetic and often blow out of the container.  So, newly added particles exist in a sort of 'ghost state' until such time when they are not overlapping any other particles.  When lots of particles are in the container, this can take a while.

There may be other approaches, such as limiting the max repulsive force, but this would take some time to experiment with.  We could also just limit the max number of particles, which wouldn't fully solve the problem but would make it less visible.  @ariel-phet can play with the sim and decide whether we need to pursue this.

**Comment by ariel-phet** [comment]
@jbphet and @phet-steele - actually I think this behavior is reasonable (a bit odd and visually inconsistent yes, but reasonable). The molecules being pumped in are in a gaseous state, so they actually are going to react to the addition of heat more obviously. The addition of heat goes into "lattice vibrations" for the solid block (which is kinetic energy), but visually that increase in kinetic energy is more obvious for gaseous particles. They are like the "vapor pressure" of the solid block.

In addition, the initial "ghost layering" seems OK to me. This is an edge case, and it seems like it would cause many complications to fix. Things get a bit whacky at super low temps anyhow, so I am OK with a bit of this weirdness. 

Great find though @phet-steele

**Comment by phet-steele** [comment]
So @ariel-phet, still reasonable behaviour? This isn't exactly the same procedure, but is certainly the same root issue. See all the water molecules along the bottom sort of just bouncing up and down instead of vaporizing?

![som01](https://cloud.githubusercontent.com/assets/5863899/15868917/18f4ea10-2ca7-11e6-9876-dc69e9fb211d.gif)

**Comment by phet-steele** [comment]
@ariel-phet when I say "not the same procedure", I really should clarify that there is hardly a procedure to this at all. I'm getting those dud water molecules from simple, non-edge-case, pumping.

**Comment by ariel-phet** [comment]
@phet-steele does this occur in the Java version?

**Comment by ariel-phet** [comment]
Please check and assign back to me if there is any discrepancy. If this behavior is in both, I will talk more with @jbphet

**Comment by phet-steele** [comment]
@ariel-phet yup.

**Comment by ariel-phet** [comment]
Discussed with @jbphet 7/26/2016 sounds like not much can be done about this issue without potentially causing some funkiness in the model. Marking as "won't fix"
