### ISSUE TITLE
problem with layout of MultiLineText

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/states-of-matter#230]
Related to https://github.com/phetsims/scenery-phet/issues/392.

Of the 10 sims that use MultiLineText, SOM is the only sim that exhibits a difference after reimplementation of MultiLineText as a subclass of RichText.

_Phase Change_ screen, in published version 1.0.6:

![screenshot_764](https://user-images.githubusercontent.com/3046552/46171496-ef757700-c25d-11e8-9342-595ed4410c71.png)

In _master_ after reimplementing MultiLineText:

![screenshot_765](https://user-images.githubusercontent.com/3046552/46171512-fac8a280-c25d-11e8-8cde-b95e3478bb7f.png)

Both the "triple point" and "critical point" labels have moved up significantly, and "critical point" is kissing the bottom of "liquid". I showed this to @jbphet. He said there was some tricky layout code in PhaseDiagram.js, and that I should create this issue and assign it to him.

**Comment by jbphet** [comment]
For reference, this is **not** an issue with the 1.1 RC that is currently in progress.

**Comment by jbphet** [comment]
Fixed, closing.
