### ISSUE TITLE
Lines separating nav bar icons too thin

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/states-of-matter#232]
Device
Mac
OS
Mac OS 10.14
Browser
Safari
Problem Description
For https://github.com/phetsims/QA/issues/205
The lines that appear on the sides of the nav bar icons when moused over can look a bit thin depending on where they are.  Doesn't seem to appear on every platform/browser
Steps to Reproduce
1. Enter the 1st screen of the sim
2. Mouse over the icons on the nav bar

Screenshots
![screen shot 2018-10-09 at 10 18 02 am](https://user-images.githubusercontent.com/41024075/46688880-bae9af80-cbbb-11e8-94db-45f63a64606d.png)
![screen shot 2018-10-09 at 10 18 07 am](https://user-images.githubusercontent.com/41024075/46688881-bae9af80-cbbb-11e8-8df7-47156ce39696.png)

**Comment by jbphet** [comment]
@KatieWoe - the screenshots shown look like they are from a long string test.  Is this problem with the thin separator lines a general one, or does it only occur during such tests?

**Comment by jbphet** [comment]
Also, it's important to know if this is unique to this RC or is also a problem with the published version.

**Comment by KatieWoe** [comment]
@jbphet it does appear without the string test and it does seem to be in the published version

**Comment by arouinfar** [comment]
Nice attention to detail @KatieWoe.

@jbphet @KatieWoe I tested the the published version of SOM and rc.2 in macOS 10.13.6 and latest Chrome/Firefox/Safari. The lines between screen icons are appearing normally.

This issue is pretty subtle, and I don't imagine it would interfere with usability.  @KatieWoe does this show up for any other published sims? If so, we could open an issue in joist to investigate, but it seems pretty low priority to me.

**Comment by KatieWoe** [comment]
It does seem to happen on published sims.  @arouinfar

**Comment by arouinfar** [comment]
If it's a general issue popping up in other sims, then I would move this issue to joist @KatieWoe. Please include examples of which OS/browser combinations result in the thinner line, as well as which sims it's appearing in.

This is a pretty subtle issue (though still good to report!), but I don't think has any effect on usability. I imagine Oliver would have opened an issue if he'd been getting complaints to phetthelp, which hasn't happened.

I don't think this issue should have any impact on the redeploy of SOM.

**Comment by KatieWoe** [comment]
Moved to Joist
