### ISSUE TITLE
Phase diagram doesn't change for water

### ISSUE THREAD

**Issue by jbphet** [phetsims/states-of-matter#233]
In the old (Java) sim, the phase diagram switches for water such that the angle of the line that shows the division between solid and liquid changes.  From the old sim, here is the diagram for non-water:

![image](https://user-images.githubusercontent.com/3082831/46758707-c48e1880-cc8a-11e8-85ee-5e566bb680db.png)

...and here is what it looks like for water:

![image](https://user-images.githubusercontent.com/3082831/46758773-ed161280-cc8a-11e8-910b-ae7e6db22ac2.png)

For the HTML5 version, this isn't happening on master, nor on the currently live version, v1.0.6.

**Comment by jbphet** [comment]
I fixed this on master, but should propagate to the currently release branch 1.1.

**Comment by KatieWoe** [comment]
Looks good 1.1.0-rc.3

**Comment by KatieWoe** [comment]
Actually, I just noticed this when stringTest=double.  The string gets too long and goes over the new boarder.
![double](https://user-images.githubusercontent.com/41024075/47594302-ebf60e00-d937-11e8-8607-6e9c2f4f9634.PNG)

**Comment by jbphet** [comment]
Deployed in v1.1.0, closing.
