### ISSUE TITLE
Temperature of water decreasing too quickly?

### ISSUE THREAD

**Issue by lmulhall-phet** [phetsims/states-of-matter#235]
For https://github.com/phetsims/QA/issues/205. If you go to the states screen and decrease the temperature of water, it goes from 146 K to 40 K in about 3 seconds. Decreasing the temperature of neon from 146 K to 40 K takes about 20 seconds. I asked Amy; she said the temperature changing as quickly as it does doesn’t seem correct. She referred me to John, who said there’s some sort of trade-off in how the physics of the temperature change is simulated. John then referred me to Amy.

**Comment by arouinfar** [comment]
Great observation @lmulhall-phet.

In general, changing the temperature of water is much faster than the other substances in the sim. This is unexpected, as water's large specific heat requires MORE heat to be exchanged to change the temperature. I compared rc.2 to the published version, and the behavior is the same.

I realize that the model for water is a bit finicky, and there haven't been any user complaints, so I am content to leave this issue alone. If you agree @jbphet, please feel free to close and as `type:wontfix`.

**Comment by ariel-phet** [comment]
Agreed, good to observe @lmulhall-phet, but this is the published sim behavior, and definitely would be lots of work to change. Specific heat is not really a learning goal of the sim, so I think different heating/cooling characteristics with different substances is fine. 

Closing
