### ISSUE TITLE
issues with CompositeThermometerNode

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/states-of-matter#236]
I'm looking at `CompositeThermometerNode` because something similar is needed in Gas Properties.  Screenshot from SOM _States_ screen:

![screenshot_861](https://user-images.githubusercontent.com/3046552/48446506-a79ba800-e756-11e8-87c5-66ac6674a968.png)

A few issues:

- [x] Temperature readout is not properly localized.  The order of value and units is hardcoded:

```js
120 self.temperatureKelvinText.setText( tempInKelvinRounded + ' ' + kelvinUnitsString );
121 self.temperatureCelsiusText.setText( Util.roundSymmetric( tempInKelvin - 273.15 ) + ' ' + celsiusUnitsString );
```

Order of value and units should be translatable, via a pattern like `'{{value}} {{units}}'` used with `StringUtils.fillIn`.

- [x] `MAX_LENGTH_TEMPERATURE_TEXT` is not localized (hardcoded format) and assumes that `celsiusUnitsString` is longer than `kelvinUnitsString`:

```js
32 var MAX_LENGTH_TEMPERATURE_TEXT = '99999 ' + celsiusUnitsString;
```

- [x] `temperatureProperty` is misnamed. It is not the temperature, it's actually the units, and should be named`temperatureUnitsProperty`.   This was initially confusing when trying to reuse this code.

- [x] `this.multipleParticleModel `, `this.modelViewTransform`, `this.temperatureInKelvinProperty` `this.temperatureKelvinText` and ` this.temperatureCelsiusText` could all be `const`, because they are not used outside of the constructor. 

- [x] Items in the ComboBox should be right justified, so that the units don't jump around when the number of digits in the temperature value changes.  Use the new `align` option with ComboBox, and see use of `SCENERY_PHET/NumberDisplay` in `GAS_PROPERTIES/TemperatureComboBox`.

**Comment by pixelzoom** [comment]
- [ ] Items in the ComboBox should ideally be right justified, so that the units don't jump around when the number of digits in the temperature value changes.

**Comment by arouinfar** [comment]
Thanks @pixelzoom. I think it's best that we discuss the broader issue of toggling units with comboboxes in the next design meeting.

If we decide to continue with a combobox, then I agree that the contents should be right-justified.

Another quirk that @pixelzoom brought to my attention is the null value. If the container is empty (which is nearly impossible to do), then the displayed temperature will be "--" without any units.

[CompositeThermometerNode.js L126-L127](https://github.com/phetsims/states-of-matter/blob/master/js/common/view/CompositeThermometerNode.js#L126-L127):
```js
126        self.temperatureKelvinText.setText( '--' );
127        self.temperatureCelsiusText.setText( '--' );
```

Generally, we have used a single hyphen for null readouts, not two.
<img src="https://user-images.githubusercontent.com/8419308/48515671-928a4c00-e81e-11e8-881a-c26665e562a1.png" width=150>  <img src="https://user-images.githubusercontent.com/8419308/48515856-2f4ce980-e81f-11e8-881f-71517fc74b9d.png" width=150> <img src="https://user-images.githubusercontent.com/8419308/48515882-3e339c00-e81f-11e8-9be2-d0eb75c81621.png" width=150><img src="https://user-images.githubusercontent.com/8419308/48515901-4ab7f480-e81f-11e8-8a53-d4126f2648de.png" width=150>

I think the bigger issue, however, is the lack of units. This means that for an empty container, both combobox options will read "--". For SOM this is very unlikely to cause any user problems, as an empty container is practically impossible to create. However, GasProps opens with an empty container.

**Comment by arouinfar** [comment]
I've linked this issue in the GasProps design meeting notes, so unassigning myself for now.

**Comment by pixelzoom** [comment]
- [ ] Options are duplicated inline for both instantiations, see `PhaseChangesScreenView` and 

```js
    this.compositeThermometerNode = new CompositeThermometerNode( multipleParticleModel, modelViewTransform, {
      font: new PhetFont( 20 ),
      fill: 'white'
```

Either make these the defaults, or move them to `SOMConstants`.

**Comment by pixelzoom** [comment]
@jbphet FYI, see ComboDisplay in https://github.com/phetsims/scenery-phet/issues/449.  This is a specialization of SUN/ComboBox whose items display AXON/NumberProperties using SCENERY_PHET/NumberDisplays.

**Comment by pixelzoom** [comment]
When you convert to ComboBoxDisplay, you should be aware of https://github.com/phetsims/scenery-phet/issues/482.

**Comment by arouinfar** [comment]
As part of the PhET-iO design review for #245, @kathy-phet and I took a look at this issue, and it seems like this is something that should be addressed @jbphet.

**Comment by jbphet** [comment]
I stand corrected, I didn't realize that `NumberDisplay`, and thus `ComboBoxDisplay`, had built-in support for no-value situations.  I've done the refactor to use `ComboBoxDisplay`.  @pixelzoom - you're welcome to review if so inclined.

**Comment by pixelzoom** [comment]
👍 closing.
