### ISSUE TITLE
incorrect lighting on Pressure gauge

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/states-of-matter#238]
Noted while adding a similar gauge to Gas Properties.  

Pressure gauge looks like it's lit from below, which does not match the PhET standard.  

![screenshot_885](https://user-images.githubusercontent.com/3046552/48796123-02378580-ecbc-11e8-821b-ed9a992f881f.png)

**Comment by pixelzoom** [comment]
Lighting in Gas Properties design doc makes more sense, where it's lit from the front:

![screenshot_886](https://user-images.githubusercontent.com/3046552/48796221-41fe6d00-ecbc-11e8-8438-d80d61ccf3b9.png)

**Comment by arouinfar** [comment]
Good catch @pixelzoom. At minimum, I would reverse the gradient in states-of-matter, though I do prefer the  gradient in https://github.com/phetsims/states-of-matter/issues/238#issuecomment-440392819.

That component is drawn in code, so it is something that @jbphet would need to address. Not sure if this is within the scope of the states-of-matter family of redeploys, but if this is a quick tweak, it'd be nice to address @jbphet. Not super high priority, though.

**Comment by pixelzoom** [comment]
In Gas Properties, I've implemented the gradient so that the light source looks like it's slightly above.  See `POST_GRADIENT` in PressureGaugeNode.

```js
  // lit from above
  const POST_GRADIENT = new LinearGradient( 0, 0, 0, POST_HEIGHT )
    .addColorStop( 0, 'rgb( 120, 120, 120 )' )
    .addColorStop( 0.3, 'rgb( 220, 220, 220 )' )
    .addColorStop( 0.5, 'rgb( 220, 220, 220 )' )
    .addColorStop( 1, 'rgb( 100, 100, 100 )' );
```

![screenshot_887](https://user-images.githubusercontent.com/3046552/48798448-ea630000-ecc1-11e8-83f3-9c36e609a5f7.png)

**Comment by jbphet** [comment]
I lifted the code from the above comment, put it in SOM, and it looks great.  There is an upcoming maintenance release for this sim, and the basics version is also due for release, so I went ahead and cherry picked the commit to the release branch (1.1).  I'm going to leave this GitHub issue open and unassigned to remind me to double check it on the next release.

**Comment by jbphet** [comment]
The sim has been redeployed and the connector now looks as though it is lit from the front in the published version.  Closing.
