### ISSUE TITLE
Rapid water phase switching causes explosion

### ISSUE THREAD

**Issue by phet-steele** [phetsims/states-of-matter#24]
On the States screen, rapidly switching between the solid, liquid, and gas phases of water for a bit causes the lid to blow off.

![statomat](https://cloud.githubusercontent.com/assets/5863899/6006769/4e91e608-aad2-11e4-949f-11dac3533ae7.gif)

Occurs in all Win 8.1 browsers and OSX 10.9.5 browsers on 1.0.0-dev.2

Troubleshooting information:
Name: States of Matter
URL: http://www.colorado.edu/physics/phet/dev/html/states-of-matter/1.0.0-dev.2/states-of-matter_en.html
Version: 1.0.0-dev.2
Features missing: touch
User Agent: Mozilla/5.0 (Windows NT 6.3; WOW64; rv:35.0) Gecko/20100101 Firefox/35.0
Language: en-US
Window: 1366x633
Pixel Ratio: 1/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0
Vendor: Mozilla (Mozilla)
Vertex: attribs: 16 varying: 10 uniform: 254
Texture: size: 16384 imageUnits: 16 (vertex: 4, combined: 20)
Max viewport: 16384x16384
OES_texture_float: true

**Comment by jbphet** [comment]
This can be easily duplicated on version 1.0.0-dev.2.  I just tested the current version on the master branch, and it seems like @ChandrashekarBemagoni's change has fixed the behavior.  I will leave this open and assign to me for now, and will have it tested on the next dev release.

**Comment by jbphet** [comment]
I just tested this on http://www.colorado.edu/physics/phet/dev/html/states-of-matter/1.0.0-dev.4/states-of-matter_en.html and the problem appears to be corrected.  Closing.
