### ISSUE TITLE
behavior of bicycle pump is incorrect

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/states-of-matter#242]
Related to https://github.com/phetsims/states-of-matter/issues/217 and identified as a problem in https://github.com/phetsims/gas-properties/issues/33.

https://github.com/phetsims/gas-properties/issues/33#issuecomment-454599692: 
> Handle speed should never determine the number of particles pumped in.

https://github.com/phetsims/gas-properties/issues/33#issuecomment-454600973:
> The behavior in SOM is incorrect, but it can wait to get corrected until @chrisklus works on phetsims/states-of-matter#217.

**Comment by chrisklus** [comment]
@pixelzoom this should be fixed on SOM master.

**Comment by pixelzoom** [comment]
@chrisklus does this need to be reviewed, or can it be closed?

**Comment by chrisklus** [comment]
Ready to close.
