### ISSUE TITLE
Use TimeControlNode for Play/Pause/Step buttons

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/states-of-matter#246]
From https://github.com/phetsims/scenery-phet/issues/561. A scenery-phet/TimeControlNode was created that combines the PlayPauseButton and StepForward button and includes PhET-iO and PDOM instrumentation. It should be used in this sim. Assigning to responsible dev.

In this case it may just be a replacement for the SOMPlayPauseStepControl.

**Comment by jessegreenberg** [comment]
Sorry @SaurabhTotey I recently added an assertion that the buttons in TimeControlNode all use the same `playingProperty`, which had an impact here. Proposed fix made in above commit, can you please make sure it is still correct?

**Comment by SaurabhTotey** [comment]
It looks good to me and I couldn't uncover any issues when doing a brief testing. As such, I will close this issue. Please reopen if there is anything left for this I should do.
