### ISSUE TITLE
Point on graph flickers at lowest potential

### ISSUE THREAD

**Issue by phet-steele** [phetsims/states-of-matter#25]
On the Interaction screen, the point on the graph will flicker at the lowest potential if the atoms are visibly stationary. The lowest potential in this situation is the highest value of interaction strength for the adjustable attraction atom. This also appears to happen at any atom diameter.

To reproduce,
1. Go to the Interaction screen.
2. Choose the Adjustable Attraction atom.
3. Slide the Interaction Strength to the highest strength value, all the way to the right.
4. The point on the graph, that's now at the lowest point of the potential well, will begin flickering.

Occurs in all Win 8.1 browsers and OSX 10.9.5 browsers on 1.0.0-dev.2

Troubleshooting information:
Name: States of Matter
URL: http://www.colorado.edu/physics/phet/dev/html/states-of-matter/1.0.0-dev.2/states-of-matter_en.html
Version: 1.0.0-dev.2
Features missing: touch
User Agent: Mozilla/5.0 (Windows NT 6.3; WOW64; rv:35.0) Gecko/20100101 Firefox/35.0
Language: en-US
Window: 1366x633
Pixel Ratio: 1/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0
Vendor: Mozilla (Mozilla)
Vertex: attribs: 16 varying: 10 uniform: 254
Texture: size: 16384 imageUnits: 16 (vertex: 4, combined: 20)
Max viewport: 16384x16384
OES_texture_float: true

**Comment by jbphet** [comment]
I was able to duplicate this on the current version of master.  Assigning to @kmsravindra to investigate.

**Comment by notsiddhartha** [comment]
A similar issue exists in the Java version as well. Looks like once in a while the point is going beyond the chart bounds and hence is not displayed resulting in a flickering display.

**Comment by ycarpenterphet** [comment]
The fix suggested for issue #63 should resolve this issue automatically as well.

**Comment by ChandrashekarBemagoni** [comment]
Fixed in above commit. Assigning to @ycarpenterphet  for verification

**Comment by jbphet** [comment]
Assigning to @phet-steele for verification.

**Comment by phet-steele** [comment]
#63 fixed this.
