### ISSUE TITLE
branch: serializeParticleState

### ISSUE THREAD

**Issue by zepumph** [phetsims/states-of-matter#253]
From https://github.com/phetsims/states-of-matter/issues/252

**Comment by jbphet** [comment]
The contents of this branch have been moved into master.  I think I should keep it around for a week to make sure master is working well and I didn't miss anything, then I'll delete it.

**Comment by jbphet** [comment]
Particle serialization has been merged in and seems to be working well.  Closing.

**Comment by jbphet** [comment]
Reopening.  This branch was restored during an effort to recover some branches that were accidentally deleted.  This one had been _intentionally_ deleted, and now needs to be re-deleted.  See https://github.com/phetsims/special-ops/issues/198.

**Comment by jbphet** [comment]
Re-deletion complete.  Closing.
