### ISSUE TITLE
Slider string too low

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/states-of-matter#255]
**Test device**
Dell
**Operating System**
Win 10
**Browser**
Chrome
**Problem description**
For ES6 Testing
The string above the interaction strength slider on the second screen is in the same place as the slider, rather than above it.

**Visuals**
![titleonslider](https://user-images.githubusercontent.com/41024075/75483338-e1042100-5963-11ea-8b25-d11bb65ec34e.png)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: States of Matter
URL: http://phettest.colorado.edu/states-of-matter/states-of-matter_en.html?ea&brand=phet
Version: 1.2.0-dev.2 (require.js)
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.122 Safari/537.36
Language: en-US
Window: 1536x722
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by jbphet** [comment]
Fixed, closing.
