### ISSUE TITLE
PhET-iO design review comments

### ISSUE THREAD

**Issue by arouinfar** [phetsims/states-of-matter#257]
For #245 @kathy-phet and I reviewed the States screen in studio, and have the following comments/questions. For issues that are also relevant to the Phase Changes screen, I've omitted the `statesScreen` prefix from the tandem.

- [x] There are several model elements that are irrelevant to the States screen which should be removed, including:
* `statesScreen.model.interactionPotentialDiagramExpandedProperty`
* `statesScreen.model.interactionStrengthProperty`
* `statesScreen.model.isExplodedProperty`
* `statesScreen.model.phaseDiagramExpandedProperty`
* `statesScreen.model.targetContainerHeightProperty`

- [x] Similarly, `statesScreen.model.substanceProperty` includes an option for `ADJUSTABLE_ATOM` which should be removed.

- [x] `model.heatingCoolingAmountProperty` has a slider control in studio which effects the model, but the HeaterCoolerNode doesn't animate when controlled from studio. It seems like this is the linked property for `view.heaterCoolerNode.slider`, but since the HeaterCoolerNode doesn't animate when adjusting this property in studio, we are wondering if there is some other intermediary property/element that may be missing from the tree.

- [x] `view.heaterCoolerNode.slider` needs a linked property to the corresponding model element.

- [x] `statesScreen.model.temperatureSetPointProperty` needs documentation and units. We aren't entirely sure what it represents, but it seems related to the state buttons -- solid is 0.15, liquid is 0.34, and gas is 1. Could this property be used to monitor the state of the particles in the container?

- [x] `model.particleContainerHeightProperty` needs units.

- [x] Remove "Selector" from the names of the radio buttons in `view.atomsAndMoleculesSelectionPanel.radioButtonGroup` (e.g. `argon` instead of `argonSelector`).  This is more parallel to how we've named other radioButtonGroups in PhET-iO sims.

- [x] The atom/molecule text and corresponding radio button don't have great proximity in the tree. `view.atomsAndMoleculesSelectionPanel.argonText` seems like it could be a child of 
`view.atomsAndMoleculesSelectionPanel.radioButtonGroup.argonSelector` (e.g. toggling the visibleProperty of `argonSelector` affects the `argonText`). Could we nest the text below the corresponding radio button?  

- [x] Changing the text of Atoms & Molecules radio buttons can break the layout pretty badly. It seems like the sim keeps a fixed distance between the text and icon, so perhaps this is the culprit? You may also want to check in with @samreid because he has been working on layout issues in PhET-iO.

* <s>The state buttons under `statesScreen.view.solidLiquidGasPhaseControlNode` should each have a linked property. Alternatively, if it would make sense to nest the property under the button (eg. move `gasSelectedProperty` under `gasStateButton`), that would also be fine with us. We are fine with either option.</s>

- [x] Why is `view.compositeThermometerNode.temperatureInKelvinProperty` in the view? How is the temperature set in the sim?

- [ ] `view.compositeThermometerNode` should probably be using ComboBoxDisplay, see #236.

- [x] Why aren't `view.compositeThermometerNode.temperatureCelsiusText` and `view.compositeThermometerNode.temperatureKelvinText` under the listBox?

- [x] `temperatureCelsiusText` and `temperatureKelvinText` is pretty verbose. Let's rename them `celsius` and `kelvin`, respectively. (`phScale.macroScreen.view.soluteComboBox.listBox` and `projectileMotion.labScreen.view.projectilePanel.projectileChoiceComboBox.listBox` are parallel examples.)

**Comment by arouinfar** [comment]
@kathy-phet I reviewed this with @jbphet today, and we had some further questions about this item:

>  The state buttons under `statesScreen.view.solidLiquidGasPhaseControlNode` should each have a linked property. Alternatively, if it would make sense to nest the property under the button (eg. move `gasSelectedProperty` under `gasStateButton`), that would also be fine with us. We are fine with either option.

Here's the current tree structure
![image](https://user-images.githubusercontent.com/8419308/77212436-b6256c80-6acc-11ea-8687-aae1b039a30b.png)

Looking at this again, I'm not sure that it's necessary to add a linked property to each of the state buttons, since the corresponding property is a sibling of the button itself. 

@jbphet thinks it may be relatively straight forward to nest the property under the button (eg. move `gasSelectedProperty` under `gasStateButton`). However, we would want to check with the phet-io team to make sure that doesn't violate any conventions. 

@kathy-phet what would you advise?

**Comment by jbphet** [comment]
@arouinfar said:

> @jbphet thinks it may be relatively straight forward to nest the property under the button

Upon further review, it actually doesn't look so easy, because the code doesn't pass in tandems for radio buttons, it passes in a tandem *name*, which the radio button group then uses in the process of creating the button.  Because of this, it's not easy to pre-create the tandem and next things like the button text underneath.  So, if this is what you want, I'll need to work with the phet-io team to figure out how to do it.

**Comment by jbphet** [comment]
I have a question about migrating `CompositeThermometerNode` to use `ComboDisplayBox` instead of `ComboBox`.   I've examined the code, and it looks like it would be fairly straightforward change except for one thing: in the current implementation, there is code in place to display "--" if there are no particles in the container.  `ComboDisplayBox` can't do this, because it displays values for `NumberProperty` instances.  This condition - i.e. an empty particle container - is quite hard to create, since you have to explode the container several times and wait until all the particles are gone.  However, I remember discussing this situation during the initial design and deciding that it wasn't appropriate to assign a temperature value to nothing, and even interstellar space is at 3 K, so showing a zero didn't seem right.

What shall we do here?  Should we go ahead and display a value of zero for no particles and use `ComboBoxDisplay`, or shall we keep what we have now and refine it to work better for phet-io?

I personally favor the latter (displaying "--" instead of zero for no particles), and will move in that direction for now.  @arouinfar and @kathy-phet - please let me know your recommendation ASAP so that I don't waste too much time if you feel otherwise.

**Comment by jbphet** [comment]
Assigning @ariel-phet in case he has an opinion on the previous comment.

**Comment by jbphet** [comment]
@arouinfar and @kathy-phet - I've addressed all but two of the issues on the list, and those issues are discussed above.  I think this is ready for the next round of review.

**Comment by kathy-phet** [comment]
JB wrote: 
> I personally favor the latter (displaying "--" instead of zero for no particles), and will move in that direction for now.
I agree that we should display --. It doesn't make sense to display 0 in this case (scientifically wrong

**Comment by kathy-phet** [comment]
Amy wrote: 
>Looking at this again, I'm not sure that it's necessary to add a linked property to each of the state buttons, since the corresponding property is a sibling of the button itself.

>@jbphet thinks it may be relatively straight forward to nest the property under the button (eg. move gasSelectedProperty under gasStateButton). However, we would want to check with the phet-io team to make sure that doesn't violate any conventions.

>@kathy-phet what would you advise?

I think its fine to leave this the way it is since it is complicated to change it. I don't think we should do anything special.

**Comment by arouinfar** [comment]
> I personally favor the latter (displaying "--" instead of zero for no particles), and will move in that direction for now. 

That's also my preference @jbphet.

> I think its fine to leave this the way it is since it is complicated to change it. I don't think we should do anything special.

Thanks @kathy-phet. @jbphet I've crossed out this item.

**Comment by arouinfar** [comment]
@kathy-phet and I reviewed the CompositeThermometerNode and the changes are looking good @jbphet. Can you add a linked property to `temperatureInKelvinProperty` somewhere within CompositeThermometerNode, or possibly in temperatureComboBox, whichever makes more sense to you.

**Comment by jbphet** [comment]
@arouinfar - I've added the linked property described above.  Can you check it out?  I think that's in for this particular GitHub issue, so if it looks good, you can go ahead and close.

**Comment by arouinfar** [comment]
Thanks @jbphet! Looks good in master.
