### ISSUE TITLE
Center line missing on interaction potential chart

### ISSUE THREAD

**Issue by jbphet** [phetsims/states-of-matter#259]
The current interaction potential chart on the "Phase Changes" screen is missing the horizontal center line.  It looks like this:

![image](https://user-images.githubusercontent.com/3082831/75830455-282c5080-5d6e-11ea-8759-22f4ca6429e5.png)

The live version (v 1.1.10) looks like this:

![image](https://user-images.githubusercontent.com/3082831/75830539-590c8580-5d6e-11ea-99bb-b055148510c7.png)

**Comment by jbphet** [comment]
After doing some forensics, it looks like this was removed in an attempt to fix the problem that the center axis line goes over the potential (red) line in https://github.com/phetsims/atomic-interactions/issues/75.

Specifically, here is what I think is the problematic commit: https://github.com/phetsims/states-of-matter/commit/bc510f768ca3d7f45dd45a53dd4450664469d606

**Comment by jbphet** [comment]
I've made some changes, here's what it looks like now (using water as the substance, which makes the line more apparent):

![image](https://user-images.githubusercontent.com/3082831/75830819-0e3f3d80-5d6f-11ea-99e0-0e1b2ad17062.png)

**Comment by jbphet** [comment]
@SaurabhTotey - please review.  It looks like you made the commit that removed the line, and I wanted to make sure that this wasn't intentional.  If all looks good, please close.

**Comment by SaurabhTotey** [comment]
Oh, I completely missed this side-effect! It wasn't my intention to remove the line for the interaction potential chart, but it looks good now. Closing.
