### ISSUE TITLE
Changing between types of atoms and molecules explodes water in "Phase Change" Scene

### ISSUE THREAD

**Issue by orejolaphet** [phetsims/states-of-matter#26]
Related to https://github.com/phetsims/states-of-matter/issues/24
Test device: Mac Book Pro 
Operating System: 10.9.4
Browser: Chrome 39

Problem description:
In the "Phase Change" Scene if you give a solid enough energy so that it reaches the critical point, rapidly changing between types of molecules will cause water to explode upon selection.

Steps to reproduce:
-Select "Phase Change" scene
-Add heat to the solid so that on its phase diagram it passes the critical point
-Rapidly click between different types of molecules and atoms (Click Argon, then water immediately after)
-Water will explode once selected 

Troubleshooting information (do not edit):
Name: States of Matter
URL: http://www.colorado.edu/physics/phet/dev/html/states-of-matter/1.0.0-dev.2/states-of-matter_en.html
Version: 1.0.0-dev.2
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.99 Safari/537.36
Language: en-US
Window: 947x571
Pixel Ratio: 1.100000023841858/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 15 uniform: 1024
Texture: size: 8192 imageUnits: 16 (vertex: 16, combined: 16)
Max viewport: 8192x8192
OES_texture_float: true

**Comment by jbphet** [comment]
This is easy to duplicate on v1.0.0-dev.2, but seems to be fixed on master with @ChandrashekarBemagoni's recent commit.  I will self assign, and will have this tested on the next dev version.

**Comment by jbphet** [comment]
I just tested this on http://www.colorado.edu/physics/phet/dev/html/states-of-matter/1.0.0-dev.4/states-of-matter_en.html and the problem appears to have been corrected.  Closing.
