### ISSUE TITLE
MultipleParticleModelIO details visible in studio

### ISSUE THREAD

**Issue by arouinfar** [phetsims/states-of-matter#264]
When reviewing #257 with @jbphet, I noticed that the model details are now visible in studio when selecting `statesOfMatter.statesScreen.model` or `statesOfMatter.phaseChangesScreen.model`. I've never seen this in studio before, and I'm not convinced this is a useful way to display this information. Is this something that we could easily hide?

![image](https://user-images.githubusercontent.com/8419308/77212102-a3f6fe80-6acb-11ea-9479-4b94a4d8b297.png)

@jbphet mentioned that this may be a result of the recent work on `MultipleParticleModelIO`, so assigning @zepumph to take a look.

**Comment by zepumph** [comment]
Oh boy. That is some state! Currently there is no way to hide this, and it needs to be `phetioState:true` to support the state feature. 

The simplest but not perhaps the best solution is likely to coopt `phetioStudioControl` to hide the "initial state" of an element when set to false.

There are currently 24 usages of `phetioStudioControl:false` in the code, and nothing struck me immediately of instances where we need to see the initial state, but to not be able to control it. No matter it is a bit sloppy. @samreid what do you think. How best might we be able to hide this? Should we try to hide it at all?

**Comment by zepumph** [comment]
This is going to be handled generally by either https://github.com/phetsims/studio/issues/117 or https://github.com/phetsims/studio/issues/116

**Comment by zepumph** [comment]
I will handle this as part of https://github.com/phetsims/phet-io/issues/1644

**Comment by zepumph** [comment]
Over in https://github.com/phetsims/phet-io/issues/1644, we added support to omit any state that is nested under the `private` field of the state object. The above commit hides all the state for MultipleParticleModelIO. @arouinfar can you please review. Does it look better now that the state is hidden for this model?

**Comment by arouinfar** [comment]
@zepumph thanks! Things are definitely looking cleaner in studio.
