### ISSUE TITLE
PhET-iO design review comments - Interactions Screen

### ISSUE THREAD

**Issue by arouinfar** [phetsims/states-of-matter#266]
For #245, and a continuation of #257 and #265.

- [x] The tandem for this screen should match what's in the sim, `interactionScreen` not `atomicInteractionsScreen`.

- [x] Does `atomicInteractionsScreen.model.interactionStrengthProperty` have units?

- [x] Use `constrainValue` to make the Atom Diameter and Interaction Strength sliders snap in increments of 5 units.

- [x] `atomicInteractionsScreen.model.atomPairProperty` and `atomicInteractionsScreen.model.fixedAtom.atomTypeProperty` should only include the options contained in States of Matter.

- [x] `atomicInteractionsScreen.model.motionPausedProperty` sounds like it's related to the TimeControlNode, but it actually tells you whether or not the unpinned atom is user-controlled. Let's rename it and also clarify its purpose in the documentation. Kathy and I couldn't come up with a name that we loved, but some options include: userMovingAtomProperty, userControlledProperty, userInControlProperty, controllingAtomProperty. Maybe @jbphet will like one of these or have an alternative idea.

- [x] Can `atomicInteractionsScreen.model.fixedAtom.radiusProperty` be read only? Clients shouldn't be changing the size of Neon or Argon, and the Adjustable Interaction option could be changed through `model.adjustableAtomDiameterProperty`.

- [x] `atomicInteractionsScreen.model.fixedAtom.radiusProperty` and `atomicInteractionsScreen.model.movableAtom.radiusProperty` need units.

- [x] `atomicInteractionsScreen.model.fixedAtom` and `atomicInteractionsScreen.model.movableAtom` have an accelerationProperty, positionProperty, and velocityProperty. The values are always 1D, but the data is presented as a 2D vector. Do they need to be 2D, or could we provide just a single number? Additionally, do these values have units, or do they use some sort of model unit?

- [x] The the titles of the sliders in the atomsControlPanel need to be instrumented. It's possible to hide the slider, but not the title. Proposed tree structure
```
atomDiameterSlider/interactionStrengthSlider
   opacityProperty
   pickableProperty
   visibleProperty
   title
      opacityProperty
      pickableProperty
      visibleProperty
      textProperty
   slider
      usual slider stuff
```

- [x] `atomicInteractionsScreen.view.atomsControlPanel.radioButtonsNode` - use the same pattern as the radioButtonGroup on the first two screens.

- [x] `atomicInteractionsScreen.view.handNode`- add linked property to `atomicInteractionsScreen.model.movementHintVisibleProperty`

- [x] The `forcesControlPanel` AccordionBox needs some restructuring. Currently, it looks more like a panel that contains an AccordionBox. Desired tree structure (modeled after `gasProperties.idealScreen.view.particlesAccordionBox`):
```
forcesAccordionBox
    opacityProperty
    pickableProperty
    visibleProperty
   +expandCollapseButton
   +radioButtonGroup
```
- [x] Rename `atomicInteractionsScreen.model.forcesControlPanelExpandedProperty` to `atomicInteractionsScreen.model.forcesExpandedProperty`.

- [x] The zoom buttons in the graph are not at all useful in this sim. We recommend removing them. Relevant phetioIDs: `atomicInteractionsScreen.view.interactiveInteractionPotentialDiagram.gridNode.zoomInButton` and 
`atomicInteractionsScreen.view.interactiveInteractionPotentialDiagram.gridNode.zoomOutButton`. As a side note, it seems strange to us that the zoom buttons were children of the gridNode. For Atomic Interactions, would it be possible for these to be siblings?

- [ ] The tree structure and naming of `atomicInteractionsScreen.view.interactiveInteractionPotentialDiagram` and its contents could be clearer. Proposed tree structure:
```
interactionPotentialGraph
    opacityProperty
    pickableProperty
    visibleProperty
    +gridNode
    -epsilonControl
        opacityProperty
        pickableProperty
        visibleProperty
       +arrowDragHandler
       +lineDragHandler
    -positionMarker
        opacityProperty
        pickableProperty
        visibleProperty
       +dragHandler
    -sigmaControl
        opacityProperty
        pickableProperty
        visibleProperty
       +arrowDragHandler (or perhaps just dragHandler since there's only one)
```

- [x] `atomicInteractionsScreen.view.returnAtomButton` - set the enabledProperty, opacityProperty, pickableProperty, and visibleProperty to phetioReadOnly: true. (Similar to Return Lid button).

**Comment by jbphet** [comment]
@arouinfar asked
 
> Does `atomicInteractionsScreen.model.interactionStrengthProperty` have units?

Please see https://github.com/phetsims/states-of-matter/issues/265#issuecomment-608126340 for an answer to this.

**Comment by jbphet** [comment]
> atomicInteractionsScreen.model.motionPausedProperty sounds like it's related to the TimeControlNode, but it actually tells you whether or not the unpinned atom is user-controlled. Let's rename it and also clarify its purpose in the documentation.

Well, the motion really *is* paused in this case, and there are a lot of other ways to affect this variable, such as changing the atom diameter or interaction strength while the atoms are in motion.  It's a pretty internal sort of model thing - how about we just don't instrument it at all?

**Comment by jbphet** [comment]
> atomicInteractionsScreen.model.fixedAtom and atomicInteractionsScreen.model.movableAtom have an accelerationProperty, positionProperty, and velocityProperty. The values are always 1D, but the data is presented as a 2D vector. Do they need to be 2D, or could we provide just a single number?

They could be a single number, but it's not trivial to change, and vectors are pretty convenient in the code for this sort of thing.  I'd estimate 1.5 hrs to do this.  Is it really worth it?

> Additionally, do these values have units, or do they use some sort of model unit?

I added units for velocity (pm/s) and acceleration (pm/s^2).  I didn't do position, since the positions are relative to the center of the fixed atom's position.  I could just make the units 'pm' if it's helpful to do so.

**Comment by arouinfar** [comment]
>> atomicInteractionsScreen.model.motionPausedProperty sounds like it's related to the TimeControlNode, but it actually tells you whether or not the unpinned atom is user-controlled. Let's rename it and also clarify its purpose in the documentation.
>
>Well, the motion really is paused in this case, and there are a lot of other ways to affect this variable, such as changing the atom diameter or interaction strength while the atoms are in motion. It's a pretty internal sort of model thing. @arouinfar - how about we just don't instrument it at all?

Oh, good point. Yes, let's uninstrument it. I don't think we need to expose it to the client.

>> atomicInteractionsScreen.model.fixedAtom and atomicInteractionsScreen.model.movableAtom have an accelerationProperty, positionProperty, and velocityProperty. The values are always 1D, but the data is presented as a 2D vector. Do they need to be 2D, or could we provide just a single number?
>
>They could be a single number, but it's not trivial to change, and vectors are pretty convenient in the code for this sort of thing. I'd estimate 1.5 hrs to do this. Is it really worth it?

Let's leave them as vectors, then.

>> Additionally, do these values have units, or do they use some sort of model unit?
>
>I added units for velocity (pm/s) and acceleration (pm/s^2). I didn't do position, since the positions are relative to the center of the fixed atom's position. I could just make the units 'pm' if it's helpful to do so.

If the distance between the atoms is in pm, let's display the units of position as pm.

**Comment by jbphet** [comment]
From the original issue description:

> As a side note, it seems strange to us that the zoom buttons were children of the gridNode. For Atomic Interactions, would it be possible for these to be siblings?

Possible yes, but not easy.  The class is called `ZoomableGridNode` and it was created to be a grid with the zooming built in as well as the means to do the zooming.  I could certainly rename it, take the buttons out, make a property that controls the zoom level, add the buttons externally and hook them to this property.  I'd estimate at least a couple of hours to do this and test it.  It sure doesn't feel worth it to me, since I think this is very unlikely to confuse our users, or even get very close scrutiny.  I vote to leave the zoom buttons as children of the grid, but please let me know if you feel it is worth the effort to refactor this.

**Comment by jbphet** [comment]
On `atomicInteractionsScreen.view.interactiveInteractionPotentialDiagram`, I can't consolidate the two nodes that act as epsilon controllers into one node because they are actually created in different places and are on different layers of the scene graph because the line is used in some other places.  I was able to get close to the structure that was specified, so please take a look and let me know whether this will do.  I structured the sigma controller similarly for consistency.

**Comment by jbphet** [comment]
@arouinfar - I think I have addressed everything in the list at the top of this issue with the exceptions noted in the comments.  I think it would be good for you to have a look through it all and make sure I didn't miss or misunderstand anything before getting back together with @kathy-phet for making the "featured" determinations.  You can assign this back to me if changes are needed.

**Comment by arouinfar** [comment]
>> As a side note, it seems strange to us that the zoom buttons were children of the gridNode. For Atomic Interactions, would it be possible for these to be siblings?
>
>Possible yes, but not easy. The class is called ZoomableGridNode and it was created to be a grid with the zooming built in as well as the means to do the zooming. I could certainly rename it, take the buttons out, make a property that controls the zoom level, add the buttons externally and hook them to this property. I'd estimate at least a couple of hours to do this and test it. It sure doesn't feel worth it to me, since I think this is very unlikely to confuse our users, or even get very close scrutiny. I vote to leave the zoom buttons as children of the grid, but please let me know if you feel it is worth the effort to refactor this.

@jbphet let's leave it as-is in Atomic Interactions, then. I don't think it's worth the time investment.

**Comment by arouinfar** [comment]
> The tandem for this screen should match what's in the sim, interactionScreen not atomicInteractionsScreen.

I just noticed that the tandem name was changed to "interactionsScreen", but the screen name in the sim is the singular "Interaction". I've caught myself referring to it as "Interactions" (such as in the title of the issue). Given that the other screen names are plural the Interaction screen's parent sim is "Atomic Interactions", we think we should rename this screen "Interactions".

 > atomicInteractionsScreen.view.atomsControlPanel.radioButtonsNode - use the same pattern as the radioButtonGroup on the first two screens.

It doesn't look like this was done @jbphet. Also, looking at Phase Changes, the "adjustableAtom" should match the string used in the sim, "adjustableAttraction".
| Interaction | Phase Changes |
| --- | --- |
| <img src="https://user-images.githubusercontent.com/8419308/79496809-e8e75580-7fe3-11ea-9025-cdebf8dc2f4a.png" width=250> | <img src="https://user-images.githubusercontent.com/8419308/79497096-601ce980-7fe4-11ea-981c-32d963ea7004.png" width=250> |

> On atomicInteractionsScreen.view.interactiveInteractionPotentialDiagram, I can't consolidate the two nodes that act as epsilon controllers into one node because they are actually created in different places and are on different layers of the scene graph because the line is used in some other places. I was able to get close to the structure that was specified, so please take a look and let me know whether this will do. I structured the sigma controller similarly for consistency

In yesterday's meeting we outlined an alternative tree structure. Some clients may want to hide the sigma and epsilon indicators in the graph (white double-headed arrow and label), so we would like to instrument this as the `diagramLabel`.

If possible, we'd also like to change the name from "interactiveInteractionPotentialDiagram" to "interactivePotentialGraph". This was in the earlier tree outline, but not specifically mentioned.

Also note that all dragHandlers should also be converted to dragListeners as discussed in today's PhET-iO meeting.

```
-interactionPotentialGraph
     opacityProperty
     pickableProperty
     visibleProperty
     -epsilonParameter
         -controlArrow
               opacityProperty
               pickableProperty
               visibleProperty
              +dragListener 
         -controlLine
               opacityProperty
               pickableProperty
               visibleProperty
              +dragListener
         -diagramLabel (includes double headed white arrow & epsilon label)
               opacityProperty
               pickableProperty
               visibleProperty
     +gridNode
     +positionMarker
     -sigmaParameter
         -controlArrow
               opacityProperty
               pickableProperty
               visibleProperty
              +dragListener
         -diagramLabel (includes double headed white arrow & sigma label)
               opacityProperty
               pickableProperty
               visibleProperty
```

**Comment by jbphet** [comment]
@arouinfar said:

> Given that the other screen names are plural the Interaction screen's parent sim is "Atomic Interactions", we think we should rename this screen "Interactions".

This is unfortunately way more tricky than it sounds.  There are a lot of translations for this string, and the key to the string is `interaction`, so I'd need to modify the string key name or add a new one, both of which will break all the existing translations when we publish off of master.  I could do some manipulation of the translation string files to make this all work out, but that process is a bit time consuming and error prone.  Given this situation, I thought I'd at least ask: How important do you think this is?

**Comment by jbphet** [comment]
> If possible, we'd also like to change the name from "interactiveInteractionPotentialDiagram" to "interactivePotentialGraph".

For the sake of consistency, and since I like this convention better anyway, I've gone through the code and renamed everything that included "InteractionPotentialDiagram" to "PotentialGraph", and have updated the comments and variable names as well.

**Comment by jbphet** [comment]
@arouinfar and I just met and made a number of real-time changes, and I followed up with some additional revisions related to the controls on the interaction potential graphs.

@arouinfar - over to you to have a look and let me know if you see anything immediately obvious to revise.  If not, you can meet with @kathy-phet for the next full round of revisions and/or identifying things that are "featured".

**Comment by arouinfar** [comment]
@jbphet the changes on this screen are all looking good. The only exception is the visibleProperty of the epsilonControl.arrow, epsilonControl.line, and sigmaControl.arrow. Selecting Adjustable Attraction will override any changes a client makes to the visibleProperty. See the end of https://github.com/phetsims/states-of-matter/issues/265#issuecomment-622519379

**Comment by jbphet** [comment]
The item noted in the previous comment should now be addressed.  @arouinfar - please have a look at the behavior on master and let me know what you think.

**Comment by arouinfar** [comment]
The discussion related to the interactionPotentialGraph starts in https://github.com/phetsims/states-of-matter/issues/265#issuecomment-626059805

In #272 we discovered a few more (seemingly minor) issues with this screen.

- [ ] `interactionScreen.model.timeControlSpeedProperty` includes an option for "Fast" but that option doesn't exist in this simulation (or Atomic Interactions) and should be removed.

- [ ] `interactionScreen.view.handNode.visibleProperty` and `interactionScreen.model.movementHintVisibleProperty` both hide the hand on the moveable atom, which is a bit odd. This looks like another example of https://github.com/phetsims/phet-io/issues/1642. Since the visibility of the hand is controlled by the model, the view property should be `phetioReadOnly: true`.

**Comment by jbphet** [comment]
@arouinfar - I've made the changes listed in the previous comment based what is written there and the Zoom call that we just had about how to address the visibility of the hand.  Please check it over and let me know if other changes are needed.

**Comment by arouinfar** [comment]
@jbphet this all looks good in master, and the tree structure for the interactivePotentialGraph discussed in https://github.com/phetsims/states-of-matter/issues/265#issuecomment-629423235 also looks good, so I'll close this issue.
