### ISSUE TITLE
use ScreenIcon

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/states-of-matter#267]
Related to https://github.com/phetsims/joist/issues/626

Noticed while doing some work on ColorProfile.  

SOM is not using JOIST/ScreenIcon for its screen icons.  It's currently using Node.

**Comment by pixelzoom** [comment]
The easiest way to address this is to wrap your existing nodes in ScreenIcon. See example in https://github.com/phetsims/number-line-common/issues/1#issuecomment-612168363.

**Comment by jbphet** [comment]
I've ported the programmatically-created icons to extend `ScreenIcon` and used the options to make a white outline appear around the navigation bar icons when in projector mode.  It appears to work very well.  Closing.
