### ISSUE TITLE
use of global in MultipleParticleModelIO

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/states-of-matter#268]
Noticed while working on a common-code issue related to IO Types...

After converting to ES6 modules, using globals in IO Types is not longer necessary or desirable.

```js
MultipleParticleModelIO.validator = { isValidValue: v => v instanceof phet.statesOfMatter.MultipleParticleModel }; 
```

**Comment by jbphet** [comment]
Good to know, thanks.  I changed it to reference an imported module instead, and tested it in the "Studio" and "State" wrappers.  Seems to work fine.  Closing.
