### ISSUE TITLE
Water molecules stop rotating/change direction when adding new molecules. 

### ISSUE THREAD

**Issue by orejolaphet** [phetsims/states-of-matter#27]
Test device: MacBook Pro
Operating System: 10.9.4
Browser: Chrome 39
Problem description: If a few particles are in the container in the "Phase Change" scene, the addition of a more water molecules cause some molecules to stop rotating, and change direction without a collision.

Steps to reproduce:
Select "Phase Change" Scene
Select Water
Push down on lid until a lid explodes
Wait until most of the molecules have escaped the container. With 3-6 left inside hit "Return Lid"
Use the pump to add more molecules (Watch as the remaining rotating particles instantly stop their rotation)

Severity:
High, does not behave physically correct.
Screenshots:
![screen shot 2015-02-03 at 9 55 00 am](https://cloud.githubusercontent.com/assets/5631059/6024777/e4f083c6-ab8a-11e4-9aa1-a84aa3ac3c0a.png)

Troubleshooting information (do not edit):
Name: States of Matter
URL: http://www.colorado.edu/physics/phet/dev/html/states-of-matter/1.0.0-dev.2/states-of-matter_en.html
Version: 1.0.0-dev.2
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.99 Safari/537.36
Language: en-US
Window: 947x571
Pixel Ratio: 1.100000023841858/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 15 uniform: 1024
Texture: size: 8192 imageUnits: 16 (vertex: 16, combined: 16)
Max viewport: 8192x8192
OES_texture_float: true

**Comment by jbphet** [comment]
This can be duplicated on 1.0.0-dev.2 and is also still an issue on the current master branch.  I created a similar condition in the Java sim, and this issue didn't occur, or was at least much less obvious.  

This is almost certainly related to the 'thermostat' code, which adjusts the energy in the various particles in order to keep the overall temperature reasonably stable.

Assigning to @kmsravindra for investigation.

**Comment by notsiddhartha** [comment]
The offset was wrong and the particle direction had to be switched. In the Java version, particles are injected from right to left (negative X direction) while in the HTML5 version they are injected from left to right (positive X direction)

**Comment by notsiddhartha** [comment]
Fixed above. Assigning to @orejolaphet for review

**Comment by notsiddhartha** [comment]
Couldn't assign to @orejolaphet. Assigned to @jbphet

**Comment by jbphet** [comment]
Tested the current version of the master branch, and the problem appears to be resolved.  Closing.
