### ISSUE TITLE
CompositeThermometerNode: opt out of dynamic layout

### ISSUE THREAD

**Issue by arouinfar** [phetsims/states-of-matter#273]
Discovered in #272 

When hiding the ComboBox (`particleContainerNode.compositeThermometerNode.temperatureComboBox.visibleProperty`), the thermometer's position shifts in such a way that it no longer appears to be measuring inside the container. 

![image](https://user-images.githubusercontent.com/8419308/81721787-a9265900-943d-11ea-9094-a1499c4091bd.png)
![image](https://user-images.githubusercontent.com/8419308/81721807-b04d6700-943d-11ea-88bf-56e3fc89394b.png)

This seems related to the support for dynamic layout introduced in https://github.com/phetsims/joist/issues/608. @jbphet can you opt out of this for the CompositeThermomterNode on the States and Phase Changes screens?

**Comment by jbphet** [comment]
I fixed this by setting the resize option to false in the VBox in which the thermometer and the combo box are embedded, and it seemed to do the trick.  @arouinfar - please check on master and close if it looks good to you.

**Comment by arouinfar** [comment]
Looks good in master @jbphet!
