### ISSUE TITLE
Interaction Screen, interaction strength does not change arrows while paused

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/states-of-matter#274]
**Test device**
Dell
**Operating System**
Win 10
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/QA/issues/501.
On the Interaction screen, when looking at the adjustable attraction atoms, the force arrows do not update as you move the interaction strength slider when paused. When moving the atom diameter slider or changing atom types the update does occur. If this is intended please close.

**Steps to reproduce**
1. Go to the Interaction screen
2. Turn on one of he Force arrow options
3. Switch to the adjustable attraction option for atoms
4. Pause the sim
5. Change the interaction strength slider
6. Step sim forward to see change
7. Compare with other methods of changing force.

**Visuals**
![arrowsandinteractionstrength](https://user-images.githubusercontent.com/41024075/81978780-3fe34900-95e9-11ea-9a80-66c66d0e2c4f.gif)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪States of Matter‬
URL: https://phet-dev.colorado.edu/html/states-of-matter/1.2.0-dev.4/phet/states-of-matter_all_phet.html
Version: 1.2.0-dev.4 2020-05-07 23:42:25 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36
Language: en-US
Window: 1536x722
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by loganbraywork** [comment]
When paused, if the atom is switched from Adjustable Attraction, to Neon or Argon, and back to Adjustable Attraction, the force arrows do not return to their normal state until the sim is unpaused. 
![2020-05-18StatesArrows](https://user-images.githubusercontent.com/54685448/82264931-1432cc80-9923-11ea-9ff6-62ccb5407d5b.gif)

**Comment by jbphet** [comment]
@arouinfar and I reviewed this on 5/29/2020 and we decided that it does not need to be fixed for an early customer dev release, but should be addressed before the next major or minor release of this sim.

**Comment by jbphet** [comment]
This was due to an error in the code that I added to make sure the movable atom was still when switching between substances as reported https://github.com/phetsims/states-of-matter/issues/282.  I was setting the attractive and repulsive forces to zero rather than making them equal.  I've fixed that, and it seems to have resolved the problem.

@KatieWoe - please test on master and leave open and unassigned if it seems okay, and we will check it on the next dev release.

**Comment by KatieWoe** [comment]
Looks good on master

**Comment by KatieWoe** [comment]
This looks ok in https://github.com/phetsims/QA/issues/525. Will reopen if something shows up.
