### ISSUE TITLE
White outlines on nav bar icons in projector view

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/states-of-matter#275]
**Test device**
Dell
**Operating System**
Win 10 
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/QA/issues/501. Not in published version.
When the sim is in projector mode, the icons in the nav bar have a white outline around them. Also seen on the home screen (though this is in published).
**Steps to reproduce**
1. Go to the phet menu and select "options"
2. Turn on projector mode

**Visuals**
![whiteoutline](https://user-images.githubusercontent.com/41024075/81980834-92723480-95ec-11ea-971c-736f4a314b08.png)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪States of Matter‬
URL: https://phet-dev.colorado.edu/html/states-of-matter/1.2.0-dev.4/phet/states-of-matter_all_phet.html
Version: 1.2.0-dev.4 2020-05-07 23:42:25 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36
Language: en-US
Window: 1536x722
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by jbphet** [comment]
Impressive - not much gets past you @KatieWoe!  

This change is intentional, and came about as a result of the work done for https://github.com/phetsims/states-of-matter/issues/267.  Closing.
