### ISSUE TITLE
Can't pump particles/too many particles in container

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/states-of-matter#276]
**Test device**
Dell
**Operating System**
Win 10
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/QA/issues/501.
In certain situations you can get the pump so that it appears to have particles, but won't add them. This occurs after you have returned the lid after a full container was blown up. You can get pumping to start by moving the lid slightly. It is also then possible to seemingly get more particles than intended in the container. This aspect doesn't always require the container to have been full before blown up and the lid returned.
**Steps to reproduce**
1. Go to the second screen
2. Pump all particles into container.
3. Lower lid so it blows off
4. Quickly return lid
5. Note particle indicator on pump and how it looks like there are more there than were lost
6. Try to pump particles
7. Lower lid slightly and raise again
8. Pump particles

**Visuals**
https://drive.google.com/file/d/1_NCLcEuhM_YvsMYYlh9CVV4aKVOfg6_S/view?usp=sharing

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪States of Matter‬
URL: https://phet-dev.colorado.edu/html/states-of-matter/1.2.0-dev.4/phet/states-of-matter_all_phet.html
Version: 1.2.0-dev.4 2020-05-07 23:42:25 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36
Language: en-US
Window: 1536x722
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by jbphet** [comment]
@arouinfar and I reviewed this on 5/29/2020 and we decided that it does not need to be fixed for an early customer dev release, but should be addressed before the next major or minor release of this sim.

**Comment by jbphet** [comment]
This should now be fixed.  @KatieWoe and team - please test on master and, if the test passes, leave it unassigned and open so that we can verify again before next publication.

**Comment by KatieWoe** [comment]
That aspect seems fixed. However, it seems that you can now continue dragging down the lid of the container after it is blown off. When you return it, it starts moving down on its own. Doesn't seem to happen with screen recording, so I'm going to try another method and post here. Let me know if it should be a separate issue.

**Comment by KatieWoe** [comment]
![ezgif com-optimize](https://user-images.githubusercontent.com/41024075/84545346-5bab3f00-acbc-11ea-9d80-81fc0c505875.gif)

**Comment by jbphet** [comment]
@KatieWoe - I noticed this too when I was testing and was probably working to fix it at the same time as you were testing it.  Can you please pull again, test, and see if this portion is fixed too?

**Comment by KatieWoe** [comment]
Looks ok on master

**Comment by KatieWoe** [comment]
Just found https://github.com/phetsims/states-of-matter/issues/276#issuecomment-643478845 on master, but when you change scenes, rather than return the lid.
![ezgif com-optimize](https://user-images.githubusercontent.com/41024075/84958688-22f3d700-b0bb-11ea-98a2-3b6d06c87038.gif)

**Comment by jbphet** [comment]
Another good find.  The container height was being reset when the substance was changes, but not the *target* container height.  That has been remedied.  @KatieWoe - please test on master and leave open if it passes so that we can verify on the next release.

**Comment by KatieWoe** [comment]
Looks good on master

**Comment by KatieWoe** [comment]
This seems fixed in https://github.com/phetsims/QA/issues/525. Will reopen if issues show up
