### ISSUE TITLE
phet-io api json 404

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/states-of-matter#280]
For https://github.com/phetsims/QA/issues/501. Found on Win 10 Chrome.
When trying to look at the phet-io api json from the wrapper index you get a 404 error.
![apijsonnotfound](https://user-images.githubusercontent.com/41024075/82252322-0b82cc00-990c-11ea-8cfd-ff7db3e04613.png)

**Comment by jbphet** [comment]
@zepumph and @samreid - Some of the API documentation seems to be missing from a phet-io dev version of SOM that I just published.  Any insights?

**Comment by zepumph** [comment]
Ahh yeah. That makes sense. Over in https://github.com/phetsims/phet-io/issues/1664 we have quite a bit of work to do until we start generating these again on build. This won't be fixed until that is taken care of.

**Comment by zepumph** [comment]
This has been a problem since https://github.com/phetsims/chipper/commit/9f49893cf8070d9c0ee04583006ab028ae52bf59.

**Comment by zepumph** [comment]
On hold until https://github.com/phetsims/phet-io/issues/1664 is sorted out, just like https://github.com/phetsims/states-of-matter/issues/281

**Comment by jbphet** [comment]
The blocking issue cited above is marked as closed, so this one is being re-opened for followup.  @samreid and @zepumph - we need to know if this has to be resolved before doing an early customer dev release.  From the description, it kinda sounds like it does (but it may be done already for all I know).

**Comment by samreid** [comment]
This does not seem critical for a client dev release, but will need to be fixed for an RC or production version.  The blocking issue is https://github.com/phetsims/chipper/issues/940

**Comment by zepumph** [comment]
This is fixed in local builds, as well as in https://phet-dev.colorado.edu/html/gravity-and-orbits/1.2.0-dev.10/phet-io/ (currently being dev tested). I'm going close this issue.
