### ISSUE TITLE
In state wrapper, in launched sim, the lid height isn't recognized

### ISSUE THREAD

**Issue by muedli** [phetsims/states-of-matter#285]
<b>Test Device</b>

Liam's MacBook Air

<b>Operating System</b>

macOS 10.15.4

<b>Browser</b>

Google Chrome 81.0.4044.138

<b>Problem Description</b>

For https://github.com/phetsims/QA/issues/501. In the phase changes screen, if you push the lid down and then launch a fresh copy of the sim, you'll notice that the fresh copy seems to think the lid isn't pushed down. See screenshot below.

<b>Visuals</b>

![issue](https://user-images.githubusercontent.com/60749003/82267245-ff593780-9928-11ea-8957-38f69d659bfc.png)

**Comment by jbphet** [comment]
In this scenario, as soon as the lid is moved the sim adjusts the container height, so it looks like the setting of the state during the launch is the problem.  I've seen this a lot where properties affect one another during setting of phet-io state.

**Comment by jbphet** [comment]
I've made the linkage between the non-normalized container size and the normalized container size a bit more direct, and it seems to have fixed this.

@KatieWoe - please have QA test this on master and, if it's fixed, leave it unassigned and we can re-verify before the next publication.

**Comment by KatieWoe** [comment]
Looks fixed. Great catch by the way @muedli

**Comment by KatieWoe** [comment]
While this looks fixed, it is hard to tell due to https://github.com/phetsims/states-of-matter/issues/311#issuecomment-670605633. Since the particles don't start as a gas, I'd like to leave this until that issue is resolved.

**Comment by jbphet** [comment]
#311 is fixed (I think), I'll leave this open and will put it on the list to verify during the next RC test.

**Comment by KatieWoe** [comment]
Looks ok in rc.2. Will reopen if something shows up.
