### ISSUE TITLE
phet-io.js not password protected

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/states-of-matter#288]
For https://github.com/phetsims/QA/issues/501. Seen on Win 10 Edge.
The phet-io.js minified document in lib is not minified. The lib directory itself is, but the file within it is not. Unsure if this belongs here on in a phet-io repo. Please move if more appropriate elsewhere. When reproducing, use new incognito modes for each tested page, as the password is cached.

**Comment by loganbraywork** [comment]
https://phet-dev.colorado.edu/html/states-of-matter/1.2.0-dev.4/phet-io/lib/phet-io.js appears to not be password protected in Firefox, while https://phet-dev.colorado.edu/html/states-of-matter/1.2.0-dev.4/phet-io/lib is.

**Comment by jbphet** [comment]
@samreid and @zepumph - this seems like it's an issue with the phet-io build process.  I'm passing it over to you, feel free to assign this back to me if it's something specific to States of Matter that I should deal with.

**Comment by zepumph** [comment]
This is expected. This minified library file is needed to run phet-io wrappers. If this file was password protected, every student would need to login to use a wrapper. Instead we keep the lib file and sim public and minified, and then password protect documentation and example wrappers. Over to QA to update the needed QA documentation or to ask questions.

**Comment by KatieWoe** [comment]
Thanks
