### ISSUE TITLE
Interaction Screen Hand in Studio doesn't appear when Launched

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/states-of-matter#289]
For https://github.com/phetsims/QA/issues/501. Seen on Win 10 Edge. 
In studio, if you add the hand that indicates a movable atom in a situation where it would not normally be, then the hand will not appear in the launched version of the sim.
Steps:
1. In studio, go to the Interaction Screen
2. Show All Elements.
3. Move the movable atom and pause it in a new spot
4. Go to interactionScreen, view, handNode, visibleProperty
5. Turn the property on
6. Launch Sim

![handnotthere](https://user-images.githubusercontent.com/41024075/82384995-4c531180-99ee-11ea-82f6-dd081e979c09.gif)

**Comment by jbphet** [comment]
@KatieWoe - I've made the visibleProperty read-only now, and the hint can only be turned on via the model property.  This seems to work okay.  Can you please test on master and verify that this is fixed?

**Comment by KatieWoe** [comment]
Behaves as described by @jbphet in master
