### ISSUE TITLE
Back of container is in front of particles in the z-order

### ISSUE THREAD

**Issue by jbphet** [phetsims/states-of-matter#29]
The z-order layering is not quite correct.  The two screen shots below should make the issue clear.  The first is from the HTML5 version of the sim, the second, which shows the correct layering, is from the Java version.

![som-new](https://cloud.githubusercontent.com/assets/3082831/6084571/4f4c7e8a-adef-11e4-888f-2a0471a8079c.png)

![som-old](https://cloud.githubusercontent.com/assets/3082831/6084573/5681e942-adef-11e4-9af4-40d787eca573.png)

**Comment by ChandrashekarBemagoni** [comment]
Fixed in the above commit. Assigning to @jbphet for verification.

**Comment by jbphet** [comment]
Much better - thanks.  Closing.
