### ISSUE TITLE
No Return Lid Option on States Screen

### ISSUE THREAD

**Issue by JRomero0613** [phetsims/states-of-matter#290]
For https://github.com/phetsims/QA/issues/501 on the States screen there is no option to return the lid if it has been popped off. The lid can be removed by heating the container for a long time, it takes a long time to get it hot enough to remove the lid so it is probably not very common. On the Phase Changes screen there is a return lid option. On the Phase Changes screen it is much more common for the lid to be removed because there are multiple ways to increase the pressure (heat, pump, and pushing the lid down). I'm not sure if this is the intended behavior for the states screen or if the return lid option was overlooked.

**Comment by jbphet** [comment]
This is intentional.  We don't want the user to be able to have less than the full complement of particles on the first screen, so they have to press reset to get the lid back.  Closing.
