### ISSUE TITLE
Pump stops working when no molecules escape after lid returned

### ISSUE THREAD

**Issue by megan-phet** [phetsims/states-of-matter#292]
<b>Test Device</b>
- MacBook Pro

<b>Operating System</b>
- 10.15.4

<b>Browser</b>
- All latest

<b>Problem Description</b>
For https://github.com/phetsims/QA/issues/501
Pump stops working after the lid is returned if all the molecules remain inside.
Even after the reset button is pressed the pump still won't work.

<b>Steps to Reproduce</b>
1. Click on phase change
2. Lower temp
3. Empty pump
4. Click on return lid button right away
5. Lower temp (to see better)
6. Use the pump again
7. Click the reset button
8. Try using the pump

<b>Visuals</b>
![Kapture 2020-05-20 at 15 25 36](https://user-images.githubusercontent.com/40698031/82499069-3e64c580-9aae-11ea-8de5-606c4722ba51.gif)
<b>Continued</b>
![Kapture 2020-05-20 at 15 26 35](https://user-images.githubusercontent.com/40698031/82499145-6b18dd00-9aae-11ea-8807-6e9a1ac521f9.gif)

**Comment by jbphet** [comment]
This should now be fixed.  @KatieWoe and team - please test on master and, if the test passes, leave it unassigned and open so that we can verify again before next publication.

**Comment by KatieWoe** [comment]
It does seem fixed.

**Comment by KatieWoe** [comment]
Looks fixed in https://github.com/phetsims/QA/issues/525. Will reopen if something shows up.
