### ISSUE TITLE
Add support for ?stickyBurners

### ISSUE THREAD

**Issue by arouinfar** [phetsims/states-of-matter#295]
One of the client requests for this sim is the ability to remove the snap-to-zero behavior from the HeaterCoolerNode slider. In EFAC, this was done with the `stickyBurners` query parameter.

@jbphet can you add support for this query parameter in SOM?

**Comment by jbphet** [comment]
Support added.  @arouinfar - please try it out and close if you approve, or mark as fixed and unassign and we can have QA verify during the next dev release if you like.

**Comment by arouinfar** [comment]
@jbphet looks great in master. I think we can go ahead and close.
