### ISSUE TITLE
publish PhET-iO dev versions for the client

### ISSUE THREAD

**Issue by jbphet** [phetsims/states-of-matter#296]
@kathy-phet would like to deliver PhET-iO dev versions of both states-of-matter and states-of-matter-basics to the client for review.

**Comment by jbphet** [comment]
During the 6/4/2020 phet-io meeting we reviewed a list of phet-io issues that could potentially block the sharing of dev version.  @zepumph said he'd add them to this issue.

**Comment by zepumph** [comment]
Yes thanks. The outline for this issue is as follows (largely copied from https://github.com/phetsims/ph-scale/issues/164#issue-601237331):


the process is:

1. Determine what sim specific issues need to be done before publishing the dev version.
1. sign off on open issues labeled "status:blocks-publication". We did this as a group today. 
  * Here is the list of issues that need to be done for this dev release:
	- [ ] https://github.com/phetsims/states-of-matter/issues/281
	- [ ] https://github.com/phetsims/studio/issues/30
	- [ ] (in review) https://github.com/phetsims/studio/issues/22
	- [ ] (in review) https://github.com/phetsims/studio/issues/14
	- [ ] (in review) https://github.com/phetsims/scenery/issues/490
  * Here is the list of issues that are currently marked as "status:blocks-publication" but don't need to be done for this dev version:
	- [x] https://github.com/phetsims/phet-io/issues/1671
	- [x] https://github.com/phetsims/chipper/issues/940
	- [x] https://github.com/phetsims/studio/issues/119
	- [x] https://github.com/phetsims/phet-io-wrappers/issues/342
	- [x] https://github.com/phetsims/studio/issues/40
	- [x] https://github.com/phetsims/studio/issues/37
	- [x] https://github.com/phetsims/studio/issues/85
	- [x] https://github.com/phetsims/studio/issues/28
	- [x] https://github.com/phetsims/studio/issues/18
2. @jbphet : publish dev versions, add links to this issue
3. @arouinfar : review and sign off
4. @kathy-phet: delivery to the client


also see https://github.com/phetsims/phet-io/issues/1680 for central documentation that will be created for this process.

**Comment by jbphet** [comment]
There are also 3 SOM-specific issues that need to be resolved:

[ ] - https://github.com/phetsims/states-of-matter/issues/256
[ ] - https://github.com/phetsims/states-of-matter/issues/287
[ ] - https://github.com/phetsims/states-of-matter/issues/295

**Comment by jbphet** [comment]
Update
--------

As of this writing, there is one blocking issue listed above, and it's https://github.com/phetsims/studio/issues/30.  This is in turn waiting on the completion of QA testing in https://github.com/phetsims/QA/issues/508.  I just checked in with @zepumph via Slack, and he said that once that testing is complete, assuming no major problems are found, we should be clear to move forward with a dev release to the customer.

I also checked in with @arouinfar as to whether she would want to review the studio tree once the studio code had been updated, given that there has been a fair amount of change both the SOM and the studio code.  She said that yes, she would.

**Comment by zepumph** [comment]
That all sounds great. I also want to add that when you are getting ready for another dev version, @zepumph and @arouinfar should look through the issues that came out of https://github.com/phetsims/QA/issues/508 to see if any should block this dev version.

**Comment by arouinfar** [comment]
@jbphet I spent quite a bit of time reviewing master in studio, and aside from the issues mentioned in https://github.com/phetsims/studio/issues/28#issuecomment-648254742 and https://github.com/phetsims/studio/issues/28#issuecomment-648286832 the tree looked undisturbed to me. I don't think this should block dev delivery to the client, however.

**Comment by jbphet** [comment]
Two more issues came up during testing that I think should be resolved before release:

- [ ] https://github.com/phetsims/studio/issues/149
- [ ] https://github.com/phetsims/states-of-matter/issues/300

**Comment by jbphet** [comment]
Though not strictly blocking, I decided to address this one too:

- [ ] https://github.com/phetsims/states-of-matter/issues/301

**Comment by zepumph** [comment]
@chrisklus and @arouinfar will work on getting the client guide for SOM built with the sim, and then this dev version is ready to publish.

**Comment by jbphet** [comment]
@chrisklus and @arouinfar have confirmed that they have made the necessary commits for the client guide.  I just did a local build and reviewed the client guide with @arouinfar and didn't see any dev-version-blocking problems.

**Comment by jbphet** [comment]
I've built and sanity tested dev versions.  Here are the links (password required):

- https://phet-dev.colorado.edu/html/states-of-matter-basics/1.2.0-dev.1/phet-io/
- https://phet-dev.colorado.edu/html/states-of-matter/1.2.0-dev.7/phet-io/

I'll leave this issue assigned to myself until I hear that these have been delivered and will update then.

**Comment by jbphet** [comment]
I wanted to note that in today's status meeting we decided that enough testing had been done on this and there was not a need to set up QA tasks to test these dev versions.

**Comment by kathy-phet** [comment]
Delivered!

**Comment by jbphet** [comment]
This is done.  I will follow up on some other items that still need to be done in order to call the phet-io instrumentation effort complete, but that will be tracked in https://github.com/phetsims/states-of-matter/issues/245, so I'll close this one.
