### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by jbphet** [phetsims/states-of-matter#30]
The first round of dev testing is complete and the issues found have been addressed.  Time for the code review.

**Comment by jbphet** [comment]
Below is the code review checklist, which will be used to guide the remainder of the code review:

PhET code-review checklist
=============

**Build and Run Checks**

- [ ] Does the sim pass jshint?
- [ ] Does the sim build without errors?
- [ ] Does the sim start up? (requirejs and built versions)
- [ ] Does the sim experience any assertion failures? (run with query parameter 'ea')
- [ ] Does the sim pass a scenery fuzzer test? (run with query parameter 'fuzzMouse')
- [ ] Are there any strings that are not being internationalized? (run with query parameter 'stringTest=x', you should see nothing but 'x' strings)
- [ ] Does the sim layout gracefully handle internationalized strings that are twice as long as the English strings? (run with query parameter 'stringTest=double') 

**Repository structure**

- [ ] Are all required files and directories present?

      For a sim repository named “my-repo”, the general structure should look like this (where audio/ or images/ may be omitted if the sim doesn’t have those types of assets).

   ```js
my-repo/
	assets/
		my-repo-screenshot.png
	audio/
		license.txt
	doc/
		model.md
		implementation-notes.md
	images/
		license.txt
	js/
		my-repo-config.js
		my-repo-main.js
		version.js
	strings/
		my-repo-strings_en.json
	.gitignore
	my-repo_en.html
	Gruntfile.js
	LICENSE
	package.json
	README.md
```

   For a common-code repository, the structure is similar, but some of the files and directories may not be present if the repo doesn’t have audio, images, strings, or a demo application.

- [ ] Is the js/ directory properly structured? 

      All JavaScript source should be in the js/ directory. There should be a subdirectory for each screen (this also applies for single-screen sims).  For a multi-screen sim, code shared by 2 or more screens should be in a js/common/ subdirectory. Model and view code should be in model/ and view/ subdirectories for each screen and common/.  For example, for a sim with screens “Introduction” and “Custom”, the general directory structure should look like this:

   ```js
my-repo/js/
	common/
		model/
		view/
custom
		model/
		view/
	introduction
		model/
		view/
my-repo-config.js
	my-repo-main.js
	version.js
 ```

- [ ] Is there a file in assets/ for every file in audio/ and images/?
- [ ] Are all license.txt files populated? audio/license.txt and images/license.txt should enumerate all files in those directories. For the format of license.txt files, go [here](https://github.com/phetsims/simula-rasa/blob/master/images/README.txt).
- [ ] Does the README.md format and content match PhET guidelines? Was it generated by `grunt generate-published-README.md`?
- [ ] Does Gruntfile.js point to `chipper/js/grunt/Gruntfile.js`?
- [ ] Are dependencies in package.json the same as version/*-config.js? Do they match what is actually used by the sim? (ie, no missing dependencies, no unused dependencies)
- [ ] Is the version identifier in package.json the same as js/version.js?
- [ ] Is the LICENSE file correct? (Generally GPL v3 for sims, MIT for common code, but there are exceptions to this.)
- [ ] Does .gitignore match other repositories?
- [ ] Does *-main.js follow PhET conventions? Does it contain correct credits (options.credits passed to Sim constructor)?
- [ ] Is the format of assets/*-screenshot.png correct? (2048x1344, PNG, 32-bit color) Has the browser chrome been stripped off of the screenshot?
- [ ] Are there git repository branches that are no longer used and should be pruned?

**Coding conventions**

- [ ] Does the code style meet PhET's code-style guidelines, as described in the [“Coding Style Guidelines” section of "PhET Development Overview"](https://docs.google.com/document/d/1odXkliRagq0zuf1_NdOtQ2BrkC9hwlISnPi2y-dKdrk/edit#heading=h.1oxr3ptyo50w)?
- [ ] Is the code formatted according to PhET conventions? See [phet-idea-code-style.xml](https://github.com/phetsims/joist/blob/master/util/phet-idea-codestyle.xml) for IntelliJ IDEA code style.

**Documentation**

- [ ] Are documentation conventions followed, as described in the [“Coding Style Guidelines” section of the PhET Development Overview](https://docs.google.com/document/d/1odXkliRagq0zuf1_NdOtQ2BrkC9hwlISnPi2y-dKdrk/edit#heading=h.1oxr3ptyo50w)?
- [ ] Does model.md adequately describe the model, in terms appropriate for teachers?
- [ ] Does implementation-notes.md adequately describe the implementation, with an overview that will be useful to future maintainers?
- [ ] Are sim-specific query parameters (if any) identified and documented in one location?

**Organization, Readability, Maintainability**

- [ ] Does the organization and structure of the code make sense? Do the model and view contain types that you would expect (or guess!) by looking at the sim? Do the names of things correspond to the names that you see in the user interface?
- [ ] Are appropriate design patterns used?
- [ ] Is inheritance used where appropriate? Does the type hierarchy make sense?
- [ ] Is there any unnecessary coupling? (e.g., by passing large objects to constructors, or exposing unnecessary properties/functions)
- [ ] Are the source files reasonable in size? Scrutinize large files with too many responsibilities - can responsibilities be broken into smaller delegates?
- [ ] Are any significant chunks of code duplicated?
- [ ] Is there anything that should be generalized and migrated to common code?

**Performance, Usability**

- [ ] Does the sim perform as desired across the range of supported platforms? (eg, not too slow on slow platforms, not too fast on fast platforms) 
- [ ] If the sim uses WebGL, does it have a fallback? Does the fallback perform reasonably well? (run with query parameter 'webgl=false')
- [ ] Are UI components sufficiently responsive? (especially continuous UI components, such as sliders)
- [ ] Are pointer areas optimized, especially for touch? (run with query parameter 'showPointerAreas')
- [ ] Do pointer areas overlap? (run with query parameter 'showPointerAreas')

**Memory Leaks**

- [ ] Does a heap comparison using Chrome Developer Tools indicate a memory leak? (Describing this process is beyond the scope of this document.)
- [ ] Are there any leaks due to registration of AXON observers? 
	- [ ] For each call to Property.link or PropertySet.link, is there a corresponding unlink, or documentation about why an unlink is unnecessary?
	- [ ] For each DerivedProperty or Multilink created, is there a corresponding detach, or documentation about why a detach is unnecessary?
	- [ ] For each common-code component (sun, scenery-phet, vegas, …) that opaquely registers an AXON observer, is there a call to that component’s dispose function, or documentation about why dispose is unnecessary?
- [ ] Are there any leaks due to registration of components with TOGETHER? `together.addComponent` should be accompanied by `together.removeComponent` or documented why removeComponent is unnecessary.

**Comment by jbphet** [comment]
On 10/20/2016, it was decided that I should do another final pass through this sim to clean up the code before publication.  It's getting close, so I'm reassigning the issue to myself.

**Comment by ariel-phet** [comment]
Sim is published, closing
