### ISSUE TITLE
Interaction scene pause button doesn't reset

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/states-of-matter#300]
For https://github.com/phetsims/QA/issues/508, but reproduced on https://github.com/phetsims/QA/issues/501. Not in published. Win 10 Edge.
When you pause the sim in the interaction screen, hitting the reset all button does not un-pause it. This occurs regardless of any other changes (though the other changes do seem to reset. Other screens do not seem impacted.
![pausedoesntreset](https://user-images.githubusercontent.com/41024075/85453422-11964900-b559-11ea-8a86-cf261175fcd4.gif)

**Comment by zepumph** [comment]
I think this one is sim-specific, over to you @jbphet.

**Comment by jbphet** [comment]
Should be fixed now.  @KatieWoe, please verify on master and leave open for next round of pre-release testing.

**Comment by KatieWoe** [comment]
Looks good on master

**Comment by KatieWoe** [comment]
Looks good in https://github.com/phetsims/QA/issues/525. Will reopen if something shows up.
