### ISSUE TITLE
Atoms panel title is not instrumented

### ISSUE THREAD

**Issue by arouinfar** [phetsims/states-of-matter#301]
Noticed during review for #296 and https://github.com/phetsims/phet-io-client-guides/issues/5

The `Atoms & Molecules` panel title is editable on the first two screens.
* `statesOfMatter.statesScreen.view.moleculesControlPanel.title.textProperty`
* `statesOfMatter.phaseChangesScreen.view.moleculesControlPanel.title.textProperty`

The equivalent `Atoms` panel on the Interaction screen does not have its title instrumented.
![image](https://user-images.githubusercontent.com/8419308/85633959-9788c180-b637-11ea-993f-d64514c77212.png)

@jbphet this seems like an oversight to me. Can you instrument the panel title? The client does not plan to use the Interaction screen, so I'll leave it up to you to decide whether or not to include this change in the upcoming dev release.

**Comment by jbphet** [comment]
'Twas indeed an oversight.  I instrumented it and added dynamic layout.  @arouinfar - please check on master and close if it looks good.

**Comment by arouinfar** [comment]
Thanks @jbphet! Looks good in master.
