### ISSUE TITLE
Projector mode broken?

### ISSUE THREAD

**Issue by zepumph** [phetsims/states-of-matter#302]
While working on a separate issue, I noticed that on master, SOM's options dialog checkbox for toggling to projector mode seems to broken. Assigning to @jbphet  with a high priority due to soon-to-come release.

**Comment by jbphet** [comment]
@zepumph - Can you please elaborate on what you're seeing that is leading you to believe that it's broken?  For the most part, it seems fine to me.  If you're saying this because the appearance of the home screen doesn't change, that's just the way it works.

**Comment by zepumph** [comment]
Ahh shoot. Indeed it was because I only tried the home screen. Thanks for catching me up.
