### ISSUE TITLE
Convert from inherit to class

### ISSUE THREAD

**Issue by samreid** [phetsims/states-of-matter#304]
During https://github.com/phetsims/states-of-matter/issues/299 I noticed the simulations have 42+ usages of `inherit` instead of `class`.  I didn't see another issue for this.

**Comment by jbphet** [comment]
I believe this is covered under https://github.com/phetsims/phet-core/issues/82.

Regardless, I'm going to defer this for now and ask at the next dev meeting about whether converting this and other sims from inherit to class is a priority.

**Comment by jbphet** [comment]
We discussed this issue as well as the general idea of migrating all files from `inherit` to `class` in today's developer meeting and decide to move forward with converting SOM, but not to proactively convert other sims.  Un-deferring.

**Comment by jbphet** [comment]
This has been done, and there are no more usages of the `inherit` function in states-of-matter, states-of-matter-basics, and atomic-interactions.  Closing.
