### ISSUE TITLE
Use non-deprecated input listeners

### ISSUE THREAD

**Issue by samreid** [phetsims/states-of-matter#305]
From review in https://github.com/phetsims/states-of-matter/issues/299, I noticed the following deprecation warnings when running with `&deprecationWarnings`.

```
Deprecation warning: ButtonListener is deprecated, please use FireListener instead
Deprecation warning: DownUpListener is deprecated, please use PressListener instead
```

The deprecated types have different PhET-iO APIs and hence should not be used for the RC and release.

**Comment by jbphet** [comment]
The offending listeners have been replaced and the deprecation warnings are no longer appearing when using the flag.  Closing.
