### ISSUE TITLE
Should temperature change when lid is blown off

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/states-of-matter#308]
For https://github.com/phetsims/QA/issues/508. Looks like it happens in published, but easier to see with studio. Seems to be SoM related, rather than studio.
When the lid is blown off on the first screen, you can continue to add/remove heat. According to the Studio element `statesOfMatter.statesScreen.model.temperatureInKelvinProperty` the temperature changes accordingly, but the molecules do not seem to change behavior. I thought that no heat was meant to be moved after the lid is blown off, but the changing temperature element makes me question that. And it also occurred to me that we may want to disable adding/removing heat if we don't want temp changes in this state.
Steps:
1. Go to the first screen
2. Heat the molecules until the lid flies off
3. Hit the solid button.
4. Look at the element `statesOfMatter.statesScreen.model.temperatureInKelvinProperty`
5. Start adding heat

![notempchange](https://user-images.githubusercontent.com/41024075/86269966-bdf2b380-bb87-11ea-928e-9ff21d7c814c.gif)

**Comment by KatieWoe** [comment]
Can't be reproduced in the second screen as the heat bucket is disabled when the lid blows off there.

**Comment by jbphet** [comment]
I ended up making several modifications for this, so @KatieWoe - please test the new behavior on master fairly thoroughly.  Here's what has changed:

- The heater cooler node now becomes disabled on the "States" screen when the container explodes
- The heater cooler output is set to zero (no heating or cooling) when the container explodes.  This mostly matters (I think) if the `stickyBurners` query parameter is being used
- The phase buttons become disabled when the container explodes

**Comment by KatieWoe** [comment]
Things look ok from what I can see on the States screen. Do you want me to check the other screen too @jbphet?

**Comment by jbphet** [comment]
@KatieWoe - I don't think it needs to be tested on the other screen just yet.  Let's leave it open and unassigned, and have it on the list to check during the upcoming RC.

**Comment by KatieWoe** [comment]
This seems to be working as expected in https://github.com/phetsims/QA/issues/525. Will reopen if something comes up.
