### ISSUE TITLE
potential infinite loop in AtomicInteractionsControlPanel

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/states-of-matter#309]
Noted while working on https://github.com/phetsims/natural-selection/issues/118.  

This is a potential infinite loop in AtomicInteractionsControlPanel.js:

```
  // Keep the title node centered if its bounds change (which can only be done through phet-io).
    titleNode.boundsProperty.link( () => {
      titleNode.centerX = radioButtonPanel.centerX;
      titleNode.bottom = radioButtonPanel.top + 5; // empirically determined to overlap reasonably well
    } );
```

When `titleNode.centerX` and `titleNode.bottom` are set, that changes `titelNode.bounds`.  The solution is to observe `titleNode.localBoundsProperty`.

**Comment by jbphet** [comment]
Thanks for pointing this out.  I've change the code to monitor local bounds instead, and tested it in Studio.  Closing.
