### ISSUE TITLE
Temperature updates don't work initially when launched from Studio

### ISSUE THREAD

**Issue by jbphet** [phetsims/states-of-matter#311]
This issue was reported by a customer using phet-io version 1.2.0-dev.7, see https://phet-dev.colorado.edu/html/states-of-matter/1.2.0-dev.7/phet-io/.

When launching from studio, temperature changes made via the heater-cooler node in both the "States" and "Phase Changes" screens don't work.  The thermometer will indicate a temperature change, but it won't be reflected in the motion of the particles.

**Comment by jbphet** [comment]
This problem was due to the thermostats (isokinetic and Andersen) having local references to the molecule data set that weren't being updated when the state was being set.  As a result, they were increasing the velocities of their own local versions of the data, but that was not being reflected in the motion of the visible particles.

I've implemented a fix that explicitly updates the data used by the thermostats when a phet-io state set operation occurs, but it feels a bit klunky to me, so I'm going to try making the data set a property, which will eliminate the need for such updates.

**Comment by jbphet** [comment]
With help from @zepumph I have modified the deserialization process to update the molecule data set rather than create a new reference.  This prevents having to explicitly update the thermostats, and thus seems a lot cleaner.  This is implemented and tested locally.  I'll close this and provide a new dev version to the customer.

**Comment by jbphet** [comment]
On second thought, I'll leave it unassigned but open so that it is tested during the RC process.

**Comment by jbphet** [comment]
A dev version with the fix has been published at https://phet-dev.colorado.edu/html/states-of-matter/1.2.0-dev.8.

**Comment by KatieWoe** [comment]
While the described bug seems fixed, it seems that the molecules now always start in a solid or liquid state, even when launched as a gas. Adding a bit of heat (or taking a bit of heat) caused it to jump into gas state. The temperature does seem to be in the right state so far.
![startassolid](https://user-images.githubusercontent.com/41024075/89667804-fc237700-d899-11ea-8afa-e864ff513c93.gif)

**Comment by jbphet** [comment]
Nice catch.  It looks like I missed adding serialization and deserialization of the state of the two thermostats that are used to adjust and maintain the temperature.  This has been added.

@KatieWoe - please test on master, record the results, and assign back to me.  If all looks good, I'll cherry pick the commit into the release branch for the next RC.

**Comment by KatieWoe** [comment]
Things are looking good on master from what I can tell. Tried a few molecule types and solid, liquid, and gas.

**Comment by jbphet** [comment]
The commit for this has been added to the 1.2 branch.

**Comment by KatieWoe** [comment]
This does seem to be fixed in rc.2. Will reopen if something shows up.
