### ISSUE TITLE
PressListener is Tandem.REQUIRED

### ISSUE THREAD

**Issue by zepumph** [phetsims/states-of-matter#312]
After fixing the assertion for supplying required tandems over in https://github.com/phetsims/tandem/issues/192, there were some unsuppied PressListeners in this sim and atomic interactions that were failing over in https://github.com/phetsims/phet-io-wrappers/issues/356.

Since these uninstrumented PressListeners were next to other instrumented code, I assume that it was a design decision, and passed through `Tandem.OPT_OUT` to accomplish this, but I want the lead dev to double check. It would be most complete under current protocol to instrument Tandem.REQUIRED instances unless there was a specific reason not to.

Commits coming imminently.

**Comment by zepumph** [comment]
After discussing with @samreid, we are ambivalent about which way to recommend:

1. Leave it the way of the above commit by using Tandem.OPT_OUT
2. Instrument them for completeness.

The benefit of (2) will be that this highlighting will end up in the data stream, and could be useful. It also could be an example of over-instrumentation. We will leave it up to @jbphet as to what he thinks is best.

**Comment by zepumph** [comment]
Wait! We changed our minds. We see that PressListener only adds events to the data stream for press and release, thus, instrumenting these listeners wouldn't do anything for PhET-iO. With this in mind, we recommend option (1) from above. Please review and feel free to close.

**Comment by jbphet** [comment]
> Since these uninstrumented PressListeners were next to other instrumented code, I assume that it was a design decision...

Precisely - it was definitely intentional not to instrument these.  I'm on board with what has been done, and like the idea of having a clear `OPT_OUT` setting.  Seems like we're in good shape here.  Closing.
