### ISSUE TITLE
Lid is not restored to max height if sim is paused while substance is changed

### ISSUE THREAD

**Issue by phet-steele** [phetsims/states-of-matter#314]
1. Phase Changes screen
2. Start on any atom/molecule
3. Move the lid down by any desired amount (don't explode the lid)
4. Pause the sim
5. Switch to any atom/molecule OTHER THAN oxygen (why this doesn't break with oxygen is a mystery to me)

The lid height will change after the substance change, but will not be at the correct (max) height. If oxygen is selected in step 5, the height will correctly be at the max height (verified with phet-io event logs). Stepping the sim, or even switching to a different substance a second time, will move the lid to the correct height.

I'm pretty sure this is related to changes made in #276, but I'm not sure.

Seen on Win 10 Chrome 84.0.4147.89. For phetsims/QA/issues/525.

<details>
<summary>Troubleshooting Information</summary>

Name: ‪States of Matter‬
URL: https://phet-dev.colorado.edu/html/states-of-matter/1.2.0-rc.1/phet/states-of-matter_all_phet.html
Version: 1.2.0-rc.1 2020-07-31 21:24:36 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36
Language: en-US
Window: 1920x937
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4095
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
</details>

**Comment by muedli** [comment]
Gif:
![issue](https://user-images.githubusercontent.com/60749003/89250108-3f979000-d5d1-11ea-9212-9cdbd5c1eb32.gif)

**Comment by jbphet** [comment]
@phet-steele and/or @muedli - Can you please verify that this is fixed on master, do a bit of additional regression testing on potentially related functionality, and then assign back to me?  It's in a bit of a touchy area of the code, so I'd like it tested before I propagate the fix to the release branch.

**Comment by muedli** [comment]
Looks good on master.

**Comment by jbphet** [comment]
Cool.  This will be on the list to verify on the next RC.

**Comment by jbphet** [comment]
The commit for this has been added to the 1.2 branch.

**Comment by phet-steele** [comment]
Looks good for phetsims/QA/issues/531
