### ISSUE TITLE
[Featured display] Search will not search for unfeatured parents

### ISSUE THREAD

**Issue by jbphet** [phetsims/states-of-matter#315]
See https://github.com/phetsims/studio/issues/175.

I'm logging this as a potentially blocking common-code issue, but there is some discussion about whether it really *is* a blocking issue.  I'll update once that's sorted out.

**Comment by jbphet** [comment]
For reference, the test I use to demonstrate this issue, and which manifests the problematic behavior on the 1.2.0-rc.1 release, is to search for the phetioID `statesOfMatter.phaseChangesScreen.view.particleContainerNode`.  This node is not featured, but many of its subcomponents are.  In Studio, when using the 1.2.0-rc.1 release and with filtering set to "Featured", the first ID to appear is `statesOfMatter.phaseChangesScreen.model.temperatureInKelvinProperty`, which seems super weird, but I think it's because it is the first featured ID under `particleContainerNode` and it is one of those linked properties (I forget the exact term).

**Comment by jbphet** [comment]
I have branched the Studio repo and cherry-picked the commits listed in https://github.com/phetsims/studio/issues/175#issuecomment-673713352.  I also updated the dependency in the 1.2 branch.

While testing locally on the 1.2 branch, searching on `statesOfMatter.phaseChangesScreen.view.particleContainerNode` takes me right to that ID, so it looks like the feature is working as we have collectively decided it should.

**Comment by jbphet** [comment]
The dependency for Studio has now been updated in states-of-matter-basics and atomic-interactions too.  The latter isn't strictly needed, since we are not releasing a phet-io version of it, but I thought it would be good to have all three variants as consistent as possible and it might make it easier in the future to release AI with phet-io off of this branch.

**Comment by KatieWoe** [comment]
This looks ok in rc.2. Will reopen if something shows up. Thanks @jbphet for clarifying things in this issue.
