### ISSUE TITLE
Temperature drop down can cover pressure valve if long enough

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/states-of-matter#316]
**Test device**
Dell
**Operating System**
Win 10
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/QA/issues/525. Doesn't seem to happen in published version. This is unlikely to come up in the actual sim, so it may be fine to pass on.
If stringTest=long, then the temperature drop down on the second screen overlaps and partially covers the pressure gauge.

**Visuals**
![longoverlappressure](https://user-images.githubusercontent.com/41024075/89462078-248c6380-d72a-11ea-8407-294ebf9e3f38.png)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: 12345678901234567890123456789012345678901234567890
URL: https://phet-dev.colorado.edu/html/states-of-matter/1.2.0-rc.1/phet/states-of-matter_all_phet.html?stringTest=long
Version: 1.2.0-rc.1 2020-07-31 21:24:36 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36
Language: en-US
Window: 1536x722
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by jbphet** [comment]
>  This is unlikely to come up in the actual sim, so it may be fine to pass on.

I'm going to pass on this one.  It would only come up if some translation had a super long string to indicate degrees in Celsius or Kelvin, which seems extremely unlikely.
