### ISSUE TITLE
Finger and lid movement are incorrect when compressing the container

### ISSUE THREAD

**Issue by jbphet** [phetsims/states-of-matter#32]
On the "Phase Changes" screen, if the finger or lid is grabbed and dragged downward, the finger and lid only move when being dragged.  In the original version of the simulation, the finger and lid would be limited in how fast they move, but would eventually "catch up" to the end drag location.  The HTML5 version needs to match this behavior.

Also, and possibly related, I noticed that when dragging the finger and lid *up* after dragging down, they often get jittery, i.e. they don't move smoothly.

This issue exists on http://www.colorado.edu/physics/phet/dev/html/states-of-matter/1.0.0-dev.2/states-of-matter_en.html and on the current master branch.

**Comment by ChandrashekarBemagoni** [comment]
https://github.com/phetsims/states-of-matter/commit/2bf413fcda511b264baaa7fa8a0836842dc5388f

**Comment by ChandrashekarBemagoni** [comment]
Fixed in above commit. Assinging to @jbphet  for verification

**Comment by jbphet** [comment]
This is better, but the use can move it much faster than in the original sim.  I recall that we wanted to avoid making the motion too quick because it makes it easy to cause the container to explode, and kids tend to fixate on that.  I am assigning this back to @ChandrashekarBemagoni to make the max rate of lid motion more quickly match that of the original Java sim.

**Comment by ChandrashekarBemagoni** [comment]
Fixed in above commit.Assigning to @jbphet  for verification

**Comment by jbphet** [comment]
Looks good, closing.
