### ISSUE TITLE
X button on dialog may have too small pointer area

### ISSUE THREAD

**Issue by jbphet** [phetsims/states-of-matter#320]
See https://github.com/phetsims/sun/issues/610.  More specifically, [this comment](https://github.com/phetsims/sun/issues/610#issuecomment-671525020) provides details about which commit(s) should be cherry-picked to the RC branch.

**Comment by jbphet** [comment]
@pixelzoom has reported merge issues when trying to cherry-pick related commits into the release branch for ph-scale.  It may be necessary to make the modifications manually.

**Comment by jbphet** [comment]
I have done the branch-and-cherry-pick-and-update-dependencies thing in order to pick up this change.  It makes the X bigger, but doesn't expand the touch area beyond that of the X.  Hopefully that will be sufficient.  Marking as unassigned, will test in next RC.

**Comment by pixelzoom** [comment]
>  It makes the X bigger, but doesn't expand the touch area beyond that of the X.

That's because we decided to remove the default touchArea dilations in Dialog. See https://github.com/phetsims/sun/commit/b5758238b2273a032d392029d2c6895989fc300c.

**Comment by pixelzoom** [comment]
>  It makes the X bigger, but doesn't expand the touch area beyond that of the X.

That's because we decided to remove the default touchArea dilations in Dialog. See https://github.com/phetsims/sun/issues/610#issuecomment-668282345 and https://github.com/phetsims/sun/commit/b5758238b2273a032d392029d2c6895989fc300c.

**Comment by KatieWoe** [comment]
This looks done. Will reopen if issues show up.
