### ISSUE TITLE
On my iPad, studio loads with extra space at the top

### ISSUE THREAD

**Issue by muedli** [phetsims/states-of-matter#321]
<b>Test Device</b>

A1670 iPad Pro

<b>Operating System</b>

iPadOS 13.5.1

<b>Browser</b>

Safari 13.1.1

<b>Problem Description</b>

For https://github.com/phetsims/QA/issues/525. Not exactly a showstopper, but when studio loads there's extra space at the top. See screenshot below. It's pretty easy to resize the screen and make this go away.

<b>Visuals</b>

![issue](https://user-images.githubusercontent.com/60749003/89833594-8a0f9400-db1e-11ea-82f2-0cfe4dff42cf.PNG)

**Comment by jbphet** [comment]
I checked in with the phet-io team on Slack about whether Studio is intended to be supported on iOS.  Here are the responses:

> @jbphet  10:16 AM
> An issue was logged on SOM about how Studio loads on an iPad.  I know there has been some discussion on this, but do we support Studio on iPad?  If so, to whom should I assign this issue?
> @samreid  10:20 AM
> Studio isn’t designed to run on iPad
> @pixelzoom   10:20 AM
> My recommendation whenever this comes up is that Studio shouldn't be supported on iPad. It's not a good experience for instructional designers.
> 10:22
> More generally... At last week's (?) phet-io meeting, @KatieWoe asked about which wrappers are supported on which platforms.  I don't recall the answer or where that info might be captured.
> @KatieWoe  10:36 AM
> Studio isn't supported on iPad. The test matrix for phet-io lists the wrappers we don't test on iPad.

Based on this input, I'm closing this issue.
