### ISSUE TITLE
State wrapper launched particles move when upstream sim particles are static

### ISSUE THREAD

**Issue by muedli** [phetsims/states-of-matter#322]
<b>Test Device</b>

MacBook Air

<b>Operating System</b>

macOS 10.15.5

<b>Browser</b>

Firefox 79.0

<b>Problem Description</b>

For https://github.com/phetsims/QA/issues/525. Possibly related to https://github.com/phetsims/states-of-matter/issues/287. I'm pretty sure this is platform-independent. In the state wrapper, if you launch the sim where the particles aren't moving, that is, the temperature is 0 K, the launched sim's particles will be jiggling like they're above 0 K, and they'll have some upward momentum.

<b>Visuals</b>

Interactable Sim:
![og-sim](https://user-images.githubusercontent.com/60749003/89837970-4705ee80-db27-11ea-8153-e76111d57a9d.png)

Launched Sim:
![issue](https://user-images.githubusercontent.com/60749003/89837976-4b320c00-db27-11ea-91c4-300135050b59.gif)

**Comment by jbphet** [comment]
I just tried to duplicate this on the current 1.2 branch, and the problem no longer occurs.  I believe that it was fixed by the work that was done for https://github.com/phetsims/states-of-matter/issues/311.

I'll leave this open and unassigned and will have it verified on the next RC.

**Comment by KatieWoe** [comment]
I reproduced this and noticed that there was some new lag in the above sims after doing this.

**Comment by KatieWoe** [comment]
looks fixed in rc.2. will reopen if something comes up
