### ISSUE TITLE
Graph size changes with long strings

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/states-of-matter#323]
For https://github.com/phetsims/QA/issues/525. Not in published from what I can tell.
If you have long strings, the phase diagram on the second screen shrinks. It doesn't shrink fully, but is noticeably smaller than normal.
![shrinkinggraph](https://user-images.githubusercontent.com/41024075/89839995-5176b700-db2c-11ea-80a9-45d799c2b22c.gif)

**Comment by KatieWoe** [comment]
I also noticed that the x-axis labels on the two graphs are different, which seems odd and may be related.

**Comment by KatieWoe** [comment]
With short strings they also have different label positions, particularly the y-axis
![difposit](https://user-images.githubusercontent.com/41024075/89947035-15515e00-dbe1-11ea-8b4e-4402e9a63f20.png)

**Comment by jbphet** [comment]
Changes cherry-picked to the 1.2 branch.  I don't consider the centering part to be a problem, so I only addressed the shrinkage during long strings.

**Comment by phet-steele** [comment]
Looks good for phetsims/QA/issues/531

**Comment by KatieWoe** [comment]
Is the overlap with the arrows ok? I think it is, but I wanted to check. Please close again if this is alright.
![overlaparrows](https://user-images.githubusercontent.com/41024075/90421116-259c8980-e076-11ea-857f-79a0a1e74112.png)

**Comment by jbphet** [comment]
I think it's okay, since labels this long are extremely unlikely and having the labels be further from the line to accommodate this rare case doesn't seem like a good trade-off.  Closing.
