### ISSUE TITLE
Should the arrow images stay on the right of the box?

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/states-of-matter#324]
For https://github.com/phetsims/QA/issues/525. This is in the published version.
Some images, such as the atom icons, stay in place when the string labels get shorter. The force arrows icons on the third screen shift left when the strings are shorter.
![movearrows](https://user-images.githubusercontent.com/41024075/89840526-a6ff9380-db2d-11ea-8a40-270a7a7f1187.png)

**Comment by jbphet** [comment]
I vaguely recall discussing this at one time and deciding not to do it, and I think we may have tried it and not liked the way it looked.  In the top control panel, there is a clear correspondence between left and right, and it's a little more complicated in the lower panel.  So, while I appreciate the suggestion, I would advocate for leaving it as is.

@arouinfar - I'll leave the final call to you.

**Comment by arouinfar** [comment]
> I vaguely recall discussing this at one time and deciding not to do it

That sounds familiar to me @jbphet. I'm fine with leaving things the way they are.
