### ISSUE TITLE
Display Only property of temperature box may cause odd looking white space.

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/states-of-matter#327]
For https://github.com/phetsims/QA/issues/525. In regards to the client request:
>Hide K option from temperature display.

This is done with the `statesOfMatter.statesScreen.view.particleContainerNode.compositeThermometerNode.temperatureComboBox.displayOnlyProperty` and `statesOfMatter.phaseChangesScreen.view.particleContainerNode.compositeThermometerNode.temperatureComboBox.displayOnlyProperty` properties. However, when they are used, they simply get rid of the drop down arrow and leave a potentially odd white space to the right. This may want to be visually adjusted.

![oddlookbox](https://user-images.githubusercontent.com/41024075/90051743-6458cb00-dc95-11ea-8d11-8b57d4023fbe.gif)

**Comment by arouinfar** [comment]
@KatieWoe this is the intended behavior of ComboBox's `displayOnlyProperty`. When true, the ComboBox is no longer interactive and the drop-down icon is hidden. Even if we wanted to center the string in the space, I don't think it'd be possible.

Here's an example from ph-scale:
![image](https://user-images.githubusercontent.com/8419308/90053801-35902400-dc98-11ea-9f4a-bb05a586e85c.png)
![image](https://user-images.githubusercontent.com/8419308/90053986-72f4b180-dc98-11ea-93f4-4aa825f0a1f2.png)

The width of the ComboBox is determined by the longest item within it, but that means shorter options will always have lots of negative space to the right regardless of the state of the `displayOnlyProperty`.
![image](https://user-images.githubusercontent.com/8419308/90054309-f1515380-dc98-11ea-8a71-6715b6c56bd1.png)
