### ISSUE TITLE
Should title of Atoms and Molecules box disappear when items are removed?

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/states-of-matter#329]
For https://github.com/phetsims/QA/issues/525. Related to the client request:
>Each atom and molecule should be hideable

If you hide each atom/molecule option on the first or second screen, then the entire box disappears. However, if you do this on the third screen then the title remains. I'm not sure which is the desired behavior, but the inconsistency seems odd.
![atomssticksaround](https://user-images.githubusercontent.com/41024075/90058784-6d4e9a00-dc9f-11ea-9fbd-cabf1ee16506.gif)

**Comment by jbphet** [comment]
The client request is:

> Each atom and molecule should be hideable

I think that the work "each" does not necessarily mean "every", and if they wanted to hide every one, wouldn't they just remove the entire panel?

Having said that, I looked into it and it wasn't too hard to add code to hide the title if the panel contents become empty.  So, the behavior is now consistent between the screens.

**Comment by jbphet** [comment]
This change has been cherry-picked to the 1.2 branch, so it should be fixed in the next RC.

**Comment by KatieWoe** [comment]
Looks good in rc.2. Will reopen if something comes up.
