### ISSUE TITLE
Can we change how the base of the pump looks?

### ISSUE THREAD

**Issue by jbphet** [phetsims/states-of-matter#33]
The base of the pump looks funny to my eye, like it has feet, and I've never seen a bicycle pump with a base that looks anything like this.  In a sim that was targeted at a younger audience, this might be fine, but it looks odd to me in this sim.

![pump](https://cloud.githubusercontent.com/assets/3082831/6361477/e6eca64e-bc3f-11e4-9196-33af22dd2be7.png)

**Comment by arouinfar** [comment]
The foot pads were designed to have a bit more dimension than the straight line that appears in our older sims. 

Here's an example of the look we were going for.
![image](https://cloud.githubusercontent.com/assets/8419308/6361798/38884db6-bc43-11e4-9b9b-a5c613fbc1ef.png)

I'll discuss it with @ariel-phet.

**Comment by arouinfar** [comment]
Just to update -- Alex has previously drawn the pump in 2D for a design task, which we will be revisiting as we redesign the base of the pump.
https://github.com/phetsims/tasks/issues/196

**Comment by arouinfar** [comment]
@jbphet @ariel-phet what do you think about this?

![image](https://cloud.githubusercontent.com/assets/8419308/10109058/d8cc4878-6381-11e5-8189-95b8e0e7d870.png)

**Comment by ariel-phet** [comment]
I think that would work for me. I might go with a different color for the base. Maybe grey as well? Poop brown seems best to be avoided.

**Comment by arouinfar** [comment]
Done!
![image](https://cloud.githubusercontent.com/assets/8419308/10110065/17876614-6388-11e5-8a90-e83b0b249fd4.png)

**Comment by ariel-phet** [comment]
Looks good to me...what do you think @arouinfar

**Comment by arouinfar** [comment]
I'm happy with the look, @ariel-phet. @jbphet originally raised the concern about the look of the base, so I'd like to see what he has to say.

**Comment by arouinfar** [comment]
@jbphet stopped by the office and likes the new base. The pump is drawn in code, so I've emailed him an updated image to use as a reference when creating the new base.

**Comment by jbphet** [comment]
Reopening and assigning to myself to implement the changes.

**Comment by jbphet** [comment]
Implemented, assigning to @arouinfar for review and, if it looks okay, closure.

**Comment by arouinfar** [comment]
@jbphet, I tried to pull the latest version of SOM to phettest, but it looks like there's something broken in scenery. Pulling scenery did not fix the issue.

![image](https://cloud.githubusercontent.com/assets/8419308/10434609/d8b6fcd0-70d7-11e5-93b2-54ee87d4df82.png)

Can you send me a screenshot instead?

**Comment by jbphet** [comment]
Here is what it looks like as of the previous commit:

![som-pump-with-new-base](https://cloud.githubusercontent.com/assets/3082831/10494667/ccf50948-7274-11e5-96dc-3153ad27bc95.png)

**Comment by arouinfar** [comment]
Looks pretty good, @jbphet. 

My only suggestion is to move the hose connection down to the base of the pump, where it originally was.
![image](https://cloud.githubusercontent.com/assets/8419308/10494967/8476a710-7276-11e5-9d54-53f388f42ef8.png)

**Comment by jbphet** [comment]
Ah, yes, I'd missed that.  It now looks like this:

![som-pump-with-new-base](https://cloud.githubusercontent.com/assets/3082831/10527197/62ef9666-734c-11e5-9967-a8c1b1015cb6.png)

**Comment by arouinfar** [comment]
Looks great! Closing.
