### ISSUE TITLE
Add suffix "RadioButton" to individual radio buttons

### ISSUE THREAD

**Issue by jbphet** [phetsims/states-of-matter#334]
In the 8/13/2020 phet-io meeting we decided that radio buttons should have the suffix "RadioButton" in their tandem names.  I had previous not done this because I felt that the fact that the elements were in a radio button group provided sufficient context, but since these items can be sometimes used in isolation, have a more complete name is useful.

There is a global issue that is logged in https://github.com/phetsims/sun/issues/615 where an assert will be added to check this, but I don't think it's important to move this to the current 1.2 RC branch.  I'll just make the change to the tandems and leave it at that.

For historical reference, the discussion that ultimately motivated this decision originated from a discussion about https://github.com/phetsims/states-of-matter/issues/331, but that issue is more about a discrepancy between the client guide and the tandems that are available in the sim.

For my own reference, here is a list of what needs to be done to make this a reality:

- [x] Change the code on master
  - [x] radio button names
- [x] Update the client guide on master
- [x] Check and, if necessary, update the overrides file on master
- [x] Verify that the change works on master and that the phet-io wrappers work
- [x] Propagate these changes to the 1.2 release branch
- [x] Verify that it runs and builds correctly on the 1.2 release branch

**Comment by jbphet** [comment]
Update: This also involves the items in combo boxes, which will impact the thermometer node.

**Comment by pixelzoom** [comment]
I handled this in phetsims/sun#615.  sun cherry-picks are identified in https://github.com/phetsims/sun/issues/615#issuecomment-673707501 and https://github.com/phetsims/sun/issues/615#issuecomment-673730651.

@arouinfar I fixed up the client guide too, please review.

> Update: This also involves the items in combo boxes, which will impact the thermometer node.

Those items are not instrumented.

**Comment by pixelzoom** [comment]
Relevant state-of-matter cherry-pick is 1e888729c8fa5a6b26d12c3dac0603533665f0f6.

Relevant phet-io-client-guides cherry-pick is d90b0b16c09b99f9cc3c0ecad0d2b3059f2e8850

**Comment by jbphet** [comment]
I have cherry-picked the commits for SOM and the client guide to the 1.2 release branch.  As for the common code, I only grabbed the one for radio button names, since the combo box changes are not particularly relevant.  I updated dependencies in SOM, SOMB, and AI, and tested the release branch locally for each.  I think this is ready for deployment.

**Comment by arouinfar** [comment]
@jbphet I added the "RadioButton" suffix to the relevant phetioIDs in SOMB's client-requests.md in the commit above. It will need to be cherry-picked into SOMB.

**Comment by phet-steele** [comment]
Looks good in phetsims/QA/issues/531 and phetsims/QA/issues/532. 🥳
