### ISSUE TITLE
?phetioDebug causes launched Studio sim to not respond

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/states-of-matter#335]
Device
Dirac
OS
Mac 10.12.6
Browser
Chrome
Problem Description
For https://github.com/phetsims/QA/issues/525
When trying to use a launched copy of a sim from studio while using `?phetioDebug` the launched sim is non interactive. It stays on the home screen, even though it was not launched from the home screen. Clicking does nothing and does not let you enter the sim. Mousing over the options brightens them, but you cannot click on them.

Steps:
1. Use the `?phetioDebug` query parameter in studio
2. In studio, go to the first screen, make some change
3. Launch

**Comment by KatieWoe** [comment]
Happens with download html too

**Comment by zepumph** [comment]
This is expected, and the reason for the recent desire to test this feature. It throws an error when setting state. @jbphet brought this to my attention yesterday, see https://github.com/phetsims/states-of-matter/issues/330 for the report and bug fix already in the release branch. This should not happen in the next RC. I don't think you need to test `?phetioDebug` anymore in this version. Sorry for the confusion!

**Comment by KatieWoe** [comment]
Ok. Closing then
