### ISSUE TITLE
Client Guide should include hiding sim title

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/states-of-matter#339]
For https://github.com/phetsims/QA/issues/531.
The client requested:
>Hide each item in the navigation bar

The guide includes these properties:
```
statesOfMatter.general.view.navigationBar.homeButton.visibleProperty
statesOfMatter.general.view.navigationBar.interactionScreenButton.visibleProperty
statesOfMatter.general.view.navigationBar.phaseChangesScreenButton.visibleProperty
statesOfMatter.general.view.navigationBar.statesScreenButton.visibleProperty
statesOfMatter.general.view.navigationBar.phetButton.enabledProperty
```
However it does not include the title text in the bar
`statesOfMatter.general.view.navigationBar.titleText.visibleProperty`
To be clear, this property works fine and the text can be hidden, but the issue is that the guide doesn't include it.

**Comment by arouinfar** [comment]
Thanks @KatieWoe. I've updated the client requests for SOM and SOMB, back to you @jbphet.

**Comment by jbphet** [comment]
changes cherry-picked to the 1.2 branch

**Comment by KatieWoe** [comment]
Looks good in rc.3
