### ISSUE TITLE
Shift Slider on Heat Bucket to the Right

### ISSUE THREAD

**Issue by arouinfar** [phetsims/states-of-matter#34]
This is a duplicate of the issue reported for States of Matter: Basics (https://github.com/phetsims/states-of-matter-basics/issues/2)

The slider on the heat bucket should be shifted to the right to accommodate translations with longer strings.  

dev.2:
![image](https://cloud.githubusercontent.com/assets/8419308/6361937/86b49746-bc44-11e4-97fd-2ef74b230f04.png)

mockup:
![image](https://cloud.githubusercontent.com/assets/8419308/6361945/9b4052a4-bc44-11e4-9f15-91e9a1ae1e5d.png)

The slider on the mockup may be slightly too far to the right, so try shifting the everything over by about the width of the slider. Assigning to @kmsravindra.

**Comment by ChandrashekarBemagoni** [comment]
Fixed in above commit. Assinging to @arouinfar  for verification.

**Comment by arouinfar** [comment]
Looks good, closing.
