### ISSUE TITLE
Add hiding Epsilon and/or Sigma controls to client guide

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/states-of-matter#341]
For https://github.com/phetsims/QA/issues/531.
Related to client request:
> Hide the interaction strength slider

and these properties were given to do this:
```
statesOfMatter.phaseChangesScreen.view.moleculesControlPanel.interactionStrengthSlider.visibleProperty
statesOfMatter.interactionScreen.view.atomsControlPanel.interactionStrengthSlider.visibleProperty
```
In both these cases, the Epsilon control in the interactive graph allows changes without those sliders. This should be updated in the guide. I don't believe the Sigma control is relevant in the guide, but just in case.

**Comment by arouinfar** [comment]
Thanks @KatieWoe. This was a good find. I added the epsilon controls to the SOM guide (irrelevant to SOMB). Since the client didn't have any sigma-related requests, I didn't add the sigma graph controls to the guide.

Back to you @jbphet.

**Comment by jbphet** [comment]
changes cherry-picked to the 1.2 branch

**Comment by KatieWoe** [comment]
Looks good in rc.3
