### ISSUE TITLE
uninstrumented elements appear in Studio tree when they should not

### ISSUE THREAD

**Issue by jbphet** [phetsims/states-of-matter#342]
See https://github.com/phetsims/studio/issues/183

This issue was discovered and reported by @kathy-phet and @amanda-phet, and we have deemed it as blocking for the 1.2.0 release.

**Comment by jbphet** [comment]
fixes pulled to the som 1.2 branch

**Comment by KatieWoe** [comment]
This looks fixed in rc.3

**Comment by KatieWoe** [comment]
I don't seem to be seeing this in https://github.com/phetsims/QA/issues/574
