### ISSUE TITLE
comboBox's enableProperty is not respected when displayOnlyProperty is altered

### ISSUE THREAD

**Issue by phet-steele** [phetsims/states-of-matter#343]
In the Studio wrapper of 1.2.0-rc.2:

1. Find `statesOfMatter.statesScreen.view.particleContainerNode.compositeThermometerNode.temperatureComboBox.enabledProperty` and disable the combo box.
2. Find `statesOfMatter.statesScreen.view.particleContainerNode.compositeThermometerNode.temperatureComboBox.displayOnlyProperty` (just above `enabledProperty`) and toggle it twice, on then off.

You should now be able to interact with the combo box in the sim, even though `enabledProperty` is false. I'm sure this is going to be a general issue for a common code repository.

IMPORTANT NOTE: This issue seems to resolve itself after the sim is launched with customization. In other words, I'm only seeing this happen in the wrapper itself.

Seen on Win 10 FF 80 For phetsims/QA/issues/531 and phetsims/QA/issues/532.

**Comment by jbphet** [comment]
I think it's safe to say that this is not blocking for the 1.2.0 release.

**Comment by kathy-phet** [comment]
@jbphet @arouinfar @kathy-phet - Definitely not blocking for SOM. Probably a small @pixelzoom fix, since he has been working on combo boxes most. 

@pixelzoom - This impacts pH Scale, also. It's not critical because its not a realistic customization. We are OK deferring this fix, but if its quick and you want to fix it, then go ahead.

**Comment by pixelzoom** [comment]
@jbphet I do not see this issue in master or the published version at https://phet-dev.colorado.edu/html/states-of-matter/1.2.0/phet-io/wrappers/studio/.   Did someone fix it, or did it self heal?

**Comment by pixelzoom** [comment]
Oh wait.  I do see it.  The combo box still looks disabled, but you can interact with it (I misunderstood that bit).   I've located the source of the problem, and created https://github.com/phetsims/sun/issues/617.

**Comment by arouinfar** [comment]
While the behavior is buggy, it's the result of unrealistic customization. It is not RC-blocking, and I don't think it's serious enough to include in the maintenance release currently planned for SOM.

I think we can probably close this issue, but I'll let @jbphet decide if he wants to keep it open while the sun issue is unresolved.

**Comment by jbphet** [comment]
I'm happy to close, since I agree that it's the result of an unrealistic customization.
