### ISSUE TITLE
Differing Return Lid behavior when launched mid explosion

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/states-of-matter#347]
For https://github.com/phetsims/QA/issues/536. Likely fairly minor.
If you pause the sim while the lid is exploding on the second screen, and press the Return Lid button while paused, then the molecules will either return to the container or disappear right away. If, however, you are in studio and launch while paused but before returning the lid, then the launched sim will return the lid without adjusting the molecules as described above. If you then step forward it will correct itself.

Steps:
1. In studio, go to the second screen
2. Explode the lid
3. Pause the sim when a few molecules are visible outside the container
4. Launch sim
5. Press return lid

![launchedreturnlid](https://user-images.githubusercontent.com/41024075/90821621-6ef80d80-e2f0-11ea-8aeb-7d6a579b8f89.gif)

**Comment by kathy-phet** [comment]
Impressive find @KatieWoe. 

@jbphet @arouinfar @kathy-phet reviewed this issue and decided it was unlikely to be desirable customization, and it wasn't very problematic even if it occurred. We decided it is not worth the dev time to fix it.
