### ISSUE TITLE
State Buttons Should Deselect when Heat Added/Removed

### ISSUE THREAD

**Issue by arouinfar** [phetsims/states-of-matter#35]
This is a duplicate of the issue reported for States of Matter: Basics (https://github.com/phetsims/states-of-matter-basics/issues/3)

----

When heat is added/removed from the system, the state buttons should deselect. This behavior is present in the original Java sim.

In the screenshot below, the heat was added to solid water until it became a liquid. However, the solid button is still selected.

![image](https://cloud.githubusercontent.com/assets/8419308/6362153/1da8dae8-bc47-11e4-86d5-ca89529209e3.png)

Assigning to @kmsravindra.

**Comment by ChandrashekarBemagoni** [comment]
Fixed in above commits. Assinging to @arouinfar  for verification

**Comment by arouinfar** [comment]
Thanks! Looks good, closing.
