### ISSUE TITLE
Patch PropertyStateHandler memory leak in MR

### ISSUE THREAD

**Issue by zepumph** [phetsims/states-of-matter#350]
A memory leak was outlined and fixed in master over in https://github.com/phetsims/axon/issues/328#issuecomment-681042541. It effects PhET brand. Please follow that link to cherry-pick changes into the next maintenance release of this sim.

**Comment by samreid** [comment]
First, I'd like to check whether this sim is affected by this memory leak.  Self-assigning to test it out before we proceed with a maintenance release.

**Comment by samreid** [comment]
In https://github.com/phetsims/axon/issues/328#issuecomment-681174532 I tested that States of Matter does not trigger this memory leak, even without the fix.  I think this issue can be closed, especially if QA didn't identify another memory problem.  Please reopen if necessary.
