### ISSUE TITLE
Convert to one of the ZoomButtonGroup subclasses

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/states-of-matter#352]
From https://github.com/phetsims/scenery-phet/issues/652, this sim is a candidate for converting to one of the ZoomButtonGroup subclasses.  The Buttons screen of the scenery-phet demo shows the 2 subclasses (screenshot below), PlusMinusZoomButtonGroup on the left, MagnifyingGlassZoomButtonGroup.  If you don't want to change the look of the sim, use MagnifyingGlassZoomButtonGroup.  If you think the more modern-looking PlusMinusZoomButtonGroup is more appropriate, consult with your sim designer.

<img width="398" alt="screenshot_882" src="https://user-images.githubusercontent.com/3046552/109216644-08a5e900-7772-11eb-8e74-9ae05ef4e272.png">

**Comment by jbphet** [comment]
Done, closing.
