### ISSUE TITLE
Provide more specific types than ObjectLiteralIO in MultipleParticleModelIO

### ISSUE THREAD

**Issue by samreid** [phetsims/states-of-matter#355]
From https://github.com/phetsims/phet-io/issues/1774, MultipleParticleModel has ObjectLiteralIO listed twice as a "wildcard".  We should provide more specific types so we can track it in the API.

```js
      isoKineticThermostatState: ObjectLiteralIO, // TODO: https://github.com/phetsims/phet-io/issues/1774
      andersenThermostatState: ObjectLiteralIO,
```

**Comment by jbphet** [comment]
@samreid - in the comment above, you said:

> MultipleParticleModel has ObjectLiteralIO listed twice as a "wildcard".

From the revision history, it looks you're the one who changed these definitions from being `applyState` methods to `ObjectLiteralIO` in 6276d5eb60c84f6afd732a20732c0c677002ca24.  You've assigned this issue to me, so you apparently expect me to address it, but I have no idea at this point what I'm supposed to do here.  The issue you referenced above is quite long.  Is the expectation that I should read through the whole issue and derive from that why this change was made and how it should be addressed in this sim?  Is there something else that you can point me to that might be more efficient, such as some documentation and/or examples?

**Comment by samreid** [comment]
A state value is like:

```js
                "isoKineticThermostatState": {
                  "accumulatedAverageVelocityChange": {
                    "x": 0,
                    "y": 0
                  },
                  "minModelTemperature": 0.005306122448979592,
                  "previousParticleVelocity": {
                    "x": 0,
                    "y": 0
                  },
                  "previousTemperatureScaleFactor": 1,
                  "targetTemperature": 0.15,
                  "totalVelocityChangeThisStep": {
                    "x": 0,
                    "y": 0
                  }
                },
```

I'm not sure how this should be captured in the state schema, or just leave it as ObjectLiteralIO.  @zepumph can you please advise?

**Comment by zepumph** [comment]
I think that this is as easy as creating an IOType with only stateSchema responsibility. How does this look to you @samreid? That way that private state isn't a black box. That said, it's private state, so isn't it allowed to be a block box?

I guess I'd be fine keeping this commit, or reverting it. 

BTW: I found a bug about API generation over in https://github.com/phetsims/phet-io/issues/1801.

**Comment by samreid** [comment]
Excellent, that looks great, thanks!  I think we should keep it. Closing.
