### ISSUE TITLE
Need to add credits

### ISSUE THREAD

**Issue by jbphet** [phetsims/states-of-matter#36]
Current master version has no credits.

**Comment by jbphet** [comment]
Initial credits have been added, will leave this open for now to remind us to finalize them before starting the release process.

**Comment by jbphet** [comment]
Assigning to @ariel-phet to check over the credits and recommend any updates or close.

**Comment by ariel-phet** [comment]
I should be "Ariel" not "Arial" but otherwise looks good.

**Comment by jbphet** [comment]
Fixed (sorry).  Closing.
