### ISSUE TITLE
CT: Uncaught Error: Assertion failed: PhET-iO API error:

### ISSUE THREAD

**Issue by jbphet** [phetsims/states-of-matter#362]
CT is currently failing for SOM and SOMB.  I'll investigate.

Here is the error:

```
states-of-matter : phet-io-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1669067906670/states-of-matter/states-of-matter_en.html?continuousTest=%7B%22test%22%3A%5B%22states-of-matter%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1669067906670%22%2C%22timestamp%22%3A1669071109269%7D&ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Query: ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: PhET-iO API error:
statesOfMatter.phaseChangesScreen.view.particleContainerNode.pressureGaugeNode.gaugeNode.labelText.stringProperty: 8. Any schema entries in the overrides file must be different from its baseline counterpart.
Error: Assertion failed: PhET-iO API error:
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1669067906670/assert/js/assert.js:28:13)
at assert (phetioAPIValidation.ts:253:16)
at assertAPIError (phetioAPIValidation.ts:221:19)
at validateOverridesFile (phetioAPIValidation.ts:85:11)
at onSimStarted (phetioEngine.ts:382:28)
at listener (TinyEmitter.ts:95:8)
at emit (ReadOnlyProperty.ts:311:22)
at _notifyListeners (ReadOnlyProperty.ts:262:13)
at unguardedSet (ReadOnlyProperty.ts:246:11)
at set (Property.ts:54:10)
id: Bayes Puppeteer
Snapshot from 11/21/2022, 2:58:26 PM
```

Screenshot:

![image](https://user-images.githubusercontent.com/3082831/203174313-d334687e-5774-46e3-8398-df07e963fdd2.png)

**Comment by jbphet** [comment]
This was likely caused by https://github.com/phetsims/scenery-phet/commit/74425ac54b59839f24a74c33d0f9b7ec4ecd42c0, where the strings were made into dynamic strings and thus are automatically featured (I think), so now now the API overrides file shouldn't mark it as such.  I've changed this, and it is working locally for me, so I'll commit it and keep an eye on CT.

Tagging @samreid as a reminder that changing common code in this way can cause problems with API override files, and it's nice to fix them proactively if possible.

**Comment by arouinfar** [comment]
@jbphet I added this to the growing list of issues in https://github.com/phetsims/phet-io/issues/1873 documenting phetioFeatured hassles.

**Comment by jbphet** [comment]
CT is now clear, closing.
