### ISSUE TITLE
Particles appear to move twice as fast versus the Java version

### ISSUE THREAD

**Issue by jbphet** [phetsims/states-of-matter#37]
When compared side-to-side with the Java version, particles in the HTML5 version appear to move much faster than those in the Java version when the substance is at the same temperature.  This is particularly noticeable when the substance is in the gaseous state.

This is probably related to the different in frame rates between the sims, since the browser clock rate is 60fps whereas the clock in the Java sim was, I believe, 30 fps.

In my opinion, the slower rate actually looks a bit better - less frenetic and jittery.  I'm going to assign to @arouinfar for her opinion, and she can then assign it to @emily-phet.  Once a decision is made, we can decide whether or not this should be changed.

**Comment by arouinfar** [comment]
I agree with @jbphet. The molecules look a bit too jittery in the HTML5 version. Since neither of us are chemistry content experts, we'd like @emily-phet's input. Do you think having faster molecules could interfere with student learning, or is the current behavior acceptable?

**Comment by emily-phet** [comment]
Hi folks - I agree, the particles are moving too fast now. For example, if you look at water, even at quite low temperatures it's difficult to track individual molecules and notice interesting things (like how there is often particular alignment between hydrogens and oxygen of different water molecules). At higher temperatures, I think it may be distracting to students that some molecules can start rotating so fast you can hardly make out the hydrogen atoms.

**Comment by jbphet** [comment]
Assigning to phet-steele for verification.

**Comment by phet-steele** [comment]
In 1.0.0-dev.5, the particles are moving slower now. They are very similar to the java speed.
