### ISSUE TITLE
Runaway particle in liquid phase

### ISSUE THREAD

**Issue by jbphet** [phetsims/states-of-matter#38]
On the "States" screen, if the user selects Neon or Argon and then switches back and forth between the solid and liquid states, there is often a 'runaway particle' or two, meaning a particle that is separated from the rest of the liquid blob and moving fairly quickly.  In some cases, it's moving very rapidly.  This doesn't occur on the Java version.
 
This problem can be reproduced on http://www.colorado.edu/physics/phet/dev/html/states-of-matter/1.0.0-dev.2/states-of-matter_en.html and on the current master version.

**Comment by ChandrashekarBemagoni** [comment]
Fixed in above commit. Assigning to @jbphet for verification

**Comment by jbphet** [comment]
Assigning to @phet-steele for verification.

**Comment by phet-steele** [comment]
When comparing to the java version, the new behavior is similar. Fixed in 1.0.0-dev.5
