### ISSUE TITLE
SVGBlock error when lid blows off the vessel

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/states-of-matter#41]
To reproduce:

1. Go to "Phase Change" screen
2. Push finger down until top blows off the vessel.
3. Observe endless stream of errors in console:

![screenshot_216](https://cloud.githubusercontent.com/assets/3046552/6405495/44206358-bde1-11e4-85d1-a508e9edfc26.png)

**Comment by pixelzoom** [comment]
@jonathanolson FYI.

**Comment by jonathanolson** [comment]
Let me know about priority (it was on the live-coding list, but I'm happy to just take care of it).

**Comment by jbphet** [comment]
I am not able to duplicate this on either the current master version or the most recently published dev version (v1.0.0-dev.3).  I'm on Chrome+Win7.  Assigning to @jonathanolson for information about whether this was a short-term issue that is now corrected.  If not, he should reassign to @pixelzoom for more info on how to recreate.

**Comment by pixelzoom** [comment]
Fixed by https://github.com/phetsims/scenery/issues/385.
