### ISSUE TITLE
overlapping touch areas

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/states-of-matter#42]
See screenshot. Touch areas should not overlap because (a) user may inadvertently make the wrong selection, and (b) which node is selected will be dependent on scenery graph order, 

![screenshot_217](https://cloud.githubusercontent.com/assets/3046552/6405528/c4632046-bde1-11e4-8103-d09028914c65.png)

**Comment by pixelzoom** [comment]
Actually, this is also true of all the selections in the "Atoms & Molecules" panel, the touch areas (red dashed lines) overlap considerably.

**Comment by jbphet** [comment]
Assigning to @kmsravindra.  I'm pretty sure you know how to view these areas but, just in case, the query param to make them visible is 'showPointerAreas'.

**Comment by ChandrashekarBemagoni** [comment]
Fixed in above commits. Assigning to @pixelzoom for verification

**Comment by pixelzoom** [comment]
Overlap with expand/collapse button is fixed, but I still see overlap in the "Atoms & Molecules" panel. See screenshot below.  Testing with 'master' of all repositories.

![screenshot_487](https://cloud.githubusercontent.com/assets/3046552/6759777/657d5e06-cf08-11e4-9785-42da7d4fddb1.png)

**Comment by pixelzoom** [comment]
I'm guessing that @ChandrashekarBemagoni read only the first comment in this issue. As noted in the 2nd comment:
> Actually, this is also true of all the selections in the "Atoms & Molecules" panel, the touch areas (red dashed lines) overlap considerably.

**Comment by ChandrashekarBemagoni** [comment]
Fixed in above commits. Assigning to @pixelzoom  for verification
