### ISSUE TITLE
Reset All button is too close to panel

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/states-of-matter#43]
See 'Phase Change' screen. There 'Reset All' button looks very crowded, and there's lots of extra space between the panels above it.

![screenshot_220](https://cloud.githubusercontent.com/assets/3046552/6405628/18db46d4-bde3-11e4-9674-25918a4c790f.png)

**Comment by arouinfar** [comment]
I agree, the mockup had the panels and reset all button equally spaced. The panels should also have equal widths. Currently, the Phase Diagram panel is too wide.

![image](https://cloud.githubusercontent.com/assets/8419308/6451119/8b7284e2-c0e9-11e4-8058-2b97f4bebbb5.png)

**Comment by ChandrashekarBemagoni** [comment]
Fixed in above commits. Assigning to @pixelzoom  for verification

**Comment by pixelzoom** [comment]
Tested the above fixes. It looks like spacing is not uniform between the panels, see screenshot below. Assigning to @arouinfar to determine if that's significant.

![screenshot_477](https://cloud.githubusercontent.com/assets/3046552/6510804/9def1b2e-c325-11e4-93c8-232b1a31e4d0.png)

**Comment by arouinfar** [comment]
Spacing around the reset all button looks good, but the Interaction Potential panel should be move up a little bit so it's centered. Reassigning to @ChandrashekarBemagoni.

**Comment by ChandrashekarBemagoni** [comment]
Fixed in above commits. Assigning to @arouinfar for verification

**Comment by arouinfar** [comment]
Thanks, looks good. Closing.
