### ISSUE TITLE
i18n problems with Phase Diagram

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/states-of-matter#44]
There are lots of i18n problems with the 'Phase Diagram' panel on the 'Phase Changes' screen.  

Here's the panel with the default English strings:

![screenshot_220](https://cloud.githubusercontent.com/assets/3046552/6405638/2f448a98-bde3-11e4-82e4-4c84109ddbf7.png)

Here's the panel after I made the strings a tad longer, by adding 'XXXX' to the default English strings(not an unreasonable change in length):

![screenshot_219](https://cloud.githubusercontent.com/assets/3046552/6405648/4fe0b70e-bde3-11e4-8186-50e7e8687552.png)

Problems include:

(1) Panel covers 'Reset All' button, so relative layout is obviously not being done. Vertical axis label should be constrained to be no taller than the vertical axis.

(2) Vertical axis label doesn't remain centered. I'm guessing that the ordering of transforms (translation, rotation) is wrong, and it was made to work for the one specific English string.

(3) The entire panel gets wider, and the 3 panels no longer have the same width. I'm guessing that the computation for the width of the panels isn't generalized.

(4) The panel's title is very cramped, and crowding the expand/collapse button. Title should be scaled once it reaches some maximum (width of the horizontal axis?)

(5) Labels for regions in the graph are clipped (e.g., 'Solid XXXX', 'Critical Point XXXX', ...) and are spilling out into other adjacent regions.  Solution is to constrain them to a maximum size, then scale them down if that maximum is exceeded.

**Comment by ChandrashekarBemagoni** [comment]
Fixed in above commits. Assigning to @pixelzoom for verification
