### ISSUE TITLE
test i18n

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/states-of-matter#45]
Based on https://github.com/phetsims/states-of-matter/issues/44, I wouldn't be surprised if this sim has other i18n problems. Has it been rigorously tested to confirm that its layout will adapt properly to other languages?

**Comment by pixelzoom** [comment]
Confirmed in #46 that there are indeed other i18n issues.

**Comment by ChandrashekarBemagoni** [comment]
Fixed  in above commits . Assigning to @pixelzoom for verification

**Comment by pixelzoom** [comment]
Looks generally good. But there's something odd with the radio buttons in the "States" screen.

With ?stringTest=double, the "Liquid" label is truncated:

![screenshot_516](https://cloud.githubusercontent.com/assets/3046552/7570948/7ea70dfe-f7d1-11e4-82a6-d1d3f81854be.png)

With ?stringTest=ABCDEFGHIJKL, the labels on all 3 buttons are truncated:

![screenshot_517](https://cloud.githubusercontent.com/assets/3046552/7570972/9cb1f17e-f7d1-11e4-9cec-e64d79139ec8.png)

**Comment by ChandrashekarBemagoni** [comment]
Fixed in above commit. Assigning to @pixelzoom for verification

**Comment by pixelzoom** [comment]
Verified that this is fixed. Closing.
