### ISSUE TITLE
problem with "Atoms & Molecules" panel

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/states-of-matter#47]
There's something overlapping the edges of the "Atoms & Molecules" panel in the "Interaction" screen. Here's a screenshot, see how the white border is interrupted on the left and right edges.

master + Mac + all browsers. 

![screenshot_222](https://cloud.githubusercontent.com/assets/3046552/6405801/5174d288-bde5-11e4-8fb7-ed79db7a6753.png)

**Comment by ChandrashekarBemagoni** [comment]
Fixed in latest code.

**Comment by ChandrashekarBemagoni** [comment]
Fixed in latest code.

**Comment by ChandrashekarBemagoni** [comment]
Assinging to @pixelzoom  for verification.

**Comment by jbphet** [comment]
Looks fine now, closing.
