### ISSUE TITLE
argon and oxygen colors are very similar

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/states-of-matter#49]
After fixing oxygen to use 'colorblind red' in #40, argon and oxygen are now very similar in color.  Will this be an issue for colorblind users?  

![screenshot_475](https://cloud.githubusercontent.com/assets/3046552/6446963/08a94522-c0cc-11e4-8e8d-589648a953be.png)

**Comment by jbphet** [comment]
Assigning to @arouinfar, since she did the visual redesign, to decide if one of the colors should be modified to be more distinct.

**Comment by ycarpenterphet** [comment]
It should also be noted that it looks like the colours of the atoms themselves in the Interactions screen were updated to match these icon colors, which makes Argon and Oxygen very difficult to distinguish in Atomic Interactions (where you can have one of each type paired together), especially for a color-blind user:

This is the illustrator color blindness preview (both protanopia and deuteranopia have this problem):
![screen shot 2015-03-02 at 2 09 55 pm](https://cloud.githubusercontent.com/assets/4682895/6450591/29f3a6fe-c0e6-11e4-91d5-732088f64c76.png)

**Comment by arouinfar** [comment]
I updated the red in the mockup to colorblind red and used Illustrator's colorblind preview modes (screenshots below) to check the contrast between argon and oxygen. I think the contrast could be improved.

Protanopia-type:
![image](https://cloud.githubusercontent.com/assets/8419308/6450208/7c2507f4-c0e3-11e4-99fb-23ab47fbea93.png)

Deuteranopia-type:
![image](https://cloud.githubusercontent.com/assets/8419308/6450221/9f62299a-c0e3-11e4-99cc-42fbaf020ffc.png)

If we use the colors from the original Java sim, the contrast improves. 

Protanopia-type:
![image](https://cloud.githubusercontent.com/assets/8419308/6450938/90309ec0-c0e8-11e4-9535-289a8e02d5e4.png)

Deuteranopia-type:
![image](https://cloud.githubusercontent.com/assets/8419308/6450944/9b6fba78-c0e8-11e4-82c9-3f71375ac67b.png)

Assigning to @jbphet to change the colors neon, argon, and adjustable attraction to match the Java version.

**Comment by jbphet** [comment]
This is related to issue #50.

**Comment by jbphet** [comment]
The colors for neon, argon, and adjustable attraction have been updated.  To my eye, argon and adjustable attraction are improvements, since they are more distinct from oxygen.  I have a slight preference for the previous color used for neon, since it was a bit more 'lively'.  Assigning back to @arouinfar to take a look and decide if this is complete or if we should use the other color for neon.

**Comment by arouinfar** [comment]
After speaking with @jbphet, we agreed that the brighter blue used for Neon in the mockups is preferable. Since the brighter blue did not have any contrast issues with the other colors in the colorblind previews, we've decided to switch back to the brighter blue.

**Comment by jbphet** [comment]
Updated the color for neon.  That should be it for this issue, closing.
