### ISSUE TITLE
Checking "project colors" checkbox from options has no affect

### ISSUE THREAD

**Issue by kmsravindra** [phetsims/states-of-matter#5]
Checking "project colors" checkbox from options in the bottom bar, has no affect on sims - states of matter , phases changes.

**Comment by notsiddhartha** [comment]
Fixed above. Assigning to @kmsravindra for verification.

**Comment by kmsravindra** [comment]
Looks good. However in interactions screen - there are 2 minor issues noticed when changing the background to white.
1. the fonts epsilon and sigma are also white on the graph and so they do not appear.
2. The label "Atoms & Molecules" appears to be off-centered from the box.

**Comment by ChandrashekarBemagoni** [comment]
Fixed in latest code .Assigning to @kmsravindra  for verification.

**Comment by kmsravindra** [comment]
Looks good. Closing.
