### ISSUE TITLE
Assertion for removal of node that is not a child

### ISSUE THREAD

**Issue by jbphet** [phetsims/states-of-matter#52]
In the current master version, an assertion is encountered on startup.  It appears to be from the AtomicInteractions screen.  Here is a stack trace with what seemed to me like the relevant bits:

window.assertions.assertFunction (assert.js:22)
extend.removeChild (Node.js?bust=1425328889108:264)
(anonymous function) (AtomicInteracti…5328889108:371)
inherit.link (Property.js?bus…5328889108:161)
AtomicInteractionsControlPanel (AtomicInteracti…5328889108:325)
AtomicInteractionsScreenView (AtomicInteracti…25328889108:78)
(anonymous function) (AtomicInteracti…25328889108:28)
(anonymous function) (Sim.js?bust=1425328889108:404)
St (lodash-2.4.1.mi…25328889108:23)
Sim (Sim.js?bust=1425328889108:394)
(anonymous function) (states-of-matte…25328889108:43)
doneLoadingImages (SimLauncher.js?…25328889108:31)
launch (SimLauncher.js?…25328889108:51)
(anonymous function) (states-of-matte…25328889108:41)

**Comment by ChandrashekarBemagoni** [comment]
Fixed in this commit.https://github.com/phetsims/atomic-interactions/commit/b033e576343a9c8fa4c0f072b3301a554c00b13b

**Comment by jbphet** [comment]
Looks great, closing.
