### ISSUE TITLE
Energy is not conserved in some cases in the "interactions" screen

### ISSUE THREAD

**Issue by jbphet** [phetsims/states-of-matter#53]
On the interactions tab, the atoms don't always retain the same energy level that they start with.  This can be duplicated on version http://www.colorado.edu/physics/phet/dev/html/states-of-matter/1.0.0-dev.4/states-of-matter_en.html.  To see the behavior, open the sim, go to the "Interactions" screen, choose Adjustable Attraction, and slide the diameter all the way down.  Then position the atom as shown in the following screenshot and let it go:

![ai](https://cloud.githubusercontent.com/assets/3082831/6450655/864e89a0-c0e6-11e4-9d97-495f31fbd9a8.png)

After a short time, the particle will stop returning consistently to the starting point, usually starting to oscillate much faster than it was originally (which would correspond to a loss of energy), though I've also seen it appear to gain energy and eventually achieve "escape velocity".

I tried this on the Java sim, and it does not exhibit this problem.

**Comment by ycarpenterphet** [comment]
@notsiddhartha Can you comment on the current state of this issue?

**Comment by notsiddhartha** [comment]
This seems to happen in the java version as well. 
Please find a screen grab from the Java version below:


![som-53](https://cloud.githubusercontent.com/assets/4057790/7563958/d04878cc-f7ff-11e4-9027-9abf0783542c.gif)

**Comment by ycarpenterphet** [comment]
Thanks @notsiddhartha. You are right. It does seem to also occur in the Java simulation.

In both the HTML5 and the Java, this problem seems to only be observable when we have very small values of sigma and very large values for epsilon.

Since this is a bug in Java sim, reassigning to @jbphet

**Comment by jbphet** [comment]
I improved the way that the main model class for this screen - DualAtomModel - handles time stepping, and set a minimum time step such that energy should be conserved in all situations available for this screen.  This should solve the problem.  Assigning to @phet-steele to verify on master.

**Comment by jbphet** [comment]
On second thought, no need for verification.  It looks good to me, and @ariel-phet and I agreed that since it's a rare case and since the Java sim had the issue too, fixing this would basically be "gravy".  It's fixed, so we'll enjoy the gravy and move on.  Closing.
