### ISSUE TITLE
Extend length of arm

### ISSUE THREAD

**Issue by arouinfar** [phetsims/states-of-matter#54]
The hand should be given a bit more of an arm so it extends beyond the bounds of an iPad screen. I can also work with @jbphet to update the artwork so the arm fades away to avoid the severed look at non-standard window sizes.

![img_0049](https://cloud.githubusercontent.com/assets/8419308/6451525/3816583e-c0ec-11e4-8a37-1a6563e0afe0.PNG)

**Comment by jbphet** [comment]
I've modified the artwork to extend the arm and have it fade out at the top.  This was reviewed with @arouinfar, and she felt that it worked.  Closing.
