### ISSUE TITLE
Stroke around Atoms & Molecules panel should be white

### ISSUE THREAD

**Issue by arouinfar** [phetsims/states-of-matter#55]
The stroke around the Atoms & Molecules panel appears to be slightly yellow, as does the stroke around the selection. Both should be white.

![image](https://cloud.githubusercontent.com/assets/8419308/6453882/4e62143e-c100-11e4-8976-e7a30bf3bfac.png)

**Comment by ChandrashekarBemagoni** [comment]
Fixed in above commits. Assiging to @arouinfar  for verification.

**Comment by arouinfar** [comment]
Fixed! Closing.
