### ISSUE TITLE
Phase Diagram panel needs adjusting

### ISSUE THREAD

**Issue by arouinfar** [phetsims/states-of-matter#56]
The Phase Diagram panel on the Phase Changes screen should have the same width as the other panels.  There should also be more negative space between the word "Pressure" and the edge of the panel. The label can be moved closer to the vertical axis. The text within the phase diagram does not match the mockup. The text should all be lower case and the "triple point" and "critical point" labels should be on two lines (as in the Java version). The "Gas" label should also be moved down slightly -- it's currently touching the line separating liquid and gas.

dev.4:
![image](https://cloud.githubusercontent.com/assets/8419308/6453914/afba5818-c100-11e4-925b-8f228ba767c9.png)

Mockup:
![image](https://cloud.githubusercontent.com/assets/8419308/6453926/c83e1d5c-c100-11e4-802d-1411221d2126.png)

**Comment by pixelzoom** [comment]
You're going to have i18n problems with "critical point" being to the right of the point. It already looks cramped, and the only option will be to scale the text down as it gets longer. Recommended to move to the left of the point.

**Comment by pixelzoom** [comment]
@arouinfar You're going to have i18n problems with "critical point" being to the right of the point. It already looks cramped, and the only option will be to scale the text down as it gets longer. Recommended to move to the left of the point.

**Comment by pixelzoom** [comment]
Have you considered right justification of "triple point"? Those 2 words are about the same length in English, but that's not guaranteed for all locales.

**Comment by arouinfar** [comment]
@pixelzoom, thanks for your suggestions. The mockup was designed to look like the Java sim, but if that arrangement will be problematic, I'm happy to tweak it.

It looks like the critical point label runs off the screen in some of the translated versions, so moving it to the left of the point is a good idea. 
![image](https://cloud.githubusercontent.com/assets/8419308/6466299/d6170a96-c183-11e4-8438-040bfe6a6117.png)
![image](https://cloud.githubusercontent.com/assets/8419308/6466337/18e0a1fc-c184-11e4-9159-056f5a71cc11.png)

To make room for the critical point label to the left of the point, the liquid label should be moved up some. The triple point and critical point labels should also be right justified.

**Comment by arouinfar** [comment]
Here's an adjusted mockup showing the changes I've requested.

![image](https://cloud.githubusercontent.com/assets/8419308/6467766/8144c666-c18d-11e4-8f11-9f9271278f10.png)

**Comment by ChandrashekarBemagoni** [comment]
Fixed in latest code .Assigning to @arouinfar  for verification

**Comment by arouinfar** [comment]
There is still some remaining work that must be done to match the spec.
- [ ] triple point and critical point labels should be lower case
- [ ] triple point and critical point labels should be right aligned (currently left aligned)
- [ ] triple point and critical point label should be moved further to the left so that they will not obscured by the point when right aligned

Latest Pull:
![image](https://cloud.githubusercontent.com/assets/8419308/6673921/6557670e-cbe4-11e4-8783-51c59822b443.png)

Spec:
![image](https://cloud.githubusercontent.com/assets/8419308/6673982/c7e9bcdc-cbe4-11e4-8300-70264a7cc321.png)

**Comment by ChandrashekarBemagoni** [comment]
Fixed in above commits. Assigning to @arouinfar  for verification

**Comment by arouinfar** [comment]
The triple point and critical point labels are still not right justified, but this issue has been moved to #70, so closing.
