### ISSUE TITLE
Reduce the height of the Atoms & Molecules panel

### ISSUE THREAD

**Issue by arouinfar** [phetsims/states-of-matter#57]
There is too much negative space between Water and the border of the panel on the States screen. There is a similar issue on the Interaction screen. The height of the panel should be reduced to match the amount of negative space present in the mockup.

dev.4:
![image](https://cloud.githubusercontent.com/assets/8419308/6454082/be1ebb2c-c102-11e4-9a0b-531b4c7bc9ae.png)
![image](https://cloud.githubusercontent.com/assets/8419308/6454033/1d2b1544-c102-11e4-86ac-edc2b1c08293.png)

Mockup:
![image](https://cloud.githubusercontent.com/assets/8419308/6454085/d16b837c-c102-11e4-8e7a-f637cea45bc1.png)
![image](https://cloud.githubusercontent.com/assets/8419308/6454046/3b717d40-c102-11e4-86a6-10739f146cd0.png)

**Comment by ChandrashekarBemagoni** [comment]
Fixed in above commits.Assiging to @arouinfar  for verification

**Comment by arouinfar** [comment]
Looks good, closing.
