### ISSUE TITLE
Adjustable attraction sliders need adjusting to match spec

### ISSUE THREAD

**Issue by arouinfar** [phetsims/states-of-matter#58]
The sliders for the adjustable attraction option need some updating to match the mockup. On the Phase Changes screen, the ends of the slider are disconnected from the body. For all of the sliders, the width should be increased to match the mockup. The sliders and Atom Diameter/Interaction Strength labels should also be centered within the panel.

dev.4 Phase Changes Screen:
![image](https://cloud.githubusercontent.com/assets/8419308/6454129/4f3fd438-c103-11e4-87e2-0d3d85249084.png)

dev.4 Interaction Screen:
![image](https://cloud.githubusercontent.com/assets/8419308/6454168/aa59f27c-c103-11e4-9f69-68b8f6ba2fed.png)

Mockup:
![image](https://cloud.githubusercontent.com/assets/8419308/6454157/99cce4fa-c103-11e4-81b3-9b590dfd427e.png)

**Comment by ChandrashekarBemagoni** [comment]
Fixed in above commits. Assigning to @arouinfar  for verification

**Comment by arouinfar** [comment]
Looks good. Closing.
