### ISSUE TITLE
Interaction potential missing epsilon arrow

### ISSUE THREAD

**Issue by arouinfar** [phetsims/states-of-matter#59]
The interaction potential graph should have two arrows -- one to indicate sigma (atom diameter) and one to indicate epsilon (interaction strength). The location of the epsilon label in the current dev version is fine, but the arrow indicating the depth of the well should be present.

dev.4:
![image](https://cloud.githubusercontent.com/assets/8419308/6469351/ea367f74-c198-11e4-9f0b-f86ae56546bb.png)

Mockup:
![image](https://cloud.githubusercontent.com/assets/8419308/6469332/bf680c54-c198-11e4-8538-2ca691239c4f.png)

**Comment by arouinfar** [comment]
Upon further investigation, I've noticed that the epsilon label shifts and is sometimes obscured by the axis. For example, oxygen selected:
![image](https://cloud.githubusercontent.com/assets/8419308/6469841/fcf89dd2-c19c-11e4-92a4-c298ff24cf1e.png)

If possible, it would be nice to keep the epsilon label in a fixed position above the axis like this:
![image](https://cloud.githubusercontent.com/assets/8419308/6469875/39a52d9a-c19d-11e4-97eb-d12733a8a076.png)

**Comment by ChandrashekarBemagoni** [comment]
Fixed in above commits.Assigning to @arouinfar  for verification

**Comment by arouinfar** [comment]
Behavior now matches the Java version, but could still use a bit more tweaking, so assigning to @jbphet 

The arrow has poor contrast with the yellow curve.
![image](https://cloud.githubusercontent.com/assets/8419308/6563917/7ac5f800-c66a-11e4-8f4d-a31720efd7fe.png)

Let's try adding a black stroke around the epsilon arrow similar to the one around the sigma arrow. I think that should improve the contrast.

**Comment by jbphet** [comment]
I had to adjust the shape of the arrow to make this work, and had to also use a thin stroke to keep the middle of the arrow from disappearing.  I applied the same stroke to the sigma arrow for consistency.  Screenshot below.  Back to @arouinfar for review.

![som-epsilon](https://cloud.githubusercontent.com/assets/3082831/9920992/41604d46-5c96-11e5-86a1-be7bc4d8e45b.png)

**Comment by arouinfar** [comment]
Looks great! Thanks @jbphet. Closing.
