### ISSUE TITLE
Interaction potential for adjustable attraction too deep

### ISSUE THREAD

**Issue by arouinfar** [phetsims/states-of-matter#60]
At the strongest setting, the epsilon arrow extends beyond the boundaries of the interaction potential graph and obscures the axis label. In the Java sim, the maximum well depth does not allow for this to happen. When the interaction strength is at its strongest, there should be no overlap between the epsilon arrow and the horizontal axis.

dev.4:
![image](https://cloud.githubusercontent.com/assets/8419308/6469380/2ef72aa0-c199-11e4-86f0-9091a567641a.png)

Desired maximum depth:
![image](https://cloud.githubusercontent.com/assets/8419308/6469949/b2b28d36-c19d-11e4-841a-5fee532ebc06.png)

**Comment by arouinfar** [comment]
This issue also exists on the Interaction screen.

Maximum allowable depth in dev.4:
![image](https://cloud.githubusercontent.com/assets/8419308/6470917/64569ae0-c1a4-11e4-927b-e3ab53cc46ca.png)

Desired maximum depth:
![image](https://cloud.githubusercontent.com/assets/8419308/6470932/80427b8e-c1a4-11e4-9d54-4853e865f443.png)

**Comment by ycarpenterphet** [comment]
This is unfortunately an issue carried over directly from the Java sim, at least on the larger version of the graph (in both Atomic Interactions, and the Interactions screen of states of matter).

Reassigning to @jbphet to decide if we should be responsible for fixing it, since the issue in the large graph originates in the Java version.

**Comment by arouinfar** [comment]
The issue reported in my first post is not present on the Phase Changes screen of the Java sim. When the interaction strength is at the maximum value, the epsilon arrow does not overlap the horizontal axis.

![image](https://cloud.githubusercontent.com/assets/8419308/6472407/658094e2-c1af-11e4-8233-a1454d081108.png)

@jbphet, should this be split into two separate issues?

**Comment by jbphet** [comment]
Yes, this is two separate issues.  The issue reported in the first post is unique to the HTML5 version, and is not seen in the Java version, so I'm assigning to Actual Concepts.  I will put the issue reported by @ycarpenterphet into a separate issue and disposition it there.

**Comment by ChandrashekarBemagoni** [comment]
Fixed in above commit. Assigning to @jbphet  for verification

**Comment by jbphet** [comment]
The behavior in the graph on the Phase Changes screen now closely matches that of the Java sim.  Assigning to @ycarpenterphet to decide whether further tweaks are desired and, if not, she can close.

**Comment by ycarpenterphet** [comment]
Reassigning to @arouinfar since she can best comment on whether this matches her desired behaviour for the Phase Changes screen.

**Comment by arouinfar** [comment]
It looks like the behavior matches the Java version, but the well depth is still less than the desired depth:

![image](https://cloud.githubusercontent.com/assets/8419308/7326457/a3271da6-ea82-11e4-912c-94261ccf0dea.png)

Reassigning to @jbphet

**Comment by phet-steele** [comment]
@arouinfar, new well depths, may you approve?

![screen shot 2016-06-03 at 10 14 24 am](https://cloud.githubusercontent.com/assets/5863899/15785342/069b64ec-2974-11e6-8518-fd08773f43f1.png)
![screen shot 2016-06-03 at 10 14 41 am](https://cloud.githubusercontent.com/assets/5863899/15785344/098a02ee-2974-11e6-96bc-e3b463ceda4b.png)

**Comment by arouinfar** [comment]
@aadish looks good, but there appears to be a layering issue. The green arrow that adjusts the well depth on the Interaction screen should sit on top of the axes.

**Comment by aadish** [comment]
fixed the layering issue in above commie

**Comment by phet-steele** [comment]
Fixed in 1.0.0-dev.7
