### ISSUE TITLE
Text on solid, liquid, gas buttons should be left aligned

### ISSUE THREAD

**Issue by arouinfar** [phetsims/states-of-matter#61]
The text on the solid, liquid, and gas buttons on the State screen should be left aligned to match the mockup. It's currently right-aligned.

dev.4:
![image](https://cloud.githubusercontent.com/assets/8419308/6473808/0cea1b00-c1b9-11e4-9db3-5cfd1c73eef9.png)

Mockup:
![image](https://cloud.githubusercontent.com/assets/8419308/6473900/d348a2d0-c1b9-11e4-8a80-2672caabff3b.png)

**Comment by ChandrashekarBemagoni** [comment]
Fixed in above commit. Assigning to @arouinfar  for verification

**Comment by arouinfar** [comment]
Looks great, thanks!.
