### ISSUE TITLE
should current-state marker use PhetColorScheme.RED_COLORBLIND ?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/states-of-matter#62]
In PhaseDiagram, line 199:
>     this.currentStateMarker = new Path( new Shape()
      .ellipse( 0, 0, CURRENT_STATE_MARKER_DIAMETER, CURRENT_STATE_MARKER_DIAMETER ), { fill: 'red' } );

Recommend to change 'red' to PhetColorScheme.RED_COLORBLIND.

**Comment by pixelzoom** [comment]
'red' is also used for the value readout in the Pressure gauge, when it exceeds max pressure. See DialGaugeNode line 93:
> dialGaugeNode.textualReadout.fill = 'red';

This is probably OK because it's likely to remain visible to colorblind people. But thought I'd point it out.

**Comment by arouinfar** [comment]
Here's what the color blind previews look like for the current red and colorblind red.

Current red:
![image](https://cloud.githubusercontent.com/assets/8419308/6538966/a75367cc-c426-11e4-9687-f3bb6d04c534.png)   ![image](https://cloud.githubusercontent.com/assets/8419308/6538971/b5716278-c426-11e4-9822-28608e3457bc.png)

Colorblind red:
![image](https://cloud.githubusercontent.com/assets/8419308/6538986/f578953a-c426-11e4-9709-df2fc3b84d50.png)  ![image](https://cloud.githubusercontent.com/assets/8419308/6538976/ceddda20-c426-11e4-9de2-bf2cba17bfc6.png)

I actually refer the current red. It has better contrast the gas section (when comparing the images on the right), so I don't think we need to change it.
