### ISSUE TITLE
Atom selection stroke should be centered within the panel

### ISSUE THREAD

**Issue by arouinfar** [phetsims/states-of-matter#66]
The selection stroke in the Atoms & Molecules panel should be centered within the panel. The padding between the selection stroke and the name/icon of the atom in the latest pull looks good and should be maintained. The iconic atoms/molecules should be moved to the left a little bit so that there is equal space between the left side of the atom/molecule name and the right side of the molecules.

Spec:
![image](https://cloud.githubusercontent.com/assets/8419308/6674396/567700ca-cbe7-11e4-9676-78039f48d693.png)

Latest pull:
![image](https://cloud.githubusercontent.com/assets/8419308/6674413/75df481e-cbe7-11e4-961a-4ab1aebfc1cd.png)

**Comment by ChandrashekarBemagoni** [comment]
Fixed in above commit. Assigning to @arouinfar for verification

**Comment by arouinfar** [comment]
Looks good. Closing.
