### ISSUE TITLE
Update artwork for solid, liquid, gas

### ISSUE THREAD

**Issue by arouinfar** [phetsims/states-of-matter#67]
Artwork for the solid, liquid, gas state buttons on the State screen should match the icons used on the home screen. Self-assigning until artwork for home screen icon is finalized.

![image](https://cloud.githubusercontent.com/assets/8419308/6674506/3335988c-cbe8-11e4-904d-834cb818b3d1.png)
![image](https://cloud.githubusercontent.com/assets/8419308/6674554/8ac1bb62-cbe8-11e4-9615-cf63e3869a98.png)

**Comment by pixelzoom** [comment]
The artwork mentioned above should be checked into the assets/ directory.  When an artist provides image files (png, jpg,...) they are supposed to also provide the associate .ai file.

**Comment by arouinfar** [comment]
I have sent the appropriate artwork and asset files to @jbphet so that they can be checked in. Thanks, @pixelzoom.

**Comment by arouinfar** [comment]
We will be using the artwork that Mariah created in https://github.com/phetsims/tasks/issues/197. I have emailed the assets to @jbphet to implement.

**Comment by jbphet** [comment]
The new artwork is integrated.  Assigning back to @arouinfar to review.  In my opinion, the edges of the icons fade a bit too much into the button background.  We could either adjust the background colors or rework the artwork a bit to have more distinct edges.  Or leave it, if other don't see it as a problem.

**Comment by jbphet** [comment]
@arouinfar is out, and at today's status meeting it was suggested that this be assigned to @amyh-phet.  Changing assignment.

**Comment by amyh-phet** [comment]
I agree that we need to make icons more visible on button.  I will look into possible changes to button background color and update.   @jbphet

**Comment by arouinfar** [comment]
@amyh-phet showed me the updated colors for the buttons. Looks good!

**Comment by jbphet** [comment]
@arouinfar says it looks good.  Closing.
