### ISSUE TITLE
Scale Distance Between Molecules Label

### ISSUE THREAD

**Issue by arouinfar** [phetsims/states-of-matter#68]
Phase Diagram Screen, Interaction Potential Panel
The horizontal axis label displays "Distance Between Atoms" or "Distance Between Molecules" depending on whether or not the selection is an atom or molecule. Currently, the text is too large and displays "Distance Between Molec". Please have the string scale to fit the axis width. This will also be important for translations.

Latest pull:
![image](https://cloud.githubusercontent.com/assets/8419308/6674673/73eeb772-cbe9-11e4-9163-65c9638dce74.png)
![image](https://cloud.githubusercontent.com/assets/8419308/6674680/7dfbf69e-cbe9-11e4-9d0b-c4c1f1607408.png)

**Comment by ChandrashekarBemagoni** [comment]
Fixed in the above commit .Assigning to @arouinfar for verification

**Comment by arouinfar** [comment]
Thanks! Closing.
