### ISSUE TITLE
Tweaks to home screen icons

### ISSUE THREAD

**Issue by arouinfar** [phetsims/states-of-matter#69]
As discussed with @jbphet there are a few changes to make to the home screen icons. 

- [x] Send separate artwork for the solid, liquid, and gas to @jbphet to implement on the state buttons. (Artwork from https://github.com/phetsims/tasks/issues/197 was emailed to JB 4/9/15)
- [x] Add white outline to home screen icons (like in Color Vision)
- [x] Populate States screen icon using the artwork for the solid, liquid, and gas buttons on States screen
- [x] Draw Phase Changes screen icon in code
- [x] Draw Interaction screen icon in code

**Comment by jbphet** [comment]
Icons are now all programmatically generated, assigning to @arouinfar for review.

**Comment by jbphet** [comment]
Since @arouinfar is away I am transferring the assignment to @amyh-phet,

**Comment by amyh-phet** [comment]
Icons look good.   Closing issue.
