### ISSUE TITLE
Dragging the lid up in Phases changes sim

### ISSUE THREAD

**Issue by kmsravindra** [phetsims/states-of-matter#7]
Dragging / Pulling the container lid upwards is somehow not as smooth experience as pushing the lid downwards. The lid sometimes jitters and doesn't very smooth while pulling upwards.

**Comment by ChandrashekarBemagoni** [comment]
Fixed in latest code. Assigning to @kmsravindra  for verification

**Comment by kmsravindra** [comment]
Looks good. Closing
