### ISSUE TITLE
"critical point" and "triple point" are not right justified

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/states-of-matter#70]
Here's a screenshot:

![screenshot_486](https://cloud.githubusercontent.com/assets/3046552/6759721/d06dc8dc-cf07-11e4-9042-9ad4b955b220.png)

Note that the "critical point" and "triple point" labels are not right justified. There is an unwanted space after "critical" and "triple".  Here are the offending string file entries:

```
"triplePoint": "triple \npoint",
"criticalPoint": "critical \npoint",
```

**Comment by jbphet** [comment]
Despite the removal of the spaces in the strings, these labels still don't look quite right in the latest dev version (http://www.colorado.edu/physics/phet/dev/html/states-of-matter/1.0.0-dev.5/states-of-matter_en.html).  Leaving this open and assigned to me.

**Comment by jbphet** [comment]
I've adjusted the positions a bit and things look pretty good at this point.  It's not absolutely perfect, but is acceptable, and I think this is probably as good as it will get given the limitations with text bounds.  Here's a screenshot from Chrome, and it looks quite similar on Firefox and IE.
![som-phase-diagram-1](https://cloud.githubusercontent.com/assets/3082831/9508546/98587422-4c13-11e5-9f66-9403c216d117.png)

**Comment by jbphet** [comment]
done, closing
