### ISSUE TITLE
Annotations should be added for properties, possibly private methods

### ISSUE THREAD

**Issue by jbphet** [phetsims/states-of-matter#74]
The code style guidelines in the PhET Development Overview document (https://docs.google.com/document/d/1odXkliRagq0zuf1_NdOtQ2BrkC9hwlISnPi2y-dKdrk/edit?usp=sharing) describe how annotations such as @private and @public for the properties and methods of a JavaScript object should be used.  I'm not seeing these annotations in the first files that I'm looking at for the code review (e.g. DualAtomModel).  These should be added, as they will make the code significantly more maintainable.

This was found during code review, see #30.

**Comment by ChandrashekarBemagoni** [comment]
Fixed in above commits. Assigning to @jbphet for review.

**Comment by jbphet** [comment]
Thanks, looks good, closing.
