### ISSUE TITLE
DualAtomModel.moleculeTypeProperty should be renamed

### ISSUE THREAD

**Issue by jbphet** [phetsims/states-of-matter#75]
The configuration of the atoms shown on the Atomic Interactions screen is currently controlled by a variable named "moleculeType" in the PropertySet call.  Potential values are NEON_NEON, NEON_OXYGEN, ARGON_ARGON, and so forth.  These are not molecule types - they are pairs of atoms that are in most cases not bound to one another - so the name is misleading.  I suggest renaming this property to "atomPair".

This was found during code review, see #30.

**Comment by jbphet** [comment]
I did this one myself because I need to log some other tickets related to this property, and it will be less confusing if the name is changed now.  Assigning to @kmsravindra so that his team can review and be aware of the change.  He or someone on his dev team can close once reviewed.

**Comment by ChandrashekarBemagoni** [comment]
Looks good, thanks. Closing.
