### ISSUE TITLE
Enum pattern should be used for atom pair selections

### ISSUE THREAD

**Issue by jbphet** [phetsims/states-of-matter#76]
AtomicInteractionsControlPanel.js contains the following code for defining the possible values for the atom pairs:

```js
  var NEON_NEON = 'NEON_NEON';
  var ARGON_ARGON = 'ARGON_ARGON';
  var OXYGEN_OXYGEN = 'OXYGEN_OXYGEN';
  var NEON_ARGON = 'NEON_ARGON';
  var NEON_OXYGEN = 'NEON_OXYGEN';
  var ARGON_OXYGEN = 'ARGON_OXYGEN';
  var ADJUSTABLE = 'ADJUSTABLE';
```

This should be done as an enum pattern in a separate object instead so that it can be shared with DualAtomModel.  Right now, DualAtomModel sets the initial atom pair value to 'NEON_NEON', which could get out of sync with the definitions above.

For an example of the enum pattern that PhET is currently using, please see: https://github.com/phetsims/area-builder/blob/master/js/game/model/GameState.js,

**Comment by pixelzoom** [comment]
@jbphet area-builder.GameState is a little out-of-date as an enum example. I believe that we decide to freeze only when assertions are enabled, because freezing has a (slight?) performance penalty. See graphing-lines.PlayState for an example:

```js
define( function( require ) {
  'use strict';

  var PlayState = {
    FIRST_CHECK: 'FIRST_CHECK', // 'Check' button is visible for the first time
    TRY_AGAIN: 'TRY_AGAIN', // 'Try Again' button is visible
    SECOND_CHECK: 'SECOND_CHECK', // 'Check' button is visible for the second time
    SHOW_ANSWER: 'SHOW_ANSWER', // 'Show Answer' button is visible
    NEXT: 'NEXT', // 'Next' button is visible
    NONE: 'NONE' // use this value when game is not in the 'play' phase
  };

  // verify that enum is immutable, without the runtime penalty in production code
  if ( assert ) { Object.freeze( PlayState ); }

  return PlayState;
} );
```

**Comment by ChandrashekarBemagoni** [comment]
Fixed in above commit. Assigning to @jbphet for review.

**Comment by jbphet** [comment]
Looks great!  Closing.
