### ISSUE TITLE
Should iterations on keys in colors be qualified with hasOwnProperty?

### ISSUE THREAD

**Issue by jbphet** [phetsims/states-of-matter#77]
AtomicInteractionColors contains the following code:

```js
  for ( var key in colors ) {
    initialProperties[ key ] = colors[ key ].default;
  }
```

IntelliJ is highlighting this code with a warning that says "Possible interaction over unexpected (cusom/inherited) members, probably missing hasOwnProperty check".  Unless there is a good reason not to have this check, it should probably be added, for example something like this:

```js
  for ( var key in colors ) {
    if ( colors.hasOwnProperty( key ) ) {
      initialProperties[ key ] = colors[ key ].default;
    }
  }
```

**Comment by jbphet** [comment]
Note that there are several places in this file where the issue occurs, not just the one mentioned above.

**Comment by jbphet** [comment]
This was found during code review, see #30.

**Comment by ChandrashekarBemagoni** [comment]
Fixed in above commit. Assigning to @jbphet for review.

**Comment by jbphet** [comment]
Yep, looks better.  Closing.
