### ISSUE TITLE
Label for selection panel on "Interaction" screen seems odd

### ISSUE THREAD

**Issue by jbphet** [phetsims/states-of-matter#78]
The panel for selecting the interacting atoms on the "Interactions" panel is entitled "Atoms & Molecules", but there aren't any molecules that can be selected.  This seems a little odd, and may cause the users to assume that the "Adjustable" selection is a molecule.  Should this be named something else, like "Atoms" or "Atom Pairs"?

**Comment by arouinfar** [comment]
Looking at the Java version, the panel is labeled "Atoms". This was not an intentional change on my part, so let's switch back to "Atoms". Good catch, @jbphet.

**Comment by jbphet** [comment]
done, closing
