### ISSUE TITLE
Use constant instead of arbitrary number

### ISSUE THREAD

**Issue by jbphet** [phetsims/states-of-matter#79]
Saw this code in AtomicInteractionsControlPanel.  The 150 value should probably be a constant.

```js
      if ( title.width > 150 ) {
        title.setFont( new PhetFont( NORMAL_TEXT_FONT_SIZE * 150 / title.width ) );
      }
```

**Comment by jbphet** [comment]
This was found during code review, see #30.

**Comment by ChandrashekarBemagoni** [comment]
Fixed in above commit. Assigning to @jbphet for review

**Comment by jbphet** [comment]
Looks good, closing.
