### ISSUE TITLE
Use scale() for sizing text instead of changing the font size spec

### ISSUE THREAD

**Issue by jbphet** [phetsims/states-of-matter#80]
The following code (or something similar) is seen in multiple places within AtomicInteractionsControlPanel.js:

```js
      if ( text.width > width ) {
        text.setFont( new PhetFont( NORMAL_TEXT_FONT_SIZE * width / text.width ) );
      }
```

This is a potentially unreliable way to scale the text, since font sizes vary quite a bit across platforms.  The scale method should be used instead, something like:

```js
      if ( text.width > width ) {
        text.scale( width / text.width );
      }
```

This was found during code review, see #30.

**Comment by jbphet** [comment]
This pattern is also seen in ForcesControlPanel.js, and should be fixed there as well.  Seems like this should be a general utility function for the sim.

**Comment by ChandrashekarBemagoni** [comment]
Fixed in above commits and here https://github.com/phetsims/states-of-matter/commit/189dfa689b59d9a7cd1e3f070ed9c631ff970251. Assigning to @jbphet  for review

**Comment by jbphet** [comment]
Looks good - closing.
