### ISSUE TITLE
Consider consolidating createText and createTitleText in AtomicInteractionsControlPanel

### ISSUE THREAD

**Issue by jbphet** [phetsims/states-of-matter#81]
There are two convenience functions in AtomicInteractionsControlPanel that overlap quite a bit in their functionality: createText and createTitleText.  It seems to me like they should be consolidated to improve maintainability.  If there is a good reason not to do so that I'm not seeing, it's okay to write the justification and close this issue.

This was found during code review, see #30.

**Comment by ChandrashekarBemagoni** [comment]
Fixed in above commit.Assigning to @jbphet for review

**Comment by jbphet** [comment]
Looks good, closing.
