### ISSUE TITLE
Consider using Bounds2.dilatedX to set touch areas in AtomicInteractionsControlPanel

### ISSUE THREAD

**Issue by jbphet** [phetsims/states-of-matter#82]
The code that sets the touch areas in AtomicInteractionsControlPanel could be written much more compactly using the dilation functions in Bounds2, e.g. rewrite this:

```js
      neonNeonRadio.touchArea = new Bounds2( neonNeonRadio.localBounds.minX - 5, neonNeonRadio.localBounds.minY,
        neonNeonRadio.localBounds.minX + maxRadioButtonWidth, neonNeonRadio.localBounds.maxY );
```

as:

```js
neonNeonRadio.touchArea = neonNeonRadio.localBounds.dilatedX( 5 );
```

This was found during code review, see #30.

**Comment by jbphet** [comment]
#83 should probably be addressed at the same time as this issue.

**Comment by ChandrashekarBemagoni** [comment]
Fixed in above commit. Assigning to @jbphet  for review.

**Comment by jbphet** [comment]
Much cleaner, thanks.  Closing.
