### ISSUE TITLE
Touch areas on control panel should be closer together without overlapping

### ISSUE THREAD

**Issue by jbphet** [phetsims/states-of-matter#83]
The touch areas in the standalone version of Atomic Interactions has some space between them.  To make touching easier, they should be expanded vertically to where they meet, but do not overlap.

Screenshot of current master version:

![ai-touch-areas](https://cloud.githubusercontent.com/assets/3082831/6968798/a85ec818-d926-11e4-9d44-2c59652abd0e.png)

This should probably be addressed at the same time as #82.

**Comment by ChandrashekarBemagoni** [comment]
Fixed in above commit. Assigning to @jbphet for verifciation

**Comment by jbphet** [comment]
I just tested this on master, and the touch areas look pretty much the same.  I think what you need is a larger expansion in the Y direction versus the X direction.  The current code using the same expansion factor for each.  Assigning back to @ChandrashekarBemagoni.

**Comment by ChandrashekarBemagoni** [comment]
Fixed in above commit. Assigning to @jbphet for verification

**Comment by jbphet** [comment]
Assigning to phet-steele for verification.

**Comment by phet-steele** [comment]
Here's the new touch areas:

![pointerareas](https://cloud.githubusercontent.com/assets/5863899/7685268/40873e44-fd4a-11e4-8012-52c2f67e9163.PNG)

Touching was easy on atomic interactions 1.0.0-dev.8
