### ISSUE TITLE
No need for functions to create the icons in AtomicInteractionsControlPanel

### ISSUE THREAD

**Issue by jbphet** [phetsims/states-of-matter#84]
There are three functions in AtomicInteractionsControlPanel for creating the icons for neon, argon, and adjustable atoms.  Each is only called once.  It would be more clear if they were just constants instead.

This was found during code review, see #30.

**Comment by ChandrashekarBemagoni** [comment]
Fixed in above commit. Assigning to @jbphet for review.

**Comment by jbphet** [comment]
Looks good, closing.
