### ISSUE TITLE
Missing or erroneous header comments

### ISSUE THREAD

**Issue by jbphet** [phetsims/states-of-matter#85]
The following files need some work on their header comments:

DimensionalArrowNode
ParticleNode
AtomicInteractionsScreen
InteractionStrengthTable

This was found during code review, see #30.

**Comment by ChandrashekarBemagoni** [comment]
Fixed in above commit. Assigning to @jbphet for review

**Comment by jbphet** [comment]
Looks good, thanks.  Closing.
