### ISSUE TITLE
Truncated multi-line comments

### ISSUE THREAD

**Issue by jbphet** [phetsims/states-of-matter#89]
I'm seeing a number of cases where multi-line comments from the Java code were only partially moved into the JavaScript code.  I've fixed a number of these instances myself, but I'm seeing enough of them that I think Actual Concepts should probably review and fix.  For example, DiatomicVerletAlgorithm has the following code section:

```js
        this.calculateWallForce( moleculeCenterOfMassPositions[ i ], normalizedContainerWidth,
          normalizedContainerHeight, nextMoleculeForces[ i ] );
        // exerted on the walls of the container.
        if ( nextMoleculeForces[ i ].y < 0 ) {
          pressureZoneWallForce += -nextMoleculeForces[ i ].y;
        }
```

In the original Java code, this looked like:

```java
            calculateWallForce( moleculeCenterOfMassPositions[i], normalizedContainerWidth, normalizedContainerHeight,
                                nextMoleculeForces[i] );

            // Accumulate this force value as part of the pressure being
            // exerted on the walls of the container.
            if ( nextMoleculeForces[i].getY() < 0 ) {
                pressureZoneWallForce += -nextMoleculeForces[i].getY();
            }
```

Note the missing portion of the comment that ends with "exerted on the walls of the container".  It's important for maintainability that these comment be properly moved into the JavaScript code.

This was found during code review, see #30.

**Comment by jbphet** [comment]
I'm seeing a lot of these in WaterPhaseStateChanger.js too.

**Comment by jbphet** [comment]
...and WaterVerletAlgorithm.js...

**Comment by jbphet** [comment]
...and MultiParticleModel.js...

**Comment by ChandrashekarBemagoni** [comment]
Fixed in above commits. Assigning to @jbphet for review

**Comment by jbphet** [comment]
Much better - thanks.  Closing.
