### ISSUE TITLE
Interactions screen - The background of disabled zoomable icons should be much darker

### ISSUE THREAD

**Issue by kmsravindra** [phetsims/states-of-matter#9]
Interactions screen - The background of disabled zoomable icons should be much darker. Please see the mock-up

**Comment by notsiddhartha** [comment]
Fixed here:
https://github.com/phetsims/atomic-interactions/commit/6c102b67d8aa3dafddcffbfa09e77887531b41ec

**Comment by notsiddhartha** [comment]
Fixed above. Assigning to @kmsravindra for verification.

**Comment by kmsravindra** [comment]
Looks good. Closing.
