### ISSUE TITLE
Types can instead by static objects

### ISSUE THREAD

**Issue by jbphet** [phetsims/states-of-matter#92]
I've seen a few cases where something that could be a static object is implemented as a type, requiring a ```new``` to instantiate it before the methods can be used.  In the Java code, the objects are not instantiated and the methods are used statically.  In such cases, the corresponding JavaScript file should not have a constructor, and should just return an object with the required methods.  See #91 as an example of the conversion of such a file.

I'll add more files to this list if I find them, but for now I'm aware of the following:
+ InteractionStrengthTable
+ SigmaTable

This was found during code review, see #30.

**Comment by ChandrashekarBemagoni** [comment]
Fixed in above commit. Assigning to @jbphet for review

**Comment by jbphet** [comment]
Looks good, closing.
