### ISSUE TITLE
original artwork missing for flames and ice cubes

### ISSUE THREAD

**Issue by jbphet** [phetsims/states-of-matter#93]
There is nothing in the "assets" directory for these images (used in the heater/cooler node).  These should be tracked down.

**Comment by jessegreenberg** [comment]
I found the assets in the PhET Unfuddle in piccolo-phet.  They are fire.ai and ice-cube-stack.ai.  I added them to scenery-phet assets, sorry I forgot to reference phetsims/scenery-phet#151 in the commit.

**Comment by jbphet** [comment]
Sounds good.  Since the HeaterCoolerNode is now a common code element, scenery-phet/assets is indeed where these artwork files should be.  I renamed fire.ai to flame.ai so that the .ai and .png file names matched, and updated the license file with these two items.  Closing.
