### ISSUE TITLE
suggestions related to Screen constructors

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/states-of-matter#95]
states-of-matter-main.js:

```js
  SimLauncher.launch( function() {
    var isHeterogeneousMoleculeControlPanel = false;
    var sim = new Sim( simTitle, [
        new SolidLiquidGasScreen( colorsProperty ),
        new PhaseChangesScreen( true, colorsProperty ),
        new AtomicInteractionsScreen( isHeterogeneousMoleculeControlPanel, interactionString, colorsProperty )
      ], simOptions );
    sim.start();
  } );
```

states-of-matter-basics-main.js:

```js
SimLauncher.launch( function() {
    var sim = new Sim( simTitle, [ new SolidLiquidGasScreen( colorsProperty ),
      new PhaseChangesScreen( false, colorsProperty ) ], simOptions );
    sim.start();
  } );
```

Suggestions:

(1) I'm wondering why isHeterogeneousMoleculeControlPanel is pulled out as a var, while the first arg to PhaseChangesScreen (isInteractionDiagramEnabled) is inlined.  In both cases, I think an option would be preferable to a constructor parameter.  Next best would be to inline them both.

(2) Since each Screen constructor has a colorProperty parameter, that parameter should be first in every constructor.

**Comment by ChandrashekarBemagoni** [comment]
Fixed in above commits. Assigning to @pixelzoom for review

**Comment by pixelzoom** [comment]
Looks great, closing.
