### ISSUE TITLE
remove or justify usage of "|*" in type declarations

### ISSUE THREAD

**Issue by jbphet** [phetsims/states-of-matter#96]
In a number of places in the code, the string "|*" is used to specify a type, for example (from DualAtomModel):

```js
      /**
       * @public
       * @returns {null|*}
       */
```

Maybe this is a shorthand of some kind, but not familiar with it and it reads very vaguely to me, like "this function returns null or whatever".  It seems to me like this should only be used in cases where there is some very legitimate reason that the type can't be fully known.  If this is a convention that I'm just unfamiliar with, please explain it (and provide an online reference).  Otherwise, usages should be replaced with more specific type specifications.

**Comment by jbphet** [comment]
Also, {*} is sometimes used as a type spec.  This should also be made more specific.  Example from line 26 of InteractionStrengthTable:

```js
    /**
     * Get the interaction potential between two atoms.  Units are such that
     * the value divided by k-boltzmann is in Kelvin.  This is apparently how
     * it is generally done.  Note that this value is used as the "epsilon"
     * parameter in Lennard-Jones potential calculations.
     * @public
     * @param {string} atomType1
     * @param {string} atomType2
     * @returns {*}
     */
```

**Comment by ChandrashekarBemagoni** [comment]
Fixed in above commits. Assigning to @jbphet for review

**Comment by jbphet** [comment]
Looks good, closing.
