### ISSUE TITLE
primitive types should use lower case

### ISSUE THREAD

**Issue by jbphet** [phetsims/states-of-matter#97]
For example, {number} should be used instead of {Number}.  See the guidelines in the PhET Development Overview document, link = https://docs.google.com/document/d/1odXkliRagq0zuf1_NdOtQ2BrkC9hwlISnPi2y-dKdrk/edit?usp=sharing

**Comment by jbphet** [comment]
@kmsravindra - I implemented this one, but thought I'd pass it on to you and your team to have a look so that you're aware of this for future implementations.  Once you've let the appropriate developers know about it, feel free to close it.

**Comment by pixelzoom** [comment]
The one exception is {Object}, not {object}.

**Comment by pixelzoom** [comment]
Sorry, I misspoke. @jbphet said "primitive" types. Objects is a composite type.

**Comment by ChandrashekarBemagoni** [comment]
Looks good , closing
