### ISSUE TITLE
Update Options menu text to be consistent with other PhET sims

### ISSUE THREAD

**Issue by ycarpenterphet** [phetsims/states-of-matter#98]
The Options menu currently lists "Projector colors" as a checkbox option.

The label should be updated to read "Projector Mode" instead, to be consistent with the label for this option in other PhET simulations.

This change should also affect Atomic Interactions and States of Matter Basics.

**Comment by ChandrashekarBemagoni** [comment]
Fixed in above commit . Assigning to @ycarpenterphet for verification

**Comment by ycarpenterphet** [comment]
Looks good. Closing.
