### ISSUE TITLE
Replace StoveNode with HeaterCoolerNode

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/states-of-matter#99]
The StoveNode used in this sim is a common component that will be used in future sims.  A generalized version of stove-node was recently moved to scenery-phet and renamed as HeaterCoolerNode.  The StoveNodes in both screen views of this sim should be replaced with HeaterCoolerNode.

Related to phetsims/scenery-phet#151.

Assigning the replacement to myself.

**Comment by jessegreenberg** [comment]
StoveNode has been removed from states-of-matter and replaced by HeaterCoolerNode.  Assigning to @jbphet for review.

**Comment by jbphet** [comment]
Looks good, works well, closing.
